// Generated by ANG. Do not edit.
import {
  useQuery,
  useMutation,
  useQueryClient,
  useInfiniteQuery,
  useSuspenseQuery,
  useSuspenseInfiniteQuery,
  UseQueryOptions,
  UseMutationOptions,
  UseSuspenseQueryOptions,
  UseSuspenseInfiniteQueryOptions,
  type InfiniteData,
} from '@tanstack/react-query';
import * as Types from '../types';
import * as QueryOptions from '../query-options';
import * as LegacyQueries from '../queries';
import * as api from '../endpoints';
import { endpointMeta } from '../endpoints/meta';
import { appWsClient, useWebsocketSubscription, useAutoInvalidation, useAppWebsocketSubscription } from './websocket-hooks';
import { WebSocketClient, getWebSocketBaseUrl } from '../websocket';
import { queryKeys } from '../query-keys';
import { useAuthStore } from '../auth-store';
import { useEffect, useRef, useLayoutEffect } from 'react';

export { appWsClient, useWebsocketSubscription, useAppWebsocketSubscription, useAutoInvalidation };


type MutationInvalidateTarget = {
  store: string;
  service?: string;
  rpc?: string;
  scopeParam?: string;
  mode?: 'list' | 'detail' | 'aggregate';
};

type GeneratedMutationContext = {
  queryKey?: readonly unknown[];
  previousData?: unknown;
};

type AuthMutationPayload = {
  accessToken: string;
  refreshToken?: string;
};

const invalidateGeneratedTargets = (
  queryClient: ReturnType<typeof useQueryClient>,
  mutationName: string,
  variables: Record<string, unknown>,
) => {
  const targets = (endpointMeta as Record<string, { invalidateTargets?: MutationInvalidateTarget[] }>)[mutationName]?.invalidateTargets || [];
  for (const target of targets) {
    const storeName = String(target.store || '').toLowerCase();
    const serviceName = String(target.service || '');
    const rpcName = String(target.rpc || '');
    const scopeParam = target.scopeParam;
    const scopeValue = scopeParam ? variables[scopeParam] : undefined;

    if (serviceName && rpcName) {
      queryClient.invalidateQueries({
        predicate: (query) => {
          const key = query.queryKey;
          if (!Array.isArray(key) || key.length < 2) return false;
          if (String(key[0] || '') !== serviceName) return false;
          if (String(key[1] || '') !== rpcName) return false;
          if (target.mode === 'detail' && scopeParam && scopeValue !== undefined && scopeValue !== null && scopeValue !== '') {
            const params = key[2];
            return Boolean(params && typeof params === 'object' && (params as Record<string, unknown>)[scopeParam] === scopeValue);
          }
          return true;
        },
      });
      continue;
    }

    if (target.mode === 'detail' && scopeParam && scopeValue !== undefined && scopeValue !== null && scopeValue !== '') {
      queryClient.invalidateQueries({
        predicate: (query) => {
          const key = query.queryKey;
          if (!Array.isArray(key) || key.length < 3) return false;
          if (String(key[0] || '').toLowerCase() !== storeName) return false;
          const params = key[2];
          return Boolean(params && typeof params === 'object' && (params as Record<string, unknown>)[scopeParam] === scopeValue);
        },
      });
      continue;
    }

    queryClient.invalidateQueries({
      predicate: (query) => {
        const key = query.queryKey;
        return Array.isArray(key) && key.length > 0 && String(key[0] || '').toLowerCase() === storeName;
      },
    });
  }
};

const missingRequiredParamsError = (hookName: string) => new Error(`${hookName} requires all path params before suspense execution`);
export const useChatWithAssistant = (options?: UseMutationOptions<Types.ChatWithAssistantResponse, Error, Types.ChatWithAssistantRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.ChatWithAssistantRequest) => {
      return api.chatWithAssistant(variables);
    },
    ...options,
  });
};
export const useLogin = (options?: UseMutationOptions<Types.LoginResponse, Error, Types.LoginRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.LoginRequest) => {
      return api.login(variables);
    },
    ...options,
  });
};
export const useGetProfile = (params?: Types.GetProfileRequest, options?: Omit<UseQueryOptions<Types.GetProfileResponse, Error, Types.GetProfileResponse, readonly unknown[]>, 'queryKey' | 'queryFn'>) => {
  const hasRequiredParams =true;
  return useQuery<Types.GetProfileResponse, Error>({
    ...QueryOptions.endpointQueryOptions.getProfile((params ?? {}) as Types.GetProfileRequest),
    ...options,
    enabled: hasRequiredParams && (options?.enabled ?? true),
  });
};

export const useGetProfileSuspense = (
  params?: Types.GetProfileRequest,
  options?: Omit<
    UseSuspenseQueryOptions<Types.GetProfileResponse, Error, Types.GetProfileResponse, readonly unknown[]>,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseOptions = QueryOptions.endpointQueryOptions.getProfile((params ?? {}) as Types.GetProfileRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useGetProfileSuspense');
  }
  return useSuspenseQuery<Types.GetProfileResponse, Error>({
    ...baseOptions,
    ...options,
  });
};
export const useUpdateProfile = (options?: UseMutationOptions<Types.UpdateProfileResponse, Error, Types.UpdateProfileRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (variables: Types.UpdateProfileRequest) => {
      return api.updateProfile(variables);
    },
    // Optimistic Update for GetProfile (canonical endpoint query keys only)
    onMutate: async (variables: Types.UpdateProfileRequest) => {
        const _v = variables as unknown as Record<string, unknown>;
        const id = _v['ID'] ?? _v['profileId'];
        // Detail Update
        if (!id) return;
        const queryKey = queryKeys.endpoint.Auth.GetProfile(variables as Types.GetProfileRequest);
        await queryClient.cancelQueries({ queryKey });
        const previousData = queryClient.getQueryData(queryKey);
        queryClient.setQueryData(queryKey, (old: unknown) => {
            return old && typeof old === 'object' ? { ...(old as object), ...variables } : variables;
        });
        return { previousData, queryKey };
    },
    onError: (_err: Error, _variables: Types.UpdateProfileRequest, context: GeneratedMutationContext | undefined) => {
        if (context?.previousData !== undefined && context?.queryKey) {
            queryClient.setQueryData(context.queryKey, context.previousData);
        }
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.UpdateProfileRequest, context: GeneratedMutationContext | undefined) => {
        if (context?.queryKey) {
            queryClient.invalidateQueries({ queryKey: context.queryKey });
        }
        invalidateGeneratedTargets(queryClient, 'updateProfile', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useRegister = (options?: UseMutationOptions<Types.RegisterResponse, Error, Types.RegisterRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.RegisterRequest) => {
      return api.register(variables);
    },
    ...options,
  });
};
export const useDeleteComment = (options?: UseMutationOptions<Types.DeleteCommentResponse, Error, Types.DeleteCommentRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.DeleteCommentRequest) => {
      return api.deleteComment(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.DeleteCommentRequest) => {
        invalidateGeneratedTargets(queryClient, 'deleteComment', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useUpdateComment = (options?: UseMutationOptions<Types.UpdateCommentResponse, Error, Types.UpdateCommentRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.UpdateCommentRequest) => {
      return api.updateComment(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.UpdateCommentRequest) => {
        invalidateGeneratedTargets(queryClient, 'updateComment', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useListMyPosts = (params?: Types.ListMyPostsRequest, options?: Omit<UseQueryOptions<Types.ListMyPostsResponse, Error, Types.ListMyPostsResponse, readonly unknown[]>, 'queryKey' | 'queryFn'>) => {
  const hasRequiredParams =true;
  return useQuery<Types.ListMyPostsResponse, Error>({
    ...QueryOptions.endpointQueryOptions.listMyPosts((params ?? {}) as Types.ListMyPostsRequest),
    ...options,
    enabled: hasRequiredParams && (options?.enabled ?? true),
  });
};

export const useListMyPostsSuspense = (
  params?: Types.ListMyPostsRequest,
  options?: Omit<
    UseSuspenseQueryOptions<Types.ListMyPostsResponse, Error, Types.ListMyPostsResponse, readonly unknown[]>,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseOptions = QueryOptions.endpointQueryOptions.listMyPosts((params ?? {}) as Types.ListMyPostsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useListMyPostsSuspense');
  }
  return useSuspenseQuery<Types.ListMyPostsResponse, Error>({
    ...baseOptions,
    ...options,
  });
};
export const useInfiniteListMyPosts = (params?: Types.ListMyPostsRequest, options?: Record<string, unknown>) => {
  const hasRequiredParams =true;
  return useInfiniteQuery<Types.ListMyPostsResponse, Error, InfiniteData<Types.ListMyPostsResponse>, readonly unknown[], number>({
    ...LegacyQueries.listMyPostsInfiniteQueryOptions((params ?? {}) as Types.ListMyPostsRequest),
    ...options,
    enabled: hasRequiredParams && ((options as { enabled?: boolean } | undefined)?.enabled ?? true),
  });
};

export const useInfiniteListMyPostsSuspense = (
  params?: Types.ListMyPostsRequest,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<
      Types.ListMyPostsResponse,
      Error,
      InfiniteData<Types.ListMyPostsResponse>,
      readonly unknown[],number
    >,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseInfinite = LegacyQueries.listMyPostsInfiniteQueryOptions((params ?? {}) as Types.ListMyPostsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useInfiniteListMyPostsSuspense');
  }
  return useSuspenseInfiniteQuery<Types.ListMyPostsResponse, Error, InfiniteData<Types.ListMyPostsResponse>, readonly unknown[], number>({
    ...baseInfinite,
    ...options,
  });
};
export const useListPosts = (params?: Types.ListPostsRequest, options?: Omit<UseQueryOptions<Types.ListPostsResponse, Error, Types.ListPostsResponse, readonly unknown[]>, 'queryKey' | 'queryFn'>) => {
  const hasRequiredParams =true;
  return useQuery<Types.ListPostsResponse, Error>({
    ...QueryOptions.endpointQueryOptions.listPosts((params ?? {}) as Types.ListPostsRequest),
    ...options,
    enabled: hasRequiredParams && (options?.enabled ?? true),
  });
};

export const useListPostsSuspense = (
  params?: Types.ListPostsRequest,
  options?: Omit<
    UseSuspenseQueryOptions<Types.ListPostsResponse, Error, Types.ListPostsResponse, readonly unknown[]>,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseOptions = QueryOptions.endpointQueryOptions.listPosts((params ?? {}) as Types.ListPostsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useListPostsSuspense');
  }
  return useSuspenseQuery<Types.ListPostsResponse, Error>({
    ...baseOptions,
    ...options,
  });
};
export const useInfiniteListPosts = (params?: Types.ListPostsRequest, options?: Record<string, unknown>) => {
  const hasRequiredParams =true;
  return useInfiniteQuery<Types.ListPostsResponse, Error, InfiniteData<Types.ListPostsResponse>, readonly unknown[], number>({
    ...LegacyQueries.listPostsInfiniteQueryOptions((params ?? {}) as Types.ListPostsRequest),
    ...options,
    enabled: hasRequiredParams && ((options as { enabled?: boolean } | undefined)?.enabled ?? true),
  });
};

export const useInfiniteListPostsSuspense = (
  params?: Types.ListPostsRequest,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<
      Types.ListPostsResponse,
      Error,
      InfiniteData<Types.ListPostsResponse>,
      readonly unknown[],number
    >,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseInfinite = LegacyQueries.listPostsInfiniteQueryOptions((params ?? {}) as Types.ListPostsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useInfiniteListPostsSuspense');
  }
  return useSuspenseInfiniteQuery<Types.ListPostsResponse, Error, InfiniteData<Types.ListPostsResponse>, readonly unknown[], number>({
    ...baseInfinite,
    ...options,
  });
};
export const useCreatePost = (options?: UseMutationOptions<Types.CreatePostResponse, Error, Types.CreatePostRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.CreatePostRequest) => {
      return api.createPost(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.CreatePostRequest) => {
        invalidateGeneratedTargets(queryClient, 'createPost', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useDeletePost = (options?: UseMutationOptions<Types.DeletePostResponse, Error, Types.DeletePostRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.DeletePostRequest) => {
      return api.deletePost(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.DeletePostRequest) => {
        invalidateGeneratedTargets(queryClient, 'deletePost', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useUpdatePost = (options?: UseMutationOptions<Types.UpdatePostResponse, Error, Types.UpdatePostRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (variables: Types.UpdatePostRequest) => {
      return api.updatePost(variables);
    },
    // Optimistic Update for GetPost (canonical endpoint query keys only)
    onMutate: async (variables: Types.UpdatePostRequest) => {
        const _v = variables as unknown as Record<string, unknown>;
        const id = _v['ID'] ?? _v['postId'];
        // Detail Update
        if (!id) return;
        const queryKey = queryKeys.endpoint.Blog.GetPost(variables as Types.GetPostRequest);
        await queryClient.cancelQueries({ queryKey });
        const previousData = queryClient.getQueryData(queryKey);
        queryClient.setQueryData(queryKey, (old: unknown) => {
            return old && typeof old === 'object' ? { ...(old as object), ...variables } : variables;
        });
        return { previousData, queryKey };
    },
    onError: (_err: Error, _variables: Types.UpdatePostRequest, context: GeneratedMutationContext | undefined) => {
        if (context?.previousData !== undefined && context?.queryKey) {
            queryClient.setQueryData(context.queryKey, context.previousData);
        }
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.UpdatePostRequest, context: GeneratedMutationContext | undefined) => {
        if (context?.queryKey) {
            queryClient.invalidateQueries({ queryKey: context.queryKey });
        }
        invalidateGeneratedTargets(queryClient, 'updatePost', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useArchivePost = (options?: UseMutationOptions<Types.ArchivePostResponse, Error, Types.ArchivePostRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.ArchivePostRequest) => {
      return api.archivePost(variables);
    },
    ...options,
  });
};
export const usePublishPost = (options?: UseMutationOptions<Types.PublishPostResponse, Error, Types.PublishPostRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.PublishPostRequest) => {
      return api.publishPost(variables);
    },
    ...options,
  });
};
export const useSubmitPost = (options?: UseMutationOptions<Types.SubmitPostResponse, Error, Types.SubmitPostRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.SubmitPostRequest) => {
      return api.submitPost(variables);
    },
    ...options,
  });
};
export const useListComments = (params?: Types.ListCommentsRequest, options?: Omit<UseQueryOptions<Types.ListCommentsResponse, Error, Types.ListCommentsResponse, readonly unknown[]>, 'queryKey' | 'queryFn'>) => {
  const hasRequiredParams =!!(((params as Types.ListCommentsRequest | undefined)?.postId));
  return useQuery<Types.ListCommentsResponse, Error>({
    ...QueryOptions.endpointQueryOptions.listComments((params ?? {}) as Types.ListCommentsRequest),
    ...options,
    enabled: hasRequiredParams && (options?.enabled ?? true),
  });
};

export const useListCommentsSuspense = (
  params?: Types.ListCommentsRequest,
  options?: Omit<
    UseSuspenseQueryOptions<Types.ListCommentsResponse, Error, Types.ListCommentsResponse, readonly unknown[]>,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =!!(((params as Types.ListCommentsRequest | undefined)?.postId));
  const baseOptions = QueryOptions.endpointQueryOptions.listComments((params ?? {}) as Types.ListCommentsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useListCommentsSuspense');
  }
  return useSuspenseQuery<Types.ListCommentsResponse, Error>({
    ...baseOptions,
    ...options,
  });
};
export const useInfiniteListComments = (params?: Types.ListCommentsRequest, options?: Record<string, unknown>) => {
  const hasRequiredParams =!!(((params as Types.ListCommentsRequest | undefined)?.postId));
  return useInfiniteQuery<Types.ListCommentsResponse, Error, InfiniteData<Types.ListCommentsResponse>, readonly unknown[], number>({
    ...LegacyQueries.listCommentsInfiniteQueryOptions((params ?? {}) as Types.ListCommentsRequest),
    ...options,
    enabled: hasRequiredParams && ((options as { enabled?: boolean } | undefined)?.enabled ?? true),
  });
};

export const useInfiniteListCommentsSuspense = (
  params?: Types.ListCommentsRequest,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<
      Types.ListCommentsResponse,
      Error,
      InfiniteData<Types.ListCommentsResponse>,
      readonly unknown[],number
    >,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =!!(((params as Types.ListCommentsRequest | undefined)?.postId));
  const baseInfinite = LegacyQueries.listCommentsInfiniteQueryOptions((params ?? {}) as Types.ListCommentsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useInfiniteListCommentsSuspense');
  }
  return useSuspenseInfiniteQuery<Types.ListCommentsResponse, Error, InfiniteData<Types.ListCommentsResponse>, readonly unknown[], number>({
    ...baseInfinite,
    ...options,
  });
};
export const useCreateComment = (options?: UseMutationOptions<Types.CreateCommentResponse, Error, Types.CreateCommentRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.CreateCommentRequest) => {
      return api.createComment(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.CreateCommentRequest) => {
        invalidateGeneratedTargets(queryClient, 'createComment', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useGetPost = (params?: Types.GetPostRequest, options?: Omit<UseQueryOptions<Types.GetPostResponse, Error, Types.GetPostResponse, readonly unknown[]>, 'queryKey' | 'queryFn'>) => {
  const hasRequiredParams =!!(((params as Types.GetPostRequest | undefined)?.slug));
  const queryClient = useQueryClient();
  return useQuery<Types.GetPostResponse, Error>({
    placeholderData: () => {
      const id = ((params as Types.GetPostRequest | undefined)?.slug);
      if (!id) return undefined;
      const cachedLists = queryClient.getQueriesData<Types.GetPostResponse>({
        queryKey: ['Blog', 'ListPosts'] as const,
      });
      for (const [, listData] of cachedLists) {
        const found = (listData as { data?: Record<string, unknown>[] } | undefined)?.data?.find(
          (item: Record<string, unknown>) => item['slug'] === id,
        );
        if (found) return { data: found } as unknown as Types.GetPostResponse;
      }
      return undefined;
    },
    ...QueryOptions.endpointQueryOptions.getPost((params ?? {}) as Types.GetPostRequest),
    ...options,
    enabled: hasRequiredParams && (options?.enabled ?? true),
  });
};

export const useGetPostSuspense = (
  params?: Types.GetPostRequest,
  options?: Omit<
    UseSuspenseQueryOptions<Types.GetPostResponse, Error, Types.GetPostResponse, readonly unknown[]>,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =!!(((params as Types.GetPostRequest | undefined)?.slug));
  const baseOptions = QueryOptions.endpointQueryOptions.getPost((params ?? {}) as Types.GetPostRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useGetPostSuspense');
  }
  return useSuspenseQuery<Types.GetPostResponse, Error>({
    ...baseOptions,
    ...options,
  });
};
export const useInfiniteGetPost = (params?: Types.GetPostRequest, options?: Record<string, unknown>) => {
  const hasRequiredParams =!!(((params as Types.GetPostRequest | undefined)?.slug));
  return useInfiniteQuery<Types.GetPostResponse, Error, InfiniteData<Types.GetPostResponse>, readonly unknown[], number>({
    ...LegacyQueries.getPostInfiniteQueryOptions((params ?? {}) as Types.GetPostRequest),
    ...options,
    enabled: hasRequiredParams && ((options as { enabled?: boolean } | undefined)?.enabled ?? true),
  });
};

export const useInfiniteGetPostSuspense = (
  params?: Types.GetPostRequest,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<
      Types.GetPostResponse,
      Error,
      InfiniteData<Types.GetPostResponse>,
      readonly unknown[],number
    >,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =!!(((params as Types.GetPostRequest | undefined)?.slug));
  const baseInfinite = LegacyQueries.getPostInfiniteQueryOptions((params ?? {}) as Types.GetPostRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useInfiniteGetPostSuspense');
  }
  return useSuspenseInfiniteQuery<Types.GetPostResponse, Error, InfiniteData<Types.GetPostResponse>, readonly unknown[], number>({
    ...baseInfinite,
    ...options,
  });
};
export const useListTags = (params?: Types.ListTagsRequest, options?: Omit<UseQueryOptions<Types.ListTagsResponse, Error, Types.ListTagsResponse, readonly unknown[]>, 'queryKey' | 'queryFn'>) => {
  const hasRequiredParams =true;
  return useQuery<Types.ListTagsResponse, Error>({
    ...QueryOptions.endpointQueryOptions.listTags((params ?? {}) as Types.ListTagsRequest),
    ...options,
    enabled: hasRequiredParams && (options?.enabled ?? true),
  });
};

export const useListTagsSuspense = (
  params?: Types.ListTagsRequest,
  options?: Omit<
    UseSuspenseQueryOptions<Types.ListTagsResponse, Error, Types.ListTagsResponse, readonly unknown[]>,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseOptions = QueryOptions.endpointQueryOptions.listTags((params ?? {}) as Types.ListTagsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useListTagsSuspense');
  }
  return useSuspenseQuery<Types.ListTagsResponse, Error>({
    ...baseOptions,
    ...options,
  });
};
export const useInfiniteListTags = (params?: Types.ListTagsRequest, options?: Record<string, unknown>) => {
  const hasRequiredParams =true;
  return useInfiniteQuery<Types.ListTagsResponse, Error, InfiniteData<Types.ListTagsResponse>, readonly unknown[], number>({
    ...LegacyQueries.listTagsInfiniteQueryOptions((params ?? {}) as Types.ListTagsRequest),
    ...options,
    enabled: hasRequiredParams && ((options as { enabled?: boolean } | undefined)?.enabled ?? true),
  });
};

export const useInfiniteListTagsSuspense = (
  params?: Types.ListTagsRequest,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<
      Types.ListTagsResponse,
      Error,
      InfiniteData<Types.ListTagsResponse>,
      readonly unknown[],number
    >,
    'queryKey' | 'queryFn'
  >,
) => {
  const hasRequiredParams =true;
  const baseInfinite = LegacyQueries.listTagsInfiniteQueryOptions((params ?? {}) as Types.ListTagsRequest);
  if (!hasRequiredParams) {
    throw missingRequiredParamsError('useInfiniteListTagsSuspense');
  }
  return useSuspenseInfiniteQuery<Types.ListTagsResponse, Error, InfiniteData<Types.ListTagsResponse>, readonly unknown[], number>({
    ...baseInfinite,
    ...options,
  });
};
export const useCreateTag = (options?: UseMutationOptions<Types.CreateTagResponse, Error, Types.CreateTagRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.CreateTagRequest) => {
      return api.createTag(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.CreateTagRequest) => {
        invalidateGeneratedTargets(queryClient, 'createTag', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useDeleteTag = (options?: UseMutationOptions<Types.DeleteTagResponse, Error, Types.DeleteTagRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.DeleteTagRequest) => {
      return api.deleteTag(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.DeleteTagRequest) => {
        invalidateGeneratedTargets(queryClient, 'deleteTag', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useUpdateTag = (options?: UseMutationOptions<Types.UpdateTagResponse, Error, Types.UpdateTagRequest, GeneratedMutationContext>) => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (variables: Types.UpdateTagRequest) => {
      return api.updateTag(variables);
    },
    onSettled: (_data: unknown, _error: Error | null, _variables: Types.UpdateTagRequest) => {
        invalidateGeneratedTargets(queryClient, 'updateTag', (_variables ?? {}) as Record<string, unknown>);
    },
    ...options,
  });
};
export const useSendInvitationEmail = (options?: UseMutationOptions<Types.SendInvitationEmailResponse, Error, Types.SendInvitationEmailRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.SendInvitationEmailRequest) => {
      return api.sendInvitationEmail(variables);
    },
    ...options,
  });
};
export const useSendPasswordResetEmail = (options?: UseMutationOptions<Types.SendPasswordResetEmailResponse, Error, Types.SendPasswordResetEmailRequest, GeneratedMutationContext>) => {

  return useMutation({
    mutationFn: async (variables: Types.SendPasswordResetEmailRequest) => {
      return api.sendPasswordResetEmail(variables);
    },
    ...options,
  });
};
