// Generated by ANG. Do not edit.
import { useQueryClient, type QueryClient } from '@tanstack/react-query';
import type * as Types from '../types';
import { WebSocketClient, type WebSocketClientOptions, type WSMessage } from '../websocket';
import * as endpoints from '../endpoints';
import { useEffect, useRef, useLayoutEffect } from 'react';

/**
 * Per event: TanStack queryKey prefixes to invalidate (partial match).
 * Built from intent: frontend.ws.invalidateRPCs, invalidateServices, invalidateAll,
 * owner, consumers; or omitted → use defaultWsInvalidatePrefixes.
 */
export const wsInvalidatePrefixesByEventType: Partial<
  Record<WSMessage['type'], readonly (readonly string[])[]>
> = {
  'CommentCreated': [
    ['blog'] as const,
  ],
  'PostCreated': [
    ['blog'] as const,
  ],
  'PostPublished': [
    ['blog'] as const,
  ],
  'PostUpdated': [
    ['blog'] as const,
  ],
  'UserLoggedIn': [
    ['auth'] as const,
  ],
  'UserRegistered': [
    ['auth'] as const,
  ],
};

/** Skip cache invalidation entirely for these WS event types (frontend.ws.noop). */
export const wsInvalidateNoopEventTypes = new Set<string>([
]);

/** When an event type is not listed above: invalidate these service-level prefixes (all GET RPCs under each service). */
export const defaultWsInvalidatePrefixes: readonly (readonly string[])[] = [
  ['Auth'] as const,
  ['Blog'] as const,
];

const defaultWebSocketOptions: WebSocketClientOptions = { handleNetworkEvents: true };

export const defaultWsClients = [
] as const;

const isQueryKeyArray = (value: unknown): value is readonly unknown[] => Array.isArray(value);

const getQueryKeyParams = (queryKey: readonly unknown[]): Record<string, unknown> | null => {
  if (queryKey.length < 3) {
    return null;
  }
  const params = queryKey[2];
  if (!params || typeof params !== 'object' || Array.isArray(params)) {
    return null;
  }
  return params as Record<string, unknown>;
};

const matchesEndpointQuery = (queryKey: readonly unknown[], service: string, rpc: string) =>
  queryKey.length >= 2 && queryKey[0] === service && queryKey[1] === rpc;

const trimPatchedList = <T,>(items: readonly T[], maxSize: number) => {
  if (maxSize <= 0) {
    return items as T[];
  }
  return items.slice(0, maxSize);
};

const eventTimestamp = (payload: unknown) => {
  if (payload && typeof payload === 'object' && !Array.isArray(payload)) {
    const createdAt = (payload as { createdAt?: unknown }).createdAt;
    if (typeof createdAt === 'string' && createdAt.trim() !== '') {
      return createdAt;
    }
  }
  return new Date().toISOString();
};
const applyHotEventCacheUpdate = (_queryClient: QueryClient, _data: WSMessage): boolean => false;

export const subscribeToWebSocketClient = <T extends WSMessage, K extends T['type']>(
  client: WebSocketClient<T>,
  topic: K,
  onMessage: (payload: Extract<T, { type: K }>['payload']) => void
) => client.subscribe((data: T) => {
  if (data.type === topic) {
    const matched = data as Extract<T, { type: K }>;
    const emit = onMessage as (payload: Extract<T, { type: K }>['payload']) => void;
    emit(matched.payload as never);
  }
});

/**
 * App-level helper for singleton sockets.
 * When /ws/app exists, this subscribes only to that canonical socket.
 * Otherwise it falls back to all generated singleton sockets.
 */
export const useWebsocketSubscription = <K extends WSMessage['type']>(
  topic: K,
  onMessage: (payload: Extract<WSMessage, { type: K }>['payload']) => void
) => {
  const onMessageRef = useRef(onMessage);
  useLayoutEffect(() => { onMessageRef.current = onMessage; });

  useEffect(() => {
    // Cast to WebSocketClient<WSMessage>: singleton clients carry all event types at runtime;
    // their static type is narrowed by what the WS endpoint declares, but
    // useWebsocketSubscription is a catch-all that must accept the full WSMessage union.
    const unsubs = (defaultWsClients as unknown as ReadonlyArray<WebSocketClient<WSMessage>>)
      .map((client) => subscribeToWebSocketClient(client, topic, (payload) => {
        const emit = onMessageRef.current as unknown as (payload: Extract<WSMessage, { type: K }>['payload']) => void;
        emit(payload as never);
      }));
    return () => {
      for (const unsub of unsubs) {
        unsub();
      }
    };
  }, [topic]);
};

/**
 * Global hook to automatically invalidate queries based on app-level singleton WS events.
 * Call this once in your App root.
 */
export const useAutoInvalidation = () => {
  const queryClient = useQueryClient();

  useEffect(() => {
    const unsubs = defaultWsClients.map((client) => client.subscribe((data: WSMessage) => {
      const t = String(data.type);
      if (wsInvalidateNoopEventTypes.has(t)) {
        return;
      }
      if (applyHotEventCacheUpdate(queryClient, data)) {
        return;
      }
      const specific = wsInvalidatePrefixesByEventType[data.type];
      const prefixes = specific ?? defaultWsInvalidatePrefixes;
      for (const prefix of prefixes) {
        queryClient.invalidateQueries({ queryKey: prefix });
      }
    }));
    return () => {
      for (const unsub of unsubs) {
        unsub();
      }
    };
  }, [queryClient]);
};
