// Package http provides HTTP handlers for the service.
// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.128
// InputHash: da749d642ad054f87ce6ce781de8c4121fb3e2489a6d0b671c0805e5e1468c97
// CompilerHash: 79cb397a90ef9aac201dfb4974782c5c77878dadc0b507ee261f8141c25ed1d8
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

package http

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/port"
)

func RegisterNotificationsRoutes(r chi.Router, svc port.Notifications) {
	r.With(MaxBodySizeMiddleware(1048576)).Post("/notifications/invitation", handlerSendInvitationEmail(svc))
	r.With(MaxBodySizeMiddleware(1048576)).Post("/notifications/password-reset", handlerSendPasswordResetEmail(svc))
}

// handlerSendInvitationEmail
// Source: cue/schema/types.cue:1433
func handlerSendInvitationEmail(svc port.Notifications) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req port.SendInvitationEmailRequest
		if err := decodeJSONRequest(r, &req); err != nil {
			errors.WriteError(w, r, errors.NewValidationError("Invalid JSON", map[string]string{"body": err.Error()}))
			return
		}
		if err := validate.Struct(&req); err != nil {
			errors.WriteError(w, r, errors.NewValidationError(err.Error(), nil))
			return
		}
		if err := req.Validate(); err != nil {
			errors.WriteError(w, r, errors.NewValidationError(err.Error(), nil))
			return
		}
		resp, err := svc.SendInvitationEmail(r.Context(), req)
		if err != nil {
			errors.WriteError(w, r, err)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)

	}
}

// handlerSendPasswordResetEmail
// Source: cue/schema/types.cue:1433
func handlerSendPasswordResetEmail(svc port.Notifications) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req port.SendPasswordResetEmailRequest
		if err := decodeJSONRequest(r, &req); err != nil {
			errors.WriteError(w, r, errors.NewValidationError("Invalid JSON", map[string]string{"body": err.Error()}))
			return
		}
		if err := validate.Struct(&req); err != nil {
			errors.WriteError(w, r, errors.NewValidationError(err.Error(), nil))
			return
		}
		if err := req.Validate(); err != nil {
			errors.WriteError(w, r, errors.NewValidationError(err.Error(), nil))
			return
		}
		resp, err := svc.SendPasswordResetEmail(r.Context(), req)
		if err != nil {
			errors.WriteError(w, r, err)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)

	}
}
