// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.65
// InputHash: e62c0030d86d5c8cffa7554e48678fea54dad5a6983506b07abe693991d92506
// CompilerHash: c15beb3a865e4334bb63f22948765f50bd374735242722f1d1383a8269976f8a
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

package http

import (
	"encoding/json"
	"net/http"
	"sync"
	"time"

	"github.com/gorilla/websocket"
)

var wsUpgrader = websocket.Upgrader{
	ReadBufferSize:  4096,
	WriteBufferSize: 4096,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

type wsEnvelope struct {
	Type    string          `json:"type"`
	Payload json.RawMessage `json:"payload"`
}

type wsBroadcast struct {
	Type    string      `json:"type"`
	Payload interface{} `json:"payload"`
}

// wsClient represents a connected websocket client.
type wsClient struct {
	hub  *wsHub
	conn *websocket.Conn
	send chan []byte
	room string
}

// wsMessage is a message to be broadcasted to a specific room.
type wsMessage struct {
	room string
	data []byte
}

// wsHub maintains the set of active clients and broadcasts messages to the clients.
type wsHub struct {
	rooms      map[string]map[*wsClient]bool
	broadcast  chan wsMessage
	register   chan *wsClient
	unregister chan *wsClient
	stop       chan struct{}
	mu         sync.RWMutex
}

func newWSHub() *wsHub {
	return &wsHub{
		rooms:      make(map[string]map[*wsClient]bool),
		broadcast:  make(chan wsMessage, 256),
		register:   make(chan *wsClient),
		unregister: make(chan *wsClient),
	}
}

func (h *wsHub) run() {
	for {
		select {
		case client := <-h.register:
			h.mu.Lock()
			if h.rooms[client.room] == nil {
				h.rooms[client.room] = make(map[*wsClient]bool)
			}
			h.rooms[client.room][client] = true
			h.mu.Unlock()
		case client := <-h.unregister:
			h.mu.Lock()
			if conns, ok := h.rooms[client.room]; ok {
				if _, ok := conns[client]; ok {
					delete(conns, client)
					close(client.send)
					if len(conns) == 0 {
						delete(h.rooms, client.room)
					}
				}
			}
			h.mu.Unlock()
		case message := <-h.broadcast:
			h.mu.RLock()
			if message.room == "" {
				for _, conns := range h.rooms {
					for client := range conns {
						select {
						case client.send <- message.data:
						default:
							go func(c *wsClient) { h.unregister <- c }(client)
						}
					}
				}
			} else if conns, ok := h.rooms[message.room]; ok {
				for client := range conns {
					select {
					case client.send <- message.data:
					default:
						go func(c *wsClient) { h.unregister <- c }(client)
					}
				}
			}
			h.mu.RUnlock()
		case <-h.stop:
			h.mu.Lock()
			for _, conns := range h.rooms {
				for client := range conns {
					client.conn.Close()
				}
			}
			h.mu.Unlock()
			return
		}
	}
}

func (c *wsClient) writePump() {
	ticker := time.NewTicker(54 * time.Second)
	defer func() {
		ticker.Stop()
		c.conn.Close()
	}()
	for {
		select {
		case message, ok := <-c.send:
			c.conn.SetWriteDeadline(time.Now().Add(10 * time.Second))
			if !ok {
				c.conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}
			if err := c.conn.WriteMessage(websocket.TextMessage, message); err != nil {
				return
			}
		case <-ticker.C:
			c.conn.SetWriteDeadline(time.Now().Add(10 * time.Second))
			if err := c.conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				return
			}
		}
	}
}

func (c *wsClient) readPump() {
	defer func() {
		c.hub.unregister <- c
		c.conn.Close()
	}()
	c.conn.SetReadLimit(512)
	c.conn.SetReadDeadline(time.Now().Add(60 * time.Second))
	c.conn.SetPongHandler(func(string) error { c.conn.SetReadDeadline(time.Now().Add(60 * time.Second)); return nil })
	for {
		_, _, err := c.conn.ReadMessage()
		if err != nil {
			break
		}
	}
}
