package paymentprovider

import "fmt"

// paymentMethodGoConst maps a platform payment-method SID to the identifier
// in gitlab.q-tech.host/transferty/backend/utils/types. Names are not a
// function of the SID (MastercarddMethod), so generated switches go through
// this table instead of string literals.
var paymentMethodGoConstTable = map[string]string{
	"cards":              "CardsMethod",
	"visa":               "VisaMethod",
	"mastercard":         "MastercarddMethod",
	"amex":               "AmexMethod",
	"discover":           "DiscoverMethod",
	"jcb":                "JCBMethod",
	"unionpay":           "UnionPayMethod",
	"mir":                "MIRMethod",
	"other":              "OtherMethod",
	"skrill":             "SkrillMethod",
	"bitcoin":            "BitcoinMethod",
	"litecoin":           "LitecoinMethod",
	"bitcoincash":        "BitcoinCashMethod",
	"cardano":            "CardanoMethod",
	"ethereum":           "EthereumMethod",
	"ethereumclassic":    "EthereumClassicMethod",
	"dogecoin":           "DogecoinMethod",
	"neo":                "NeoMethod",
	"ripple":             "RippleMethod",
	"augur":              "AugurMethod",
	"tether":             "TetherMethod",
	"tetherusdte":        "TetherUSDTEMethod",
	"tetherusdtt":        "TetherUSDTTMethod",
	"tethereur":          "TetherEURMethod",
	"infinityeconomics":  "InfinityEconomicsMethod",
	"binancecoin":        "BinanceCoinMethod",
	"bitcoinsv":          "BitcoinSVMethod",
	"stasiseur":          "StasisEURMethod",
	"usdcoin":            "USDCoinMethod",
	"tron":               "TRONMethod",
	"binancesmartchain":  "BinanceSmartChainMethod",
	"binanceusd":         "BinanceUSDMethod",
	"coinspaid":          "CoinsPaidMethod",
	"dai":                "DaiMethod",
	"upi":                "UPIMethod",
	"sepa":               "SEPAMethod",
	"papara":             "PaparaMethod",
	"payfix":             "PayfixMethod",
	"mefete":             "MefeteMethod",
	"popypara":           "PopyparaMethod",
	"parazula":           "ParazulaMethod",
	"parolapara":         "ParolaparaMethod",
	"payco":              "PayCoMethod",
	"eft":                "EFTMethod",
	"fasthavale":         "FastHavaleMethod",
	"banktransfer":       "BankTransferMethod",
	"sbp":                "SBPMethod",
	"sberpay":            "SberpayMethod",
	"imps":               "IMPSMethod",
	"paytm":              "PaytmMethod",
	"phonepe":            "PhonePeMethod",
	"walletm10":          "WalletM10Method",
	"cardp2p":            "CardP2PMethod",
	"phonep2p":           "PhoneP2PMethod",
	"emanat":             "EmanatMethod",
	"offramp":            "OffRampMethod",
	"mobilecom":          "MobileComMethod",
	"internationalcard":  "InternationalCardMethod",
	"click":              "ClickMethod",
	"accountnumber":      "AccountNumberMethod",
	"qrnspk":             "QRNSPKMethod",
	"qrcode":             "QRCodeMethod",
	"uzcard":             "UZCARD",
	"humo":               "HUMO",
	"mbank":              "MBANK",
	"optimabank":         "OptimaBank",
	"ovo":                "OVOMethod",
	"grabpay":            "GrabPayMethod",
	"qris":               "QRISMethod",
	"applepay":           "ApplePayMethod",
	"googlepay":          "GooglePayMethod",
	"cent":               "CentMethod",
	"pesonet":            "PesonetMethod",
	"instapay":           "InstaPayMethod",
	"ew":                 "EWMethod",
	"va":                 "VAMethod",
	"sofort":             "SofortMethod",
	"blik":               "BlikMethod",
	"volt":               "VoltMethod",
	"help2pay":           "Help2PayMethod",
	"neteller":           "NetellerMethod",
	"ideal":              "IdealMethod",
	"klarna":             "KlarnaMethod",
	"SPEI":               "SPEIMethod",
	"codi":               "CODIMethod",
	"oxxo":               "OXXOMethod",
	"BANAMEX":            "BANAMEXMethod",
	"BBVAMX":             "BBVAMXMethod",
	"SANTANDER":          "SANTANDERMethod",
	"HSBC_MX":            "HSBCMXMethod",
	"BANORTE":            "BANORTEMethod",
	"AZTECA":             "AZTECAMethod",
	"SCOTIABANK":         "SCOTIABANKMethod",
	"INBURSA":            "INBURSAMethod",
	"BAJIO":              "BAJIOMethod",
	"BANREGIO":           "BANREGIOMethod",
	"BANCOPPEL":          "BANCOPPELMethod",
	"AFIRME":             "AFIRMEMethod",
	"MIFEL":              "MIFELMethod",
	"MULTIVA":            "MULTIVAMethod",
	"INTERCAM":           "INTERCAMMethod",
	"bkash_p2c":          "BkashP2CMethod",
	"bkash_p2p":          "BkashP2PMethod",
	"nagad_p2c":          "NagadP2CMethod",
	"nagad_p2p":          "NagadP2PMethod",
	"jazzcash":           "JazzCashMethod",
	"easypaisa":          "EasyPaisaMethod",
	"CARD":               "CARDMethod",
	"MTP":                "MTPMethod",
	"MTP_INTERNATIONAL":  "MTPInternationalMethod",
	"CARD_INTERNATIONAL": "CARDInternationalMethod",
	"NSPK":               "NSPKMethod",
	"cross_border":       "CrossBorderMethod",
	"havale":             "HavaleMethod",
	"UZCARD":             "UZCARD",
	"HUMO":               "HUMO",
	"MBANK":              "MBANK",
}

func paymentMethodGoConst(sid string) (string, error) {
	name, ok := paymentMethodGoConstTable[sid]
	if !ok || name == "" {
		return "", fmt.Errorf("payment method sid %q has no types.* constant; add it to paymentMethodGoConstTable", sid)
	}
	return name, nil
}
