// Generated by ANG. Do not edit.
import * as Types from '../types';

/**
 * queryKeys registry for TanStack Query.
 * Use these keys for manual invalidation or custom hooks.
 */
export const queryKeys = {
  User: {
    all: ['User'] as const,
  },
} as const;
