"""PDF chart helper used by generated report service."""

from __future__ import annotations

import io
from typing import Any

import matplotlib.pyplot as plt
from fastapi import Response
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


def _to_payload(payload: Any) -> dict[str, Any]:
    if hasattr(payload, "model_dump"):
        return payload.model_dump()
    if isinstance(payload, dict):
        return payload
    return {}


def _normalize_points(raw_points: Any) -> list[dict[str, float]]:
    points: list[dict[str, float]] = []
    if isinstance(raw_points, list):
        for item in raw_points:
            if not isinstance(item, dict):
                continue
            points.append(
                {
                    "x": float(item.get("x", 0)),
                    "y": float(item.get("y", 0)),
                }
            )
    if points:
        return points
    return [
        {"x": 1, "y": 3},
        {"x": 2, "y": 4.2},
        {"x": 3, "y": 2.8},
        {"x": 4, "y": 5.1},
    ]


def generate_pdf_report_response(payload: Any) -> Response:
    data = _to_payload(payload)
    title = str(data.get("title") or "PDF Chart Report")
    points = _normalize_points(data.get("points"))

    xs = [p["x"] for p in points]
    ys = [p["y"] for p in points]

    fig, ax = plt.subplots(figsize=(7, 3.2))
    ax.plot(xs, ys, marker="o", linewidth=2)
    ax.set_title(title)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.grid(alpha=0.3)

    img_buffer = io.BytesIO()
    fig.savefig(img_buffer, format="png", dpi=160, bbox_inches="tight")
    plt.close(fig)
    img_buffer.seek(0)

    pdf_buffer = io.BytesIO()
    pdf = canvas.Canvas(pdf_buffer, pagesize=A4)
    _width, height = A4

    pdf.setTitle(title)
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(40, height - 48, title)
    pdf.setFont("Helvetica", 10)
    pdf.drawString(40, height - 64, "Generated by ANG Python example service")
    pdf.drawImage(
        ImageReader(img_buffer),
        40,
        height - 380,
        width=520,
        height=280,
        preserveAspectRatio=True,
        mask="auto",
    )
    pdf.setFont("Helvetica", 9)
    pdf.drawString(40, 36, "POST /reports/pdf")

    pdf.showPage()
    pdf.save()
    pdf_buffer.seek(0)

    return Response(
        content=pdf_buffer.getvalue(),
        media_type="application/pdf",
        headers={"Content-Disposition": "inline; filename=report.pdf"},
    )

