"""FastAPI app scaffold generated by ANG."""

from fastapi import FastAPI
from app.routers import (
    auth,
    blog,
)

app = FastAPI(title="ANG Service", version="0.1.65")
app.include_router(auth.router)
app.include_router(blog.router)
