"""Domain models scaffold generated by ANG."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel


class Comment(BaseModel):
    id: str
    postID: str
    authorID: str
    parentID: str
    content: str
    createdAt: datetime
    updatedAt: datetime


class Post(BaseModel):
    id: str
    authorID: str
    title: str
    slug: str
    content: str
    excerpt: str
    status: str
    publishedAt: datetime
    viewCount: int
    createdAt: datetime
    updatedAt: datetime


class PostTag(BaseModel):
    postID: str
    tagID: str


class Tag(BaseModel):
    id: str
    name: str
    slug: str
    description: str


class User(BaseModel):
    id: str
    email: str
    passwordHash: str
    name: str
    role: str
    avatarURL: str
    createdAt: datetime
    updatedAt: datetime


class UserVault(BaseModel):
    id: str
    personalKey: str
    bio: str | None = None

