"""Postgres refresh token store stub generated by ANG."""

from __future__ import annotations

from app.security.refresh_store import RefreshTokenStore


class PostgresRefreshTokenStore(RefreshTokenStore):
    async def save(self, token: str, subject: str, expires_at_unix: int) -> None:
        # ANG:BEGIN_CUSTOM RefreshStore.save
        raise NotImplementedError("Implement postgres refresh store save")
        # ANG:END_CUSTOM RefreshStore.save

    async def revoke(self, token: str) -> None:
        # ANG:BEGIN_CUSTOM RefreshStore.revoke
        raise NotImplementedError("Implement postgres refresh store revoke")
        # ANG:END_CUSTOM RefreshStore.revoke

    async def exists(self, token: str) -> bool:
        # ANG:BEGIN_CUSTOM RefreshStore.exists
        raise NotImplementedError("Implement postgres refresh store exists")
        # ANG:END_CUSTOM RefreshStore.exists
