"""Refresh token store port generated by ANG."""

from __future__ import annotations

from typing import Protocol


class RefreshTokenStore(Protocol):
    async def save(self, token: str, subject: str, expires_at_unix: int) -> None: ...
    async def revoke(self, token: str) -> None: ...
    async def exists(self, token: str) -> bool: ...
