"""In-memory refresh token store generated by ANG."""

from __future__ import annotations

from app.security.refresh_store import RefreshTokenStore


class MemoryRefreshTokenStore(RefreshTokenStore):
    def __init__(self) -> None:
        self._tokens: set[str] = set()

    async def save(self, token: str, subject: str, expires_at_unix: int) -> None:
        self._tokens.add(token)

    async def revoke(self, token: str) -> None:
        self._tokens.discard(token)

    async def exists(self, token: str) -> bool:
        return token in self._tokens
