// Code generated by ANG. DO NOT EDIT.
package mock

import (
	"context"

	"github.com/example/blog/internal/port"
)

type MockNotifications struct {
	SendEmailVerificationFunc   func(ctx context.Context, req port.SendEmailVerificationRequest) (port.SendEmailVerificationResponse, error)
	SendEmailVerificationCalls  []MockNotificationsSendEmailVerificationCall
	SendPasswordResetEmailFunc  func(ctx context.Context, req port.SendPasswordResetEmailRequest) (port.SendPasswordResetEmailResponse, error)
	SendPasswordResetEmailCalls []MockNotificationsSendPasswordResetEmailCall
}

var _ port.Notifications = (*MockNotifications)(nil)

func NewNotifications() *MockNotifications {
	return &MockNotifications{}
}

type MockNotificationsSendEmailVerificationCall struct {
	Ctx context.Context
	Req port.SendEmailVerificationRequest
}

func (m *MockNotifications) SendEmailVerification(ctx context.Context, req port.SendEmailVerificationRequest) (port.SendEmailVerificationResponse, error) {
	m.SendEmailVerificationCalls = append(m.SendEmailVerificationCalls, MockNotificationsSendEmailVerificationCall{Ctx: ctx, Req: req})
	if m.SendEmailVerificationFunc != nil {
		return m.SendEmailVerificationFunc(ctx, req)
	}
	var ret0 port.SendEmailVerificationResponse
	var ret1 error
	return ret0, ret1
}

type MockNotificationsSendPasswordResetEmailCall struct {
	Ctx context.Context
	Req port.SendPasswordResetEmailRequest
}

func (m *MockNotifications) SendPasswordResetEmail(ctx context.Context, req port.SendPasswordResetEmailRequest) (port.SendPasswordResetEmailResponse, error) {
	m.SendPasswordResetEmailCalls = append(m.SendPasswordResetEmailCalls, MockNotificationsSendPasswordResetEmailCall{Ctx: ctx, Req: req})
	if m.SendPasswordResetEmailFunc != nil {
		return m.SendPasswordResetEmailFunc(ctx, req)
	}
	var ret0 port.SendPasswordResetEmailResponse
	var ret1 error
	return ret0, ret1
}
