// Code generated by ANG. DO NOT EDIT.
package mock

import (
	"context"

	"github.com/example/blog/internal/port"
)

type MockOutboxRepository struct {
	SaveEventFunc      func(ctx context.Context, id string, topic string, payload []byte) error
	SaveEventCalls     []MockOutboxRepositorySaveEventCall
	ListPendingFunc    func(ctx context.Context, limit int) ([]port.OutboxMessage, error)
	ListPendingCalls   []MockOutboxRepositoryListPendingCall
	MarkProcessedFunc  func(ctx context.Context, id string) error
	MarkProcessedCalls []MockOutboxRepositoryMarkProcessedCall
}

var _ port.OutboxRepository = (*MockOutboxRepository)(nil)

func NewOutboxRepository() *MockOutboxRepository {
	return &MockOutboxRepository{}
}

type MockOutboxRepositorySaveEventCall struct {
	Ctx     context.Context
	ID      string
	Topic   string
	Payload []byte
}

func (m *MockOutboxRepository) SaveEvent(ctx context.Context, id string, topic string, payload []byte) error {
	m.SaveEventCalls = append(m.SaveEventCalls, MockOutboxRepositorySaveEventCall{Ctx: ctx, ID: id, Topic: topic, Payload: payload})
	if m.SaveEventFunc != nil {
		return m.SaveEventFunc(ctx, id, topic, payload)
	}
	var ret0 error
	return ret0
}

type MockOutboxRepositoryListPendingCall struct {
	Ctx   context.Context
	Limit int
}

func (m *MockOutboxRepository) ListPending(ctx context.Context, limit int) ([]port.OutboxMessage, error) {
	m.ListPendingCalls = append(m.ListPendingCalls, MockOutboxRepositoryListPendingCall{Ctx: ctx, Limit: limit})
	if m.ListPendingFunc != nil {
		return m.ListPendingFunc(ctx, limit)
	}
	var ret0 []port.OutboxMessage
	var ret1 error
	return ret0, ret1
}

type MockOutboxRepositoryMarkProcessedCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockOutboxRepository) MarkProcessed(ctx context.Context, id string) error {
	m.MarkProcessedCalls = append(m.MarkProcessedCalls, MockOutboxRepositoryMarkProcessedCall{Ctx: ctx, ID: id})
	if m.MarkProcessedFunc != nil {
		return m.MarkProcessedFunc(ctx, id)
	}
	var ret0 error
	return ret0
}
