// Code generated by ANG. DO NOT EDIT.
package mock

import (
	"context"

	"github.com/example/blog/internal/domain"
	"github.com/example/blog/internal/port"
)

type MockPostRepository struct {
	SaveFunc                   func(ctx context.Context, entity *domain.Post) error
	SaveCalls                  []MockPostRepositorySaveCall
	FindByIDFunc               func(ctx context.Context, id string) (*domain.Post, error)
	FindByIDCalls              []MockPostRepositoryFindByIDCall
	DeleteFunc                 func(ctx context.Context, id string) error
	DeleteCalls                []MockPostRepositoryDeleteCall
	InsertFunc                 func(ctx context.Context, entity *domain.Post) error
	InsertCalls                []MockPostRepositoryInsertCall
	UpdateFunc                 func(ctx context.Context, entity *domain.Post) error
	UpdateCalls                []MockPostRepositoryUpdateCall
	LockByIDFunc               func(ctx context.Context, id string) (*domain.Post, error)
	LockByIDCalls              []MockPostRepositoryLockByIDCall
	CountPublishedFunc         func(ctx context.Context, status string) (int64, error)
	CountPublishedCalls        []MockPostRepositoryCountPublishedCall
	CountPublishedByTagFunc    func(ctx context.Context, status string, id string) (int64, error)
	CountPublishedByTagCalls   []MockPostRepositoryCountPublishedByTagCall
	FindBySlugFunc             func(ctx context.Context, slug string) (*domain.Post, error)
	FindBySlugCalls            []MockPostRepositoryFindBySlugCall
	ListByAuthorFunc           func(ctx context.Context, authorID string) ([]domain.Post, error)
	ListByAuthorCalls          []MockPostRepositoryListByAuthorCall
	ListByAuthorAndStatusFunc  func(ctx context.Context, authorID string, status string) ([]domain.Post, error)
	ListByAuthorAndStatusCalls []MockPostRepositoryListByAuthorAndStatusCall
	ListPublishedFunc          func(ctx context.Context, status string) ([]domain.Post, error)
	ListPublishedCalls         []MockPostRepositoryListPublishedCall
	ListPublishedByTagFunc     func(ctx context.Context, status string, id string) ([]domain.Post, error)
	ListPublishedByTagCalls    []MockPostRepositoryListPublishedByTagCall
	ListAllFunc                func(ctx context.Context, offset int, limit int) ([]domain.Post, error)
	ListAllCalls               []MockPostRepositoryListAllCall
}

var _ port.PostRepository = (*MockPostRepository)(nil)

func NewPostRepository() *MockPostRepository {
	return &MockPostRepository{}
}

type MockPostRepositorySaveCall struct {
	Ctx    context.Context
	Entity *domain.Post
}

func (m *MockPostRepository) Save(ctx context.Context, entity *domain.Post) error {
	m.SaveCalls = append(m.SaveCalls, MockPostRepositorySaveCall{Ctx: ctx, Entity: entity})
	if m.SaveFunc != nil {
		return m.SaveFunc(ctx, entity)
	}
	var ret0 error
	return ret0
}

type MockPostRepositoryFindByIDCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockPostRepository) FindByID(ctx context.Context, id string) (*domain.Post, error) {
	m.FindByIDCalls = append(m.FindByIDCalls, MockPostRepositoryFindByIDCall{Ctx: ctx, ID: id})
	if m.FindByIDFunc != nil {
		return m.FindByIDFunc(ctx, id)
	}
	var ret0 *domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryDeleteCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockPostRepository) Delete(ctx context.Context, id string) error {
	m.DeleteCalls = append(m.DeleteCalls, MockPostRepositoryDeleteCall{Ctx: ctx, ID: id})
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, id)
	}
	var ret0 error
	return ret0
}

type MockPostRepositoryInsertCall struct {
	Ctx    context.Context
	Entity *domain.Post
}

func (m *MockPostRepository) Insert(ctx context.Context, entity *domain.Post) error {
	m.InsertCalls = append(m.InsertCalls, MockPostRepositoryInsertCall{Ctx: ctx, Entity: entity})
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, entity)
	}
	var ret0 error
	return ret0
}

type MockPostRepositoryUpdateCall struct {
	Ctx    context.Context
	Entity *domain.Post
}

func (m *MockPostRepository) Update(ctx context.Context, entity *domain.Post) error {
	m.UpdateCalls = append(m.UpdateCalls, MockPostRepositoryUpdateCall{Ctx: ctx, Entity: entity})
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, entity)
	}
	var ret0 error
	return ret0
}

type MockPostRepositoryLockByIDCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockPostRepository) LockByID(ctx context.Context, id string) (*domain.Post, error) {
	m.LockByIDCalls = append(m.LockByIDCalls, MockPostRepositoryLockByIDCall{Ctx: ctx, ID: id})
	if m.LockByIDFunc != nil {
		return m.LockByIDFunc(ctx, id)
	}
	var ret0 *domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryCountPublishedCall struct {
	Ctx    context.Context
	Status string
}

func (m *MockPostRepository) CountPublished(ctx context.Context, status string) (int64, error) {
	m.CountPublishedCalls = append(m.CountPublishedCalls, MockPostRepositoryCountPublishedCall{Ctx: ctx, Status: status})
	if m.CountPublishedFunc != nil {
		return m.CountPublishedFunc(ctx, status)
	}
	var ret0 int64
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryCountPublishedByTagCall struct {
	Ctx    context.Context
	Status string
	ID     string
}

func (m *MockPostRepository) CountPublishedByTag(ctx context.Context, status string, id string) (int64, error) {
	m.CountPublishedByTagCalls = append(m.CountPublishedByTagCalls, MockPostRepositoryCountPublishedByTagCall{Ctx: ctx, Status: status, ID: id})
	if m.CountPublishedByTagFunc != nil {
		return m.CountPublishedByTagFunc(ctx, status, id)
	}
	var ret0 int64
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryFindBySlugCall struct {
	Ctx  context.Context
	Slug string
}

func (m *MockPostRepository) FindBySlug(ctx context.Context, slug string) (*domain.Post, error) {
	m.FindBySlugCalls = append(m.FindBySlugCalls, MockPostRepositoryFindBySlugCall{Ctx: ctx, Slug: slug})
	if m.FindBySlugFunc != nil {
		return m.FindBySlugFunc(ctx, slug)
	}
	var ret0 *domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryListByAuthorCall struct {
	Ctx      context.Context
	AuthorID string
}

func (m *MockPostRepository) ListByAuthor(ctx context.Context, authorID string) ([]domain.Post, error) {
	m.ListByAuthorCalls = append(m.ListByAuthorCalls, MockPostRepositoryListByAuthorCall{Ctx: ctx, AuthorID: authorID})
	if m.ListByAuthorFunc != nil {
		return m.ListByAuthorFunc(ctx, authorID)
	}
	var ret0 []domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryListByAuthorAndStatusCall struct {
	Ctx      context.Context
	AuthorID string
	Status   string
}

func (m *MockPostRepository) ListByAuthorAndStatus(ctx context.Context, authorID string, status string) ([]domain.Post, error) {
	m.ListByAuthorAndStatusCalls = append(m.ListByAuthorAndStatusCalls, MockPostRepositoryListByAuthorAndStatusCall{Ctx: ctx, AuthorID: authorID, Status: status})
	if m.ListByAuthorAndStatusFunc != nil {
		return m.ListByAuthorAndStatusFunc(ctx, authorID, status)
	}
	var ret0 []domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryListPublishedCall struct {
	Ctx    context.Context
	Status string
}

func (m *MockPostRepository) ListPublished(ctx context.Context, status string) ([]domain.Post, error) {
	m.ListPublishedCalls = append(m.ListPublishedCalls, MockPostRepositoryListPublishedCall{Ctx: ctx, Status: status})
	if m.ListPublishedFunc != nil {
		return m.ListPublishedFunc(ctx, status)
	}
	var ret0 []domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryListPublishedByTagCall struct {
	Ctx    context.Context
	Status string
	ID     string
}

func (m *MockPostRepository) ListPublishedByTag(ctx context.Context, status string, id string) ([]domain.Post, error) {
	m.ListPublishedByTagCalls = append(m.ListPublishedByTagCalls, MockPostRepositoryListPublishedByTagCall{Ctx: ctx, Status: status, ID: id})
	if m.ListPublishedByTagFunc != nil {
		return m.ListPublishedByTagFunc(ctx, status, id)
	}
	var ret0 []domain.Post
	var ret1 error
	return ret0, ret1
}

type MockPostRepositoryListAllCall struct {
	Ctx    context.Context
	Offset int
	Limit  int
}

func (m *MockPostRepository) ListAll(ctx context.Context, offset int, limit int) ([]domain.Post, error) {
	m.ListAllCalls = append(m.ListAllCalls, MockPostRepositoryListAllCall{Ctx: ctx, Offset: offset, Limit: limit})
	if m.ListAllFunc != nil {
		return m.ListAllFunc(ctx, offset, limit)
	}
	var ret0 []domain.Post
	var ret1 error
	return ret0, ret1
}
