"""Repository port for PostTagRepository generated by ANG."""

from __future__ import annotations

from typing import Any, Protocol


class PostTagRepository(Protocol):
    async def delete_by_post(self, *args: Any, **kwargs: Any) -> Any: ...
    async def delete_by_tag(self, *args: Any, **kwargs: Any) -> Any: ...
