"""Repository port for TagRepository generated by ANG."""

from __future__ import annotations

from typing import Any, Protocol


class TagRepository(Protocol):
    async def find_by_slug(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_all(self, *args: Any, **kwargs: Any) -> Any: ...
    async def list_by_post(self, *args: Any, **kwargs: Any) -> Any: ...
