linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/strog/ang

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - stylecheck
    - revive
    - unconvert
    - goconst
    - gocyclo
    - asciicheck
    - gofmt
    - misspell
    - unparam
    - dogsled
    - nakedret
    - exportloopref
    - gocritic

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
    - sdk

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
