// Code generated by ANG. DO NOT EDIT.
package bootstrap

import (
	"context"

	effectmw "github.com/example/minimal/internal/adapter/middleware"
	"github.com/example/minimal/internal/adapter/repository/postgres"
	"github.com/example/minimal/internal/config"
	"github.com/example/minimal/internal/port"
	"github.com/jackc/pgx/v5/pgxpool"
)

type EffectHandler struct {
	Kind     string
	Driver   string
	Provider string
	Options  map[string]any
}

type EffectProfile struct {
	Handlers   map[string]EffectHandler
	Middleware map[string][]effectmw.EffectMiddleware
}

func (p EffectProfile) Handler(kind string) (EffectHandler, bool) {
	v, ok := p.Handlers[kind]
	return v, ok
}

func (p EffectProfile) Chain(kind string) []effectmw.EffectMiddleware {
	return p.Middleware[kind]
}

type EffectRegistry struct {
	RepoUser               port.UserRepository
	Publisher              port.Publisher
	Storage                port.FileStorage
	StateStore             port.StateStore
	NotificationDispatcher port.NotificationDispatcher
	// Runtime EffectProfile metadata
	Runtime EffectProfile
	// Test EffectProfile metadata
	Test EffectProfile
}

func NewEffectRegistry(
	ctx context.Context,
	cfg *config.Config,
	pgPool *pgxpool.Pool,
	publisher port.Publisher,
	notificationDispatcher port.NotificationDispatcher,
) (*EffectRegistry, error) {
	_ = ctx
	reg := &EffectRegistry{
		Publisher:              publisher,
		NotificationDispatcher: notificationDispatcher,
		Runtime:                EffectProfile{Handlers: map[string]EffectHandler{}, Middleware: map[string][]effectmw.EffectMiddleware{}},
		Test:                   EffectProfile{Handlers: map[string]EffectHandler{}, Middleware: map[string][]effectmw.EffectMiddleware{}},
	}
	reg.Publisher = effectmw.WrapPublisher(reg.Publisher, reg.Runtime.Chain("events"))
	reg.RepoUser = postgres.NewUserRepository(pgPool)
	reg.StateStore = effectmw.WrapStateStore(reg.StateStore, reg.Runtime.Chain("state"))
	return reg, nil
}

func NewTestEffectRegistry(publisher port.Publisher, storage port.FileStorage, stateStore port.StateStore) *EffectRegistry {
	reg := &EffectRegistry{
		Publisher:  publisher,
		Storage:    storage,
		StateStore: stateStore,
		Runtime:    EffectProfile{Handlers: map[string]EffectHandler{}, Middleware: map[string][]effectmw.EffectMiddleware{}},
		Test:       EffectProfile{Handlers: map[string]EffectHandler{}, Middleware: map[string][]effectmw.EffectMiddleware{}},
	}
	reg.Publisher = effectmw.WrapPublisher(reg.Publisher, reg.Test.Chain("events"))
	reg.Storage = effectmw.WrapFileStorage(reg.Storage, reg.Test.Chain("storage"))
	reg.StateStore = effectmw.WrapStateStore(reg.StateStore, reg.Test.Chain("state"))
	return reg
}
