"""Report routes generated by ANG."""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, Depends

from app.services.report import ReportService, get_report_service

router = APIRouter(tags=["Report"])

@router.post("/reports/pdf")
async def generate_report_pdf(payload: dict[str, Any], svc: ReportService = Depends(get_report_service)) -> Any:
    return await svc.generate_report_pdf(payload)

