// Generated by ANG. Do not edit.
// Cache invalidation is handled exclusively by TanStack Query in hooks/index.ts.
// registerStoreInvalidator is kept as a no-op for compatibility with legacy entity stores.
export function registerStoreInvalidator(_entity: string, _fn: (...args: any[]) => void): void {}
