package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/strogmv/ang/compiler"
)

// generatorModulePath is the Go module of ANG itself. A generated project never
// declares it, so finding it in the build target means the command was launched
// from the generator checkout by mistake.
const generatorModulePath = "github.com/strogmv/ang"

// ensureGeneratableProject refuses to generate into a directory that is not an
// ANG project.
//
// `ang build` generates the project of the target directory, which defaults to
// the current one. A stray `cd`, a shell that resets the working directory
// between commands, or a copied command line therefore overwrites whatever
// repository happens to be current — including the generator's own checkout,
// whose `cue/` directory makes it look buildable. Failing here costs one stat
// call and turns a silent overwrite into a message.
func ensureGeneratableProject(projectPath, cueRoot string) error {
	base := strings.TrimSpace(projectPath)
	if base == "" {
		base = "."
	}
	abs, err := filepath.Abs(base)
	if err != nil {
		return fmt.Errorf("resolve project path %q: %w", base, err)
	}
	info, err := os.Stat(abs)
	if err != nil {
		return fmt.Errorf("project directory %s is not accessible: %w", abs, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("project path %s is not a directory", abs)
	}
	if isGeneratorCheckout(abs) {
		return fmt.Errorf("refusing to generate into the ANG generator checkout at %s\n"+
			"       `ang build` generates the project of the target directory, not the generator itself.\n"+
			"       Run it from your project directory, or pass --project <dir>", abs)
	}
	root := strings.TrimSpace(cueRoot)
	if root == "" {
		root = compiler.DefaultCueRoot
	}
	cuePath := root
	if !filepath.IsAbs(cuePath) {
		cuePath = filepath.Join(abs, cuePath)
	}
	if info, err := os.Stat(cuePath); err != nil || !info.IsDir() {
		return fmt.Errorf("%s does not look like an ANG project: no CUE root at %s\n"+
			"       Run `ang build` from the project directory, pass --project <dir>, or scaffold one with `ang init`", abs, cuePath)
	}
	return nil
}

// isGeneratorCheckout reports whether dir is the ANG source repository rather
// than a project generated by it.
func isGeneratorCheckout(dir string) bool {
	if data, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			line = strings.TrimSpace(line)
			if !strings.HasPrefix(line, "module ") {
				continue
			}
			return strings.TrimSpace(strings.TrimPrefix(line, "module ")) == generatorModulePath
		}
	}
	// A checkout with no go.mod (or a renamed module) is still recognizable by
	// the generator's own source layout.
	for _, marker := range []string{
		filepath.Join("compiler", "emitter"),
		filepath.Join("cmd", "ang"),
	} {
		info, err := os.Stat(filepath.Join(dir, marker))
		if err != nil || !info.IsDir() {
			return false
		}
	}
	return true
}
