// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Component: UserTable
// Query: useListUsers
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

// ============================================================================
// SECTION: Imports
// PURPOSE: MUI DataGrid for table rendering, React Query for data fetching
// LIBRARIES:
//   - @mui/x-data-grid: Virtualized data table with sorting, pagination
//   - @mui/material: UI components (Avatar, Chip, IconButton, etc.)
//   - dayjs: Date formatting
// ============================================================================
import { useMemo, useState } from 'react';
import { Avatar, Box, Chip, IconButton, Tooltip } from '@mui/material';
import { DataGrid, type GridColDef, type GridPaginationModel, type GridRenderCellParams } from '@mui/x-data-grid';
import { Edit as EditIcon, Delete as DeleteIcon, Visibility as ViewIcon } from '@mui/icons-material';
import dayjs from 'dayjs';
import { useListUsers } from '../../hooks';

// ============================================================================
// SECTION: Component Props
// PURPOSE: Define table component interface
// PROPS:
//   - onView: View row details callback
//   - onEdit: Edit row callback (opens update form)
//   - onDelete: Delete row callback
// ============================================================================
export interface UserTableProps {
  onView?: (row: any) => void;
  onEdit?: (row: any) => void;
  onDelete?: (row: any) => void;
}

// ============================================================================
// SECTION: Table Component
// PURPOSE: Render paginated data table with action buttons
// PATTERN: MUI DataGrid with useMemo for column definitions
// DATA: Fetched via useListUsers hook (React Query)
// ============================================================================
export function UserTable({ onView, onEdit, onDelete }: UserTableProps) {
  const [paginationModel, setPaginationModel] = useState<GridPaginationModel>({
    page: 0,
    pageSize: 25,
  });

  const { data, isLoading } = useListUsers({
    limit: paginationModel.pageSize,
    offset: paginationModel.page * paginationModel.pageSize,
  });

  const columns = useMemo<GridColDef[]>(() => [
    {
      field: 'id',
      headerName: 'ID',
      width: 100,
      sortable: true,
    },
    {
      field: 'email',
      headerName: 'Email',
      minWidth: 120,
      flex: 1,
      sortable: true,
    },
    {
      field: 'name',
      headerName: 'Name',
      minWidth: 120,
      flex: 1,
      sortable: true,
    },
    {
      field: 'actions',
      headerName: 'Действия',
      width: 120,
      sortable: false,
      renderCell: (params: GridRenderCellParams) => (
        <Box>
          {onView && (
            <Tooltip title="Просмотр">
              <IconButton size="small" onClick={() => onView(params.row)}>
                <ViewIcon fontSize="small" />
              </IconButton>
            </Tooltip>
          )}
          {onEdit && (
            <Tooltip title="Редактировать">
              <IconButton size="small" onClick={() => onEdit(params.row)}>
                <EditIcon fontSize="small" />
              </IconButton>
            </Tooltip>
          )}
          {onDelete && (
            <Tooltip title="Удалить">
              <IconButton size="small" onClick={() => onDelete(params.row)}>
                <DeleteIcon fontSize="small" color="error" />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      ),
    },
  ], [onView, onEdit, onDelete]);

  return (
    <Box sx={{ width: '100%', overflowX: 'auto' }}>
      <DataGrid
        rows={data?.data ?? []}
        columns={columns}
        loading={isLoading}
        paginationModel={paginationModel}
        onPaginationModelChange={setPaginationModel}
        pageSizeOptions={[10, 25, 50, 100]}
        disableRowSelectionOnClick
        autoHeight
        sx={{ minWidth: 800 }}
      />
    </Box>
  );
}
