// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.127
// InputHash: 2280e6dff5bcac137d5e4ca79079af522793ed3c7f1301a7955910011cd5b7e5
// CompilerHash: 294b50c17c5868adf98ff6e7e34d9b0ddcf67156d863f2f508ad57df44889164
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// Comment represents the domain entity.
// Source: cue/domain/entities.cue:132
type Comment struct {
	// Source: cue/domain/entities.cue:137
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:141
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:146
	AuthorID string `json:"authorId"`
	// Source: cue/domain/entities.cue:151
	ParentID string `json:"parentId"`
	// Source: cue/domain/entities.cue:157
	Content string `json:"content"`
	// Source: cue/domain/entities.cue:162
	CreatedAt time.Time `json:"createdAt"`
	// Source: cue/domain/entities.cue:166
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e *Comment) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Comment) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("postId", e.PostID),
		slog.Any("authorId", e.AuthorID),
		slog.Any("parentId", e.ParentID),
		slog.Any("content", e.Content),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewComment creates a new instance of Comment with default values.
func NewComment() *Comment {
	return &Comment{}
}
