// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.126
// InputHash: 9f7bb382d697e7e0e28af6fd8d931d158be9dc0bf58b540af092428075ff0b9c
// CompilerHash: 29a8f520277aa6f4d2ff45be2952a732164a1e0860bf797c7d714de4f1da85f9
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// PostTag represents the domain entity.
// Source: cue/domain/entities.cue:206
type PostTag struct {
	// Source: cue/domain/entities.cue:211
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:215
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:219
	TagID string `json:"tagId"`
}

func (e *PostTag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *PostTag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("postId", e.PostID),
		slog.Any("tagId", e.TagID),
	)
}

// NewPostTag creates a new instance of PostTag with default values.
func NewPostTag() *PostTag {
	return &PostTag{}
}
