// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.112
// InputHash: 1a34db2e564023eca319aeaeba1a627726234220f411107ef4871fa5ecfde212
// CompilerHash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// PostTag represents the domain entity.
// Source: cue/domain/entities.cue:202
type PostTag struct {
	// Source: cue/domain/entities.cue:207
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:211
	TagID string `json:"tagId"`
}

func (e *PostTag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *PostTag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("postId", e.PostID),
		slog.Any("tagId", e.TagID),
	)
}

// NewPostTag creates a new instance of PostTag with default values.
func NewPostTag() *PostTag {
	return &PostTag{}
}
