// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.112
// InputHash: 1a34db2e564023eca319aeaeba1a627726234220f411107ef4871fa5ecfde212
// CompilerHash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// Tag represents the domain entity.
// Source: cue/domain/entities.cue:174
type Tag struct {
	// Source: cue/domain/entities.cue:179
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:183
	Name string `json:"name"`
	// Source: cue/domain/entities.cue:188
	Slug string `json:"slug"`
	// Source: cue/domain/entities.cue:193
	Description string `json:"description"`
}

func (e *Tag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Tag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("name", e.Name),
		slog.Any("slug", e.Slug),
		slog.Any("description", e.Description),
	)
}

// NewTag creates a new instance of Tag with default values.
func NewTag() *Tag {
	return &Tag{}
}
