// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.112
// InputHash: 1a34db2e564023eca319aeaeba1a627726234220f411107ef4871fa5ecfde212
// CompilerHash: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// User represents the domain entity.
// Source: cue/domain/entities.cue:12
type User struct {
	// Source: cue/domain/entities.cue:17
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:21
	Email string `json:"email"`
	// Source: cue/domain/entities.cue:26
	PasswordHash string `json:"passwordHash"`
	// Source: cue/domain/entities.cue:30
	Name string `json:"name"`
	// Source: cue/domain/entities.cue:35
	Role string `json:"role"`
	// Source: cue/domain/entities.cue:40
	AvatarURL string `json:"avatarUrl"`
	// Source: cue/domain/entities.cue:45
	CreatedAt time.Time `json:"createdAt"`
	// Source: cue/domain/entities.cue:49
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e *User) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *User) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("email", e.Email),
		slog.String("passwordHash", "***"),
		slog.Any("name", e.Name),
		slog.Any("role", e.Role),
		slog.Any("avatarUrl", e.AvatarURL),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewUser creates a new instance of User with default values.
func NewUser() *User {
	return &User{}
}
