// Generated by ANG. Do not edit.
import { create } from 'zustand';
import type * as Types from '../types';
import { registerStoreInvalidator } from './invalidation';
type GetPostResponseTagsItemId = Types.GetPostResponseTagsItem['id'];

const getPostResponseTagsItemIdKey = (item: Types.GetPostResponseTagsItem): string =>
  String(item.id);

export interface GetPostResponseTagsItemStore {
  items: Record<string, Types.GetPostResponseTagsItem>;
  list: Types.GetPostResponseTagsItem[];
  listStale: boolean;
  detailStale: Record<string, boolean>;
  listVersion: number;
  setAll: (items: Types.GetPostResponseTagsItem[]) => void;
  upsert: (item: Types.GetPostResponseTagsItem) => void;
  remove: (id: GetPostResponseTagsItemId) => void;
  markListStale: () => void;
  markDetailStale: (id: GetPostResponseTagsItemId) => void;
  clearListStale: () => void;
  clearDetailStale: (id: GetPostResponseTagsItemId) => void;
  clear: () => void;
}

export const useGetPostResponseTagsItemStore = create<GetPostResponseTagsItemStore>()((set) => ({
  items: {},
  list: [],
  listStale: false,
  detailStale: {},
  listVersion: 0,
  setAll: (items) => {
    const index: Record<string, Types.GetPostResponseTagsItem> = {};
    for (const item of items) {
      index[getPostResponseTagsItemIdKey(item)] = item;
    }
    set((state) => ({ items: index, list: items, listStale: false, detailStale: {}, listVersion: state.listVersion + 1 }));
  },
  upsert: (item) =>
    set((state) => {
      const key = getPostResponseTagsItemIdKey(item);
      const items = { ...state.items, [key]: item };
      const exists = state.list.some((entry) => getPostResponseTagsItemIdKey(entry) === key);
      const list = exists
        ? state.list.map((entry) => (getPostResponseTagsItemIdKey(entry) === key ? item : entry))
        : [item, ...state.list];
      const detailStale = { ...state.detailStale, [key]: false };
      return { items, list, listStale: false, detailStale, listVersion: state.listVersion + 1 };
    }),
  remove: (id) =>
    set((state) => {
      const key = String(id);
      if (!state.items[key]) {
        return state;
      }
      const items = { ...state.items };
      delete items[key];
      const list = state.list.filter((entry) => getPostResponseTagsItemIdKey(entry) !== key);
      const detailStale = { ...state.detailStale };
      delete detailStale[key];
      return { items, list, listStale: false, detailStale, listVersion: state.listVersion + 1 };
    }),
  markListStale: () =>
    set((state) => {
      if (state.listStale) return state;
      return { listStale: true, listVersion: state.listVersion + 1 };
    }),
  markDetailStale: (id) =>
    set((state) => {
      const key = String(id);
      if (state.detailStale[key]) return state;
      return { detailStale: { ...state.detailStale, [key]: true }, listVersion: state.listVersion + 1 };
    }),
  clearListStale: () => set({ listStale: false }),
  clearDetailStale: (id) =>
    set((state) => {
      const key = String(id);
      if (!state.detailStale[key]) return state;
      const next = { ...state.detailStale };
      delete next[key];
      return { detailStale: next };
    }),
  clear: () => set((state) => ({ items: {}, list: [], listStale: false, detailStale: {}, listVersion: state.listVersion + 1 })),
}));

registerStoreInvalidator('getpostresponsetagsitem', (target, params) => {
  const state = useGetPostResponseTagsItemStore.getState();
  if (target?.mode === 'detail' && target.scopeParam && params && typeof params === 'object') {
    const obj = params as Record<string, unknown>;
    const raw = obj[target.scopeParam];
    if (raw !== undefined && raw !== null && raw !== '') {
      state.markDetailStale(raw as GetPostResponseTagsItemId);
      return;
    }
  }
  state.markListStale();
});
