// Generated by ANG. Do not edit.
import { create } from 'zustand';
import type * as Types from '../types';
type GetPostResponseTagsItemId = Types.GetPostResponseTagsItem['id'];

const getPostResponseTagsItemIdKey = (item: Types.GetPostResponseTagsItem): string =>
  String(item.id);

export interface GetPostResponseTagsItemStore {
  items: Record<string, Types.GetPostResponseTagsItem>;
  list: Types.GetPostResponseTagsItem[];
  setAll: (items: Types.GetPostResponseTagsItem[]) => void;
  upsert: (item: Types.GetPostResponseTagsItem) => void;
  remove: (id: GetPostResponseTagsItemId) => void;
  clear: () => void;
}

export const useGetPostResponseTagsItemStore = create<GetPostResponseTagsItemStore>()((set) => ({
  items: {},
  list: [],
  setAll: (items) => {
    const index: Record<string, Types.GetPostResponseTagsItem> = {};
    for (const item of items) {
      index[getPostResponseTagsItemIdKey(item)] = item;
    }
    set({ items: index, list: items });
  },
  upsert: (item) =>
    set((state) => {
      const key = getPostResponseTagsItemIdKey(item);
      const items = { ...state.items, [key]: item };
      const exists = state.list.some((entry) => getPostResponseTagsItemIdKey(entry) === key);
      const list = exists
        ? state.list.map((entry) => (getPostResponseTagsItemIdKey(entry) === key ? item : entry))
        : [item, ...state.list];
      return { items, list };
    }),
  remove: (id) =>
    set((state) => {
      const key = String(id);
      if (!state.items[key]) {
        return state;
      }
      const items = { ...state.items };
      delete items[key];
      const list = state.list.filter((entry) => getPostResponseTagsItemIdKey(entry) !== key);
      return { items, list };
    }),
  clear: () => set({ items: {}, list: [] }),
}));
