// Generated by ANG. Do not edit.

type InvalidateFn = () => void;

const storeInvalidators = new Map<string, InvalidateFn>();

export const registerStoreInvalidator = (storeKey: string, fn: InvalidateFn) => {
  if (!storeKey || typeof fn !== 'function') return;
  storeInvalidators.set(storeKey, fn);
};

export const markStoreListStale = (storeKey: string) => {
  const fn = storeInvalidators.get(storeKey);
  if (fn) fn();
};

export const markStoresListStale = (storeKeys: string[]) => {
  const seen = new Set<string>();
  for (const key of storeKeys || []) {
    if (!key || seen.has(key)) continue;
    seen.add(key);
    markStoreListStale(key);
  }
};

