// Generated by ANG. Do not edit.
import { create } from 'zustand';
import type * as Types from '../types';
type TagId = Types.Tag['id'];

const tagIdKey = (item: Types.Tag): string =>
  String(item.id);

export interface TagStore {
  items: Record<string, Types.Tag>;
  list: Types.Tag[];
  setAll: (items: Types.Tag[]) => void;
  upsert: (item: Types.Tag) => void;
  remove: (id: TagId) => void;
  clear: () => void;
}

export const useTagStore = create<TagStore>()((set) => ({
  items: {},
  list: [],
  setAll: (items) => {
    const index: Record<string, Types.Tag> = {};
    for (const item of items) {
      index[tagIdKey(item)] = item;
    }
    set({ items: index, list: items });
  },
  upsert: (item) =>
    set((state) => {
      const key = tagIdKey(item);
      const items = { ...state.items, [key]: item };
      const exists = state.list.some((entry) => tagIdKey(entry) === key);
      const list = exists
        ? state.list.map((entry) => (tagIdKey(entry) === key ? item : entry))
        : [item, ...state.list];
      return { items, list };
    }),
  remove: (id) =>
    set((state) => {
      const key = String(id);
      if (!state.items[key]) {
        return state;
      }
      const items = { ...state.items };
      delete items[key];
      const list = state.list.filter((entry) => tagIdKey(entry) !== key);
      return { items, list };
    }),
  clear: () => set({ items: {}, list: [] }),
}));
