// Generated by ANG. Do not edit.
import { create } from 'zustand';
import type * as Types from '../types';
type User_email_id_ProjId = Types.User_email_id_Proj['id'];

const user_email_id_ProjIdKey = (item: Types.User_email_id_Proj): string =>
  String(item.id);

export interface User_email_id_ProjStore {
  items: Record<string, Types.User_email_id_Proj>;
  list: Types.User_email_id_Proj[];
  setAll: (items: Types.User_email_id_Proj[]) => void;
  upsert: (item: Types.User_email_id_Proj) => void;
  remove: (id: User_email_id_ProjId) => void;
  clear: () => void;
}

export const useUser_email_id_ProjStore = create<User_email_id_ProjStore>()((set) => ({
  items: {},
  list: [],
  setAll: (items) => {
    const index: Record<string, Types.User_email_id_Proj> = {};
    for (const item of items) {
      index[user_email_id_ProjIdKey(item)] = item;
    }
    set({ items: index, list: items });
  },
  upsert: (item) =>
    set((state) => {
      const key = user_email_id_ProjIdKey(item);
      const items = { ...state.items, [key]: item };
      const exists = state.list.some((entry) => user_email_id_ProjIdKey(entry) === key);
      const list = exists
        ? state.list.map((entry) => (user_email_id_ProjIdKey(entry) === key ? item : entry))
        : [item, ...state.list];
      return { items, list };
    }),
  remove: (id) =>
    set((state) => {
      const key = String(id);
      if (!state.items[key]) {
        return state;
      }
      const items = { ...state.items };
      delete items[key];
      const list = state.list.filter((entry) => user_email_id_ProjIdKey(entry) !== key);
      return { items, list };
    }),
  clear: () => set({ items: {}, list: [] }),
}));
