// Generated by ANG. Do not edit.
import { create } from 'zustand';
import type * as Types from '../types';
import { registerStoreInvalidator } from './invalidation';
type UserId = Types.User['id'];

const userIdKey = (item: Types.User): string =>
  String(item.id);

export interface UserStore {
  items: Record<string, Types.User>;
  list: Types.User[];
  listStale: boolean;
  listVersion: number;
  setAll: (items: Types.User[]) => void;
  upsert: (item: Types.User) => void;
  remove: (id: UserId) => void;
  markListStale: () => void;
  clearListStale: () => void;
  clear: () => void;
}

export const useUserStore = create<UserStore>()((set) => ({
  items: {},
  list: [],
  listStale: false,
  listVersion: 0,
  setAll: (items) => {
    const index: Record<string, Types.User> = {};
    for (const item of items) {
      index[userIdKey(item)] = item;
    }
    set((state) => ({ items: index, list: items, listStale: false, listVersion: state.listVersion + 1 }));
  },
  upsert: (item) =>
    set((state) => {
      const key = userIdKey(item);
      const items = { ...state.items, [key]: item };
      const exists = state.list.some((entry) => userIdKey(entry) === key);
      const list = exists
        ? state.list.map((entry) => (userIdKey(entry) === key ? item : entry))
        : [item, ...state.list];
      return { items, list, listStale: false, listVersion: state.listVersion + 1 };
    }),
  remove: (id) =>
    set((state) => {
      const key = String(id);
      if (!state.items[key]) {
        return state;
      }
      const items = { ...state.items };
      delete items[key];
      const list = state.list.filter((entry) => userIdKey(entry) !== key);
      return { items, list, listStale: false, listVersion: state.listVersion + 1 };
    }),
  markListStale: () =>
    set((state) => {
      if (state.listStale) return state;
      return { listStale: true, listVersion: state.listVersion + 1 };
    }),
  clearListStale: () => set({ listStale: false }),
  clear: () => set((state) => ({ items: {}, list: [], listStale: false, listVersion: state.listVersion + 1 })),
}));

registerStoreInvalidator('user', () => {
  useUserStore.getState().markListStale();
});
