// Code generated by ANG v0.1.127 from:
//   cue/api/example.cue (sha: 46bb6a80)
// DO NOT EDIT.

package service

import (
	"github.com/example/minimal/internal/port"
)

type NotificationsImpl struct {
	dispatcher port.NotificationDispatcher
}

func NewNotificationsImpl(dispatcher port.NotificationDispatcher) *NotificationsImpl {
	return &NotificationsImpl{dispatcher: dispatcher}
}
