package explain

var explainDB = map[string]knowledge{
	// ── Semantic lint codes (Layer 2) ──────────────────────────────────────────
	"E_FLOW_TOO_LARGE": {
		Title:       "Flow exceeds step limit",
		Description: "Flow has more than 20 steps, making it hard to maintain, test, and reason about.",
		Fix:         "Split the flow into smaller sub-operations. Extract cohesive groups of steps into separate CUE operations and call them via {action: \"flow.Call\", op: \"<service>.<MethodName>\"}. Alternatively, extract repeated patterns into a shared preset in cue/schema/flow_helpers.cue.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Split into sub-operations using 'flow.Call', or extract repeated patterns into a shared preset in cue/schema/flow_helpers.cue.",
		DocAnchor:   "docs/flow-semantics.md#flow-size",
		Expected:    []string{"flow with ≤20 steps"},
	},
	"W_FLOW_HTTP_NO_TIMEOUT": {
		Title:       "HTTP action missing timeout",
		Description: "An http.* step has no timeout — external HTTP calls can hang indefinitely, blocking the handler goroutine.",
		Fix:         "Add timeout: \"5s\" (or an appropriate value) to the step args. Example: {action: \"http.Request\", url: \"...\", timeout: \"5s\"}",
		ActionRef:   "http.Request",
		SchemaRef:   "R_FLOW_ACTION_KNOWN",
		Hint:        "Add timeout to the http step. Recommended: 3–30 s depending on SLA.",
		DocAnchor:   "docs/flow-semantics.md#http",
		Expected:    []string{"timeout field present in http.* step args"},
	},
	"W_FLOW_OUTBOX_PREFERRED": {
		Title:       "Event publish without transactional outbox",
		Description: "The flow writes to DB (repo.Save/Upsert/Update) and publishes an event (event.Publish/Broadcast) without using the outbox pattern. If the process crashes after the DB commit but before the publish, the event is silently lost.",
		Fix:         "Replace event.Publish with event.Outbox inside a tx.Block. Pattern:\n  {action: \"tx.Block\", do: [\n    {action: \"repo.Save\", ...},\n    {action: \"event.Outbox\", event: \"<EventName>\", payload: \"...\"},\n  ]}\nThe outbox ensures the event is stored atomically and delivered at-least-once.",
		ActionRef:   "event.Outbox",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Use event.Outbox inside tx.Block instead of event.Publish.",
		DocAnchor:   "docs/flow-semantics.md#transactional-outbox",
		Expected:    []string{"event.Outbox inside tx.Block when combining DB write and event publish"},
	},
	"E_FLOW_INVALID_NESTING_KEYS": {
		Title:       "Invalid nested block for action",
		Description: "A flow step uses structural nested keys (_then/_do/_catch/...) that are not supported by this action.",
		Fix:         "Remove unsupported nested keys from the step. Use only nested keys listed in diagnostics.allowed for this action.",
		SchemaRef:   "R_FLOW_ACTION_KNOWN",
		Hint:        "Keep only allowed structural keys for the action (see diagnostics.allowed).",
		DocAnchor:   "docs/flow-semantics.md#control-flow-actions",
		Expected:    []string{"only action-supported nested keys are used"},
	},
	"E_DB_WRITE_WITHOUT_TX_WHEN_REQUIRED": {
		Title:       "DB mutation requires tx.Block",
		Description: "The flow has multiple DB writes (or lock + write) outside transaction boundary, risking partial commit and data races.",
		Fix:         "Wrap related DB writes/locks into a single tx.Block with do: [...].",
		ActionRef:   "tx.Block",
		Hint:        "Use {action: \"tx.Block\", do: [...]} for write bundles and row locks.",
		DocAnchor:   "docs/flow-semantics.md#authoring-rules-recommended",
		Expected:    []string{"multi-write and lock+write sequences are inside tx.Block"},
	},
	"E_MUTATING_ENDPOINT_WITHOUT_IDEMPOTENCY": {
		Title:       "Mutating endpoint lacks idempotency",
		Description: "A mutating HTTP operation writes to DB without idempotency/dedup protection, so retries can duplicate side effects.",
		Fix:         "Add idempotency.DeriveKey + idempotency.Check + idempotency.SaveResult (or dedupe.Once) before DB write steps.",
		ActionRef:   "idempotency.DeriveKey",
		Hint:        "Use idempotency guard for POST/PUT/PATCH/DELETE handlers with DB writes.",
		DocAnchor:   "docs/flow-semantics.md#authoring-rules-recommended",
		Expected:    []string{"idempotency guard around mutating operation"},
	},
	"E_PROTECTED_OPERATION_WITHOUT_AUTHZ": {
		Title:       "Missing auth/authz guard",
		Description: "Mutating external operation has no endpoint auth policy and no authz guard in flow.",
		Fix:         "Add endpoint auth (jwt/roles/permission) or explicit guard step at flow start: auth.RequireRole / rbac.CheckPermission.",
		ActionRef:   "auth.RequireRole",
		Hint:        "Canonical order: auth -> validate -> rate/idem -> business.",
		DocAnchor:   "docs/flow-semantics.md#authoring-rules-recommended",
		Expected:    []string{"auth or permission gate is present for protected mutating operation"},
	},
	"W_PACK_AUTH_MISSING_SELF_PROFILE_ROUTE": {
		Title:       "Auth pack is missing self-profile route",
		Description: "An operation uses the canonical auth pack, but the project has no stable self-profile endpoint such as GET /auth/profile or GET /me.",
		Fix:         "Add a self-profile endpoint and map it to GetProfile/GetMyProfile. Recommended route: GET /auth/profile. Keep UpdateProfile on PUT /auth/profile.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Canonical auth pack expects a stable self-profile route.",
		DocAnchor:   "docs/ai-playbook.md#canonical-packs",
		Expected:    []string{"GET /auth/profile or GET /me for auth/profile pack"},
	},
	"E_PACK_MODERATION_MISSING_TRANSITIONS": {
		Title:       "Moderation pack is missing canonical transitions",
		Description: "A moderation entity exists, but it does not define the canonical pending/approved/rejected FSM transitions required by the moderation pack.",
		Fix:         "Add fsm.states: [\"pending\", \"approved\", \"rejected\"] and transitions: { pending: [\"approved\", \"rejected\"] }. Then ensure Approve*/Reject* operations target those states.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Moderation entities should define pending -> approved|rejected.",
		DocAnchor:   "docs/ai-playbook.md#canonical-packs",
		Expected:    []string{"fsm.states includes pending/approved/rejected", "fsm.transitions pending -> approved|rejected"},
	},
	"E_PACK_NOTIFY_MISSING_RECIPIENT_SOURCE": {
		Title:       "Notify pack is missing recipient source",
		Description: "The operation defines notify side effects, but ANG cannot infer who receives the message.",
		Fix:         "Add an explicit recipient source such as req.Email, req.RecipientEmail, requester.Email, or a notify.Email/notify.Send step with to: \"...\".",
		ActionRef:   "notify.Email",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Canonical notify pack must know recipient source explicitly.",
		DocAnchor:   "docs/ai-playbook.md#canonical-packs",
		Expected:    []string{"recipient source such as req.Email or notify.Email.to"},
	},
	"W_PACK_MISSING_PLANNER_HINTS": {
		Title:       "Canonical pack operation is missing planner hints",
		Description: "The operation looks like auth/profile/messaging/commerce pack intent, but it does not carry explicit planner.route / planner.repository metadata. This keeps ANG dependent on fallback heuristics.",
		Fix:         "Add planner.source_pack and explicit planner.route / planner.repository bindings. Example: planner: { source_pack: \"auth_profile\", route: { method: \"GET\", path: \"/auth/profile\" }, repository: { load_method: \"FindByUserID\", actor_field: \"userID\" } }.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Treat planner metadata as the source of truth for canonical packs.",
		DocAnchor:   "docs/ai-playbook.md#canonical-packs",
		Expected:    []string{"planner.source_pack is set", "planner.route and/or planner.repository is set"},
	},
	"W_PACK_MISSING_PLANNER_ROUTE_PATH": {
		Title:       "Planner route path is missing",
		Description: "The operation carries planner hints, but planner.route.path is empty. ANG can still compile, but routing semantics remain partially implicit.",
		Fix:         "Add planner.route.path explicitly. Example: planner: { route: { method: \"GET\", path: \"/auth/profile\" } }.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Treat planner.route.path as explicit source of truth for canonical routing.",
		DocAnchor:   "docs/ai-playbook.md#canonical-packs",
		Expected:    []string{"planner.route.path is set"},
	},
	"W_IR_CANONICAL_PACK_MISMATCH": {
		Title:       "Canonical IR metadata is inconsistent",
		Description: "primary_operation_kind, capabilities, side_effects, endpoint path, or pack semantics disagree with each other. This weakens deterministic lowering and validation.",
		Fix:         "Align canonical IR metadata: keep primary_operation_kind, capabilities, side_effects, and endpoint path consistent with the chosen pack. Example: auth -> capabilities:[\"auth\"], profile self-route -> /auth/profile, moderation side effects -> capabilities:[\"moderation\"].",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Treat canonical pack metadata as source of truth; remove contradictions.",
		DocAnchor:   "docs/ai-playbook.md#canonical-packs",
		Expected:    []string{"consistent primary_operation_kind/capabilities/side_effects/path metadata"},
	},
	"E_MIGRATION_FACTS_REQUIRED": {
		Title:       "Migration mode requires facts file",
		Description: "Facts-driven migration lint was enabled, but no `ang/facts/v1` JSON was provided.",
		Fix:         "Run `ang extract <source-path> --from auto --out migration.facts.json`, then rerun `ang ops vet --migration-mode --facts migration.facts.json`.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Provide `--facts <path>` when using `--migration-mode`.",
		DocAnchor:   "docs/ai-playbook.md#mcp-first",
		Expected:    []string{"--facts points to a valid ang/facts/v1 JSON"},
	},
	"E_MIGRATION_FACTS_LOAD_FAILED": {
		Title:       "Facts file cannot be loaded",
		Description: "The file passed to `--facts` is missing, invalid JSON, or has an unsupported schema.",
		Fix:         "Regenerate facts with `ang extract ... --out migration.facts.json` and verify `schema` is `ang/facts/v1`.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Use a valid JSON file generated by `ang extract`.",
		DocAnchor:   "docs/commands.md#ang-extract",
		Expected:    []string{"readable JSON with schema `ang/facts/v1`"},
	},
	"E_MIGRATION_GAP_WITHOUT_OPEN_QUESTION": {
		Title:       "Fact gap without unresolved marker",
		Description: "Flow references data not present in extracted facts, but does not mark uncertainty (`unknown.*`/`openQuestion`). This indicates likely hallucinated business logic.",
		Fix:         "Replace uncertain expressions with explicit placeholders (`unknown.<name>` or `openQuestion: \"...\"`) and keep operation in draft until facts are completed.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Never invent missing inputs; mark gaps explicitly.",
		DocAnchor:   "docs/ai-playbook.md#prompting-pattern-for-agents",
		Expected:    []string{"all unresolved business facts are marked as unknown/openQuestion"},
	},
	"W_MIGRATION_GAP_MARKED": {
		Title:       "Fact gap is explicitly marked",
		Description: "Flow has unresolved data gaps, but they are properly marked with `unknown.*` or `openQuestion`.",
		Fix:         "Complete source facts and replace placeholders with validated fields from `ang/facts/v1`.",
		SchemaRef:   "R_PREFER_FLOW",
		Hint:        "Keep markers until source facts are confirmed.",
		DocAnchor:   "docs/ai-playbook.md#prompting-pattern-for-agents",
		Expected:    []string{"placeholder markers are eventually replaced by confirmed facts"},
	},

	// ── Compiler / flow codes ──────────────────────────────────────────────────
	"MISSING_ID": {
		Title:       "Missing ID assignment before repo.Save",
		Description: "New entity must have deterministic ID before save.",
		Fix:         "Add {action: \"mapping.Assign\", to: \"<entity>.ID\", value: \"uuid.NewString()\"} before the repo.Save step.",
		ActionRef:   "mapping.Assign",
		Hint:        `Add mapping.Assign: {to: "newEntity.ID", value: "uuid.NewString()"}`,
		DocAnchor:   "docs/flow-semantics.md#authoring-rules-recommended",
		Expected:    []string{"mapping.Assign for <entity>.ID before repo.Save"},
	},
	"MISSING_CREATED_AT": {
		Title:       "Missing CreatedAt assignment before repo.Save",
		Description: "CreatedAt should be explicit and normalized for sorting and audit.",
		Fix:         "Add {action: \"mapping.Assign\", to: \"<entity>.CreatedAt\", value: \"time.Now().UTC().Format(time.RFC3339)\"} before the repo.Save step.",
		ActionRef:   "mapping.Assign",
		Hint:        `Set CreatedAt using RFC3339 UTC before save`,
		DocAnchor:   "docs/flow-semantics.md#authoring-rules-recommended",
		Expected:    []string{"mapping.Assign for <entity>.CreatedAt"},
	},
	"MISSING_OUTPUT": {
		Title:       "Missing output variable",
		Description: "Step must declare output variable to store produced value.",
		Fix:         "Add output: \"<varName>\" to the step args. The variable can then be referenced in subsequent steps.",
		Hint:        "Add output field in step args.",
		DocAnchor:   "docs/flow-semantics.md#validation-model",
		Expected:    []string{"output field is present"},
	},
	"MISSING_INPUT": {
		Title:       "Missing input argument",
		Description: "Repository/mapping step requires input expression.",
		Fix:         "Add input: \"<varName>\" to the step args referencing the variable holding the entity/value.",
		ActionRef:   "repo.Save",
		Hint:        "Provide `input` field in step args.",
		DocAnchor:   "docs/flow-semantics.md#validation-model",
		Expected:    []string{"input field is present"},
	},
	"MISSING_SOURCE": {
		Title:       "Missing source argument",
		Description: "Repository step requires source entity/repository.",
		Fix:         "Add source: \"<EntityName>\" to the step args (e.g. source: \"User\").",
		ActionRef:   "repo.Save",
		Hint:        "Provide `source` field with entity name.",
		DocAnchor:   "docs/flow-semantics.md#validation-model",
		Expected:    []string{"source field is present"},
	},
	"MISSING_ENTITY": {
		Title:       "Missing entity in mapping.Map",
		Description: "mapping.Map requires entity for typed object creation.",
		Fix:         "Add entity: \"<EntityName>\" to the mapping.Map step args (e.g. entity: \"User\").",
		ActionRef:   "mapping.Map",
		Hint:        "Set `entity` in mapping.Map step.",
		DocAnchor:   "docs/flow-semantics.md#validation-model",
		Expected:    []string{"entity field is present"},
	},
	"UNKNOWN_ACTION": {
		Title:       "Unknown flow action",
		Description: "Action is not part of registered stdlib.",
		Fix:         "Run 'ang actions --json' to see all registered actions and replace the typo/unknown name with the correct canonical action.",
		SchemaRef:   "R_FLOW_ACTION_KNOWN",
		Hint:        "Use `ang actions --json` to pick canonical action.",
		DocAnchor:   "docs/flow-semantics.md#action-catalog",
		Expected:    []string{"known flow action"},
	},
	"E_FLOW_UNKNOWN_ACTION": {
		Title:       "Unknown flow action",
		Description: "Action is not part of registered stdlib.",
		Fix:         "Run 'ang actions --json' to see all registered actions and replace the typo/unknown name with the correct canonical action. The diagnostic's 'allowed' field lists same-namespace suggestions.",
		SchemaRef:   "R_FLOW_ACTION_KNOWN",
		Hint:        "Use `ang actions --json` to pick canonical action. Check 'allowed' field for suggestions.",
		DocAnchor:   "docs/flow-semantics.md#action-catalog",
		Expected:    []string{"known flow action"},
	},
	"TX_REQUIRED": {
		Title:       "Action requires transaction",
		Description: "This action can only execute inside `tx.Block`.",
		Fix:         "Wrap the step inside tx.Block: {action: \"tx.Block\", do: [{action: \"<this-action>\", ...}]}",
		ActionRef:   "tx.Block",
		Hint:        "Wrap step in `tx.Block { do: [...] }`.",
		DocAnchor:   "docs/flow-semantics.md#validation-model",
		Expected:    []string{"step located inside tx.Block"},
	},
	"MISSING_CONTENT": {
		Title:       "notify.Send needs template or text",
		Description: "notify.Send step requires either a template reference or inline text content.",
		Fix:         "Add text: \"Your message here\" or template: \"<template-name>\" to the notify.Send step args.",
		ActionRef:   "notify.Send",
		Hint:        `Add text: "..." or template: "..." to the notify.Send step args.`,
		DocAnchor:   "docs/flow-semantics.md#notify",
		Expected:    []string{"text or template field present in notify.Send args"},
	},
	"MISSING_APPROVERS": {
		Title:       "Approval requires non-empty approvers",
		Description: "approval.Request step must specify at least one approver.",
		Fix:         "Add approvers: [\"user@example.com\"] to the approval.Request step args.",
		ActionRef:   "approval.Request",
		Hint:        `Add approvers: ["user@example.com"] to the approval step.`,
		DocAnchor:   "docs/flow-semantics.md#approval",
		Expected:    []string{"non-empty approvers list"},
	},
	"INVALID_APPROVERS_TYPE": {
		Title:       "Approvers must be string or list",
		Description: "The approvers field accepts a single string or a list of strings.",
		Fix:         "Change approvers to a string or a list of strings: approvers: \"user@example.com\" or approvers: [\"a@b.com\"].",
		ActionRef:   "approval.Request",
		Hint:        "Use approvers: \"user@example.com\" or approvers: [\"a@b.com\", \"c@d.com\"].",
		DocAnchor:   "docs/flow-semantics.md#approval",
		Expected:    []string{"string or []string for approvers"},
	},
	"INVALID_POLICY": {
		Title:       "Approval policy must be any/all/quorum",
		Description: "The policy field on approval steps must be one of: any, all, quorum.",
		Fix:         "Set policy to one of the allowed values: policy: \"any\", policy: \"all\", or policy: \"quorum\".",
		ActionRef:   "approval.Request",
		SchemaRef:   "R_OP_MODE_XOR",
		Hint:        `Set policy: "any" or policy: "all" or policy: "quorum".`,
		DocAnchor:   "docs/flow-semantics.md#approval",
		Expected:    []string{"policy is one of: any, all, quorum"},
	},
	"MISSING_BLOCK": {
		Title:       "Required child block missing",
		Description: "A compound step is missing a required child block (e.g. _do, _then, _else).",
		Fix:         "Add the missing child block. Run 'ang actions --json' to see the contract for this compound step.",
		Hint:        "Add the missing block. Check `ang actions --json` for step contract.",
		DocAnchor:   "docs/flow-semantics.md#compound-steps",
		Expected:    []string{"required child block present (_do, _then, etc.)"},
	},
	"MISSING_FIELD": {
		Title:       "Required step argument missing",
		Description: "A flow step is missing a required argument from its action contract.",
		Fix:         "Run 'ang actions --json | jq \".[] | select(.name==\\\"<action>\\\")\"' to find required fields and add the missing one to the step.",
		Hint:        "Check the step contract via `ang actions --json` and add the missing field.",
		DocAnchor:   "docs/flow-semantics.md#validation-model",
		Expected:    []string{"all required action arguments present"},
	},
}
