// Generated by ANG. Do not edit.
import { QueryClient } from '@tanstack/react-query';
import * as Queries from './queries';

export interface RouteMeta {
  title: string;
  breadcrumb: string;
}

export const createRouteDefinitions = (queryClient: QueryClient) => [
  {
    path: '/users',
    method: 'GET',
    rpc: 'ListUsers',
    loader: async ({ params }: { params: any }) => {
      await queryClient.ensureQueryData(Queries.listUsersQueryOptions());
    },
    meta: {
      title: 'ListUsers',
      breadcrumb: 'ListUsers'
    } as RouteMeta
  },
];

export const Routes = {
  ListUsers: () => `/users`,
};
