// Code generated by ANG v0.2.2 from:
//   cue/api/assistant.cue (sha: d3baa21c)
// DO NOT EDIT.

package service

import (
	"sync"

	"github.com/strogmv/ang/internal/port"
)

var _AssistantFlowMutexRegistry sync.Map

func _AssistantFlowMutexForKey(key string) *sync.Mutex {
	if key == "" {
		key = "__default__"
	}
	if existing, ok := _AssistantFlowMutexRegistry.Load(key); ok {
		if mu, ok := existing.(*sync.Mutex); ok && mu != nil {
			return mu
		}
	}
	mu := &sync.Mutex{}
	actual, _ := _AssistantFlowMutexRegistry.LoadOrStore(key, mu)
	if existing, ok := actual.(*sync.Mutex); ok && existing != nil {
		return existing
	}
	return mu
}

type AssistantImpl struct {
	BlogService port.Blog
	stateStore  port.StateStore
}

func NewAssistantImpl(blogService port.Blog, stateStore port.StateStore) *AssistantImpl {
	return &AssistantImpl{BlogService: blogService, stateStore: stateStore}
}
