// Code generated by ANG v0.1.127 from:
//   cue/api/auth.cue (sha: e5be7260)
//   cue/api/report.cue (sha: 1611f28a)
// DO NOT EDIT.

package service

import (
	"github.com/strogmv/ang/internal/port"
)

type AuthImpl struct {
	UserRepo   port.UserRepository
	publisher  port.Publisher
	dispatcher port.NotificationDispatcher
}

func NewAuthImpl(userRepo port.UserRepository, publisher port.Publisher, dispatcher port.NotificationDispatcher) *AuthImpl {
	return &AuthImpl{UserRepo: userRepo, publisher: publisher, dispatcher: dispatcher}
}
