// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.44
// InputHash: 9fad923bd84da41f91e7eb0536e3fd36dd2e90a2a0aa35367843acfaf697931b
// CompilerHash: 9a63cacc45edd67a77f1a002cd4d57844a2dce9914c1d5777eb76af325d670df
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

package service

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/strogmv/ang/internal/port"
)

// Blank identifiers to suppress unused import warnings
var (
	_ = json.Marshal
	_ = fmt.Sprintf
	_ = time.Now
)

// AuthCached decorates Auth with Redis caching.
type AuthCached struct {
	next  port.Auth
	redis *redis.Client
}

func NewAuthCached(next port.Auth, r *redis.Client) *AuthCached {
	return &AuthCached{
		next:  next,
		redis: r,
	}
}
func (s *AuthCached) Register(ctx context.Context, req port.RegisterRequest) (port.RegisterResponse, error) {
	return s.next.Register(ctx, req)
}
func (s *AuthCached) Login(ctx context.Context, req port.LoginRequest) (port.LoginResponse, error) {
	return s.next.Login(ctx, req)
}
func (s *AuthCached) GetProfile(ctx context.Context, req port.GetProfileRequest) (port.GetProfileResponse, error) {
	return s.next.GetProfile(ctx, req)
}
func (s *AuthCached) UpdateProfile(ctx context.Context, req port.UpdateProfileRequest) (port.UpdateProfileResponse, error) {
	return s.next.UpdateProfile(ctx, req)
}
