// Code generated by ANG v0.1.127 from:
//   cue/api/auth.cue (sha: 6d6155f5)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"

	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/auth.cue:108
func (s *AuthImpl) GetProfile(ctx context.Context, req port.GetProfileRequest) (resp port.GetProfileResponse, err error) {
	user, err := s.UserRepo.FindByID(ctx, req.UserID)
	if err != nil {
		return resp, err
	}
	if user == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "User not found")
	}
	if err := helpers.Assign(&resp.ID, user.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Email, user.Email); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Name, user.Name); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Role, user.Role); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.AvatarURL, user.AvatarURL); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.CreatedAt, user.CreatedAt); err != nil {
		return resp, err
	}

	return resp, nil
}
