// Code generated by ANG v0.1.116 from:
//   cue/api/auth.cue (sha: 568e1d9d)
// DO NOT EDIT.

package service

import (
	"github.com/strogmv/ang/internal/port"
)

type AuthImpl struct {
	UserRepo  port.UserRepository
	publisher port.Publisher
}

func NewAuthImpl(userRepo port.UserRepository, publisher port.Publisher) *AuthImpl {
	return &AuthImpl{UserRepo: userRepo, publisher: publisher}
}
