// Code generated by ANG v0.1.127 from:
//   cue/api/auth.cue (sha: e5be7260)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"

	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/auth.cue:138
func (s *AuthImpl) UpdateProfile(ctx context.Context, req port.UpdateProfileRequest) (resp port.UpdateProfileResponse, err error) {
	user, err := s.UserRepo.FindByID(ctx, req.UserID)
	if err != nil {
		return resp, err
	}
	if user == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "User not found")
	}
	if req.Name != "" {
		if err := helpers.Assign(&user.Name, req.Name); err != nil {
			return resp, err
		}
	}
	if req.AvatarURL != "" {
		if err := helpers.Assign(&user.AvatarURL, req.AvatarURL); err != nil {
			return resp, err
		}
	}
	if err := s.UserRepo.Save(ctx, user); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Ok, true); err != nil {
		return resp, err
	}

	return resp, nil
}
