// Code generated by ANG v0.2.2 from:
//   cue/api/tags.cue (sha: 50a0741e)
// DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/tags.cue:73
func (s *BlogImpl) UpdateTag(ctx context.Context, req port.UpdateTagRequest) (resp port.UpdateTagResponse, err error) {
	tag, err := s.TagRepo.FindByID(ctx, req.ID)
	if err != nil {
		return resp, err
	}
	if tag == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "Tag not found")
	}
	if req.Name != "" {
		if err := helpers.Assign(&tag.Name, req.Name); err != nil {
			return resp, err
		}
		slugSource := strings.ToLower(strings.TrimSpace(req.Name))
		_re_2, _reErr_2 := regexp.Compile("[^a-z0-9]+")
		if _reErr_2 != nil {
			return resp, fmt.Errorf("regex.Replace: %w", _reErr_2)
		}
		slugTrimmed := _re_2.ReplaceAllString(slugSource, "-")
		_re_3, _reErr_3 := regexp.Compile("(^-+|-+$)")
		if _reErr_3 != nil {
			return resp, fmt.Errorf("regex.Replace: %w", _reErr_3)
		}
		slug := _re_3.ReplaceAllString(slugTrimmed, "")
		if err := helpers.Assign(&tag.Slug, slug); err != nil {
			return resp, err
		}
	}
	if req.Description != "" {
		if err := helpers.Assign(&tag.Description, req.Description); err != nil {
			return resp, err
		}
	}
	if err := s.TagRepo.Save(ctx, tag); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Ok, true); err != nil {
		return resp, err
	}

	return resp, nil
}
