// Code generated by ANG v0.1.116 from:
//   cue/api/tags.cue (sha: e08068db)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"
	"time"

	"github.com/google/uuid"
	"github.com/strogmv/ang/internal/domain"
	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

func (s *BlogImpl) CreateTag(ctx context.Context, req port.CreateTagRequest) (resp port.CreateTagResponse, err error) {
	slug, err := slugify(req.Name)
	if err != nil {
		return resp, err
	}
	existing, err := s.TagRepo.FindBySlug(ctx, slug)
	if err != nil {
		return resp, err
	}
	if !(existing == nil) {
		return resp, errors.New(http.StatusBadRequest, "Validation Error", "Tag already exists")
	}
	var newTag domain.Tag
	if err := helpers.Assign(&newTag.Name, req.Name); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newTag.Slug, slug); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newTag.Description, req.Description); err != nil {
		return resp, err
	}
	_newTagAutoID := uuid.NewString()
	if err := helpers.Assign(&newTag.ID, _newTagAutoID); err != nil {
		return resp, err
	}
	_newTagAutoCreatedAt := time.Now().UTC().Format(time.RFC3339)
	if err := helpers.Assign(&newTag.CreatedAt, _newTagAutoCreatedAt); err != nil {
		return resp, err
	}
	if err := s.TagRepo.Save(ctx, &newTag); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.ID, newTag.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Slug, newTag.Slug); err != nil {
		return resp, err
	}

	return resp, nil
}
