// Code generated by ANG v0.1.126 from:
//   cue/api/posts.cue (sha: d94ac621)
// DO NOT EDIT.

package service

import (
	"context"

	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/posts.cue:151
func (s *BlogImpl) ListMyPosts(ctx context.Context, req port.ListMyPostsRequest) (resp port.ListMyPostsResponse, err error) {
	if req.Status != "" {
		posts, err := s.PostRepo.ListByAuthorAndStatus(ctx, req.UserID, req.Status)
		if err != nil {
			return resp, err
		}
		if err := helpers.Assign(&resp.Data, posts); err != nil {
			return resp, err
		}
	} else {
		posts, err := s.PostRepo.ListByAuthor(ctx, req.UserID)
		if err != nil {
			return resp, err
		}
		if err := helpers.Assign(&resp.Data, posts); err != nil {
			return resp, err
		}
	}

	return resp, nil
}
