// Code generated by ANG v0.1.118 from:
//   cue/api/posts.cue (sha: f06113eb)
// DO NOT EDIT.

package service

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/strogmv/ang/internal/domain"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/posts.cue:12
func (s *BlogImpl) CreatePost(ctx context.Context, req port.CreatePostRequest) (resp port.CreatePostResponse, err error) {
	slug, err := slugify(req.Title)
	if err != nil {
		return resp, err
	}
	existing, err := s.PostRepo.FindBySlug(ctx, slug)
	if err != nil {
		return resp, err
	}
	if existing != nil {
		slug, err = appendRandom(slug)
		if err != nil {
			return resp, err
		}
	}
	var newPost domain.Post
	if err := helpers.Assign(&newPost.Title, req.Title); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.Content, req.Content); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.Slug, slug); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.AuthorID, req.UserID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.Status, "draft"); err != nil {
		return resp, err
	}
	_newPostAutoID := uuid.NewString()
	if err := helpers.Assign(&newPost.ID, _newPostAutoID); err != nil {
		return resp, err
	}
	_newPostAutoCreatedAt := time.Now().UTC().Format(time.RFC3339)
	if err := helpers.Assign(&newPost.CreatedAt, _newPostAutoCreatedAt); err != nil {
		return resp, err
	}
	if err := s.PostRepo.Save(ctx, &newPost); err != nil {
		return resp, err
	}
	if s.publisher != nil {
		_ = s.publisher.PublishPostCreated(ctx, domain.PostCreated{AuthorID: newPost.AuthorID, PostID: newPost.ID, Title: newPost.Title})
	}
	for _, tagName := range req.Tags {
		tag, err := s.TagRepo.FindBySlug(ctx, tagName)
		if err != nil {
			return resp, err
		}
		if tag != nil {
			var assoc domain.PostTag
			if err := helpers.Assign(&assoc.PostID, newPost.ID); err != nil {
				return resp, err
			}
			if err := helpers.Assign(&assoc.TagID, tag.ID); err != nil {
				return resp, err
			}
			if err := s.PostTagRepo.Save(ctx, &assoc); err != nil {
				return resp, err
			}
		}
	}
	if err := helpers.Assign(&resp.ID, newPost.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Slug, newPost.Slug); err != nil {
		return resp, err
	}

	return resp, nil
}
