// Code generated by ANG v0.2.2 from:
//   cue/api/comments.cue (sha: f627efc3)
//   cue/api/posts.cue (sha: ed54d013)
//   cue/api/posts_lifecycle.cue (sha: 1aea0c6f)
//   cue/api/report.cue (sha: 1611f28a)
//   cue/api/tags.cue (sha: 50a0741e)
// DO NOT EDIT.

package service

import (
	"sync"

	"github.com/strogmv/ang/internal/port"
)

var _BlogFlowMutexRegistry sync.Map

func _BlogFlowMutexForKey(key string) *sync.Mutex {
	if key == "" {
		key = "__default__"
	}
	if existing, ok := _BlogFlowMutexRegistry.Load(key); ok {
		if mu, ok := existing.(*sync.Mutex); ok && mu != nil {
			return mu
		}
	}
	mu := &sync.Mutex{}
	actual, _ := _BlogFlowMutexRegistry.LoadOrStore(key, mu)
	if existing, ok := actual.(*sync.Mutex); ok && existing != nil {
		return existing
	}
	return mu
}

type BlogImpl struct {
	CommentRepo port.CommentRepository
	PostRepo    port.PostRepository
	PostTagRepo port.PostTagRepository
	TagRepo     port.TagRepository
	AuthService port.Auth
	txManager   port.TxManager
	publisher   port.Publisher
}

func NewBlogImpl(commentRepo port.CommentRepository, postRepo port.PostRepository, postTagRepo port.PostTagRepository, tagRepo port.TagRepository, authService port.Auth, txManager port.TxManager, publisher port.Publisher) *BlogImpl {
	return &BlogImpl{CommentRepo: commentRepo, PostRepo: postRepo, PostTagRepo: postTagRepo, TagRepo: tagRepo, AuthService: authService, txManager: txManager, publisher: publisher}
}
