// Code generated by ANG v0.2.2 from:
//   cue/api/posts.cue (sha: ed54d013)
// DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	"net/http"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/strogmv/ang/internal/domain"
	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/posts.cue:12
func (s *BlogImpl) CreatePost(ctx context.Context, req port.CreatePostRequest) (resp port.CreatePostResponse, err error) {
	slugSource := strings.ToLower(strings.TrimSpace(req.Title))
	_re_1, _reErr_1 := regexp.Compile("[^a-z0-9]+")
	if _reErr_1 != nil {
		return resp, fmt.Errorf("regex.Replace: %w", _reErr_1)
	}
	slugTrimmed := _re_1.ReplaceAllString(slugSource, "-")
	_re_2, _reErr_2 := regexp.Compile("(^-+|-+$)")
	if _reErr_2 != nil {
		return resp, fmt.Errorf("regex.Replace: %w", _reErr_2)
	}
	slug := _re_2.ReplaceAllString(slugTrimmed, "")
	if !(slug != "") {
		return resp, errors.New(http.StatusBadRequest, "Validation Error", "Post slug cannot be empty")
	}
	existing, err := s.PostRepo.FindBySlug(ctx, slug)
	if err != nil {
		return resp, err
	}
	if !(existing == nil) {
		return resp, errors.New(http.StatusBadRequest, "Validation Error", "Post slug already exists")
	}
	var newPost domain.Post
	if err := helpers.Assign(&newPost.Title, req.Title); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.Content, req.Content); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.Slug, slug); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.AuthorID, req.UserID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newPost.Status, "draft"); err != nil {
		return resp, err
	}
	if err := s.PostRepo.Save(ctx, &newPost); err != nil {
		return resp, err
	}
	if s.publisher == nil {
		return resp, fmt.Errorf("event.Publish: publisher wiring is not configured")
	}
	if err := s.publisher.PublishPostCreated(ctx, domain.PostCreated{AuthorID: newPost.AuthorID, PostID: newPost.ID, Title: newPost.Title}); err != nil {
		return resp, fmt.Errorf("event.Publish PostCreated: %w", err)
	}
	for _, tagName := range req.Tags {
		tag, err := s.TagRepo.FindBySlug(ctx, tagName)
		if err != nil {
			return resp, err
		}
		if tag != nil {
			var assoc domain.PostTag
			if err := helpers.Assign(&assoc.ID, uuid.NewString()); err != nil {
				return resp, err
			}
			if err := helpers.Assign(&assoc.PostID, newPost.ID); err != nil {
				return resp, err
			}
			if err := helpers.Assign(&assoc.TagID, tag.ID); err != nil {
				return resp, err
			}
			if err := s.PostTagRepo.Save(ctx, &assoc); err != nil {
				return resp, err
			}
		}
	}
	if err := helpers.Assign(&resp.ID, newPost.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Slug, newPost.Slug); err != nil {
		return resp, err
	}

	return resp, nil
}
