// Code generated by ANG v0.1.126 from:
//   cue/api/posts.cue (sha: d94ac621)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"

	"github.com/strogmv/ang/internal/domain"
	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/posts.cue:238
func (s *BlogImpl) PublishPost(ctx context.Context, req port.PublishPostRequest) (resp port.PublishPostResponse, err error) {
	post, err := s.PostRepo.FindByID(ctx, req.ID)
	if err != nil {
		return resp, err
	}
	if post == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "Post not found")
	}
	if err := post.TransitionTo("\"published\""); err != nil {
		return resp, err
	}
	if err := s.PostRepo.Save(ctx, post); err != nil {
		return resp, err
	}
	if s.publisher != nil {
		_ = s.publisher.PublishPostPublished(ctx, domain.PostPublished{AuthorID: post.AuthorID, PostID: post.ID, Slug: post.Slug, Title: post.Title})
	}
	if err := helpers.Assign(&resp.Ok, true); err != nil {
		return resp, err
	}

	return resp, nil
}
