// Code generated by ANG v0.1.116 from:
//   cue/api/posts_lifecycle.cue (sha: a36aab55)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"

	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

func (s *BlogImpl) DeletePost(ctx context.Context, req port.DeletePostRequest) (resp port.DeletePostResponse, err error) {
	post, err := s.PostRepo.FindByID(ctx, req.ID)
	if err != nil {
		return resp, err
	}
	if post == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "Post not found")
	}
	if _, err := s.PostTagRepo.DeleteByPost(ctx, post.ID); err != nil {
		return resp, err
	}
	if err := s.PostRepo.Delete(ctx, post.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Ok, true); err != nil {
		return resp, err
	}

	return resp, nil
}
