// Code generated by ANG v0.1.118 from:
//   cue/api/tags.cue (sha: e08068db)
// DO NOT EDIT.

package service

import (
	"context"

	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/tags.cue:12
func (s *BlogImpl) ListTags(ctx context.Context, req port.ListTagsRequest) (resp port.ListTagsResponse, err error) {
	tags, err := s.TagRepo.ListAll(ctx)
	if err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Data, tags); err != nil {
		return resp, err
	}

	return resp, nil
}
