// Code generated by ANG v0.1.127 from:
//   cue/api/notifications.cue (sha: 55c5022b)
// DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	"net/http"

	"github.com/strogmv/ang/internal/pkg/errors"
	"github.com/strogmv/ang/internal/pkg/helpers"
	"github.com/strogmv/ang/internal/port"
)

// Generated from: cue/api/notifications.cue:5
func (s *NotificationsImpl) SendPasswordResetEmail(ctx context.Context, req port.SendPasswordResetEmailRequest) (resp port.SendPasswordResetEmailResponse, err error) {
	{
		_notifyMeta_0 := map[string]any{"to": fmt.Sprint(req.Email)}
		_notifyMsg_0 := port.NotificationMessage{Metadata: _notifyMeta_0, Template: fmt.Sprint("password_reset"), Payload: map[string]any{"Name": req.Name, "ResetURL": req.ResetURL, "AppName": "ANG", "SupportEmail": "support@ang.local"}}
		if s.dispatcher == nil {
			return resp, errors.New(http.StatusInternalServerError, "NOTIFY_DISPATCHER_NOT_CONFIGURED", "notify.Email requires notification dispatcher wiring")
		}
		if _notifyErr_0 := s.dispatcher.Dispatch(ctx, _notifyMsg_0); _notifyErr_0 != nil {
			return resp, fmt.Errorf("notify.Email: %w", _notifyErr_0)
		}
	}
	if err := helpers.Assign(&resp.Ok, true); err != nil {
		return resp, err
	}

	return resp, nil
}
