// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Component: CreateCommentForm
// Type: Create Form (POST)
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

// ============================================================================
// SECTION: Imports
// PURPOSE: React Hook Form for form state, MUI for UI components
// LIBRARIES:
//   - react-hook-form: Form state management and validation
//   - @mui/material: UI components (TextField, Select, etc.)
//   - @mui/x-date-pickers: Date/time picker components
//   - dayjs: Date manipulation library
// ============================================================================
import { Controller } from 'react-hook-form';
import { Box, Button, Stack, TextField, Autocomplete } from '@mui/material';
import { useCreateCommentForm } from '../../forms';
import { useCreateComment } from '../../hooks';
import type { CreateCommentRequest, CreateCommentResponse } from '../../types';

// ============================================================================
// SECTION: Component Props
// PURPOSE: Define form component interface
// PROPS:
//   - onSuccess: Callback after successful mutation
//   - onError: Callback on mutation error
//   - onCancel: Callback for cancel button
// ============================================================================
export interface CreateCommentFormProps {
  onSuccess?: (data: CreateCommentResponse) => void;
  onError?: (error: Error) => void;
  onCancel?: () => void;
}

// ============================================================================
// SECTION: Form Component
// PURPOSE: Render form with controlled inputs and submit handling
// PATTERN: Controller pattern for react-hook-form integration
// MUTATION: useCreateComment hook for API call
// ============================================================================
export function CreateCommentForm({ onSuccess, onError, onCancel }: CreateCommentFormProps) {
  const form = useCreateCommentForm();
  const { mutate, isPending } = useCreateComment({
    onSuccess: (data) => onSuccess?.(data),
    onError: (error) => onError?.(error as Error),
  });

  return (
    <Box
      component="form"
      onSubmit={form.handleSubmit((data) => mutate(data))}
      noValidate
    >
      <Stack spacing={3}>

        <Controller
          name="postId"
          control={form.control}
          render={({ field, fieldState }) => (
            <TextField
              {...field}
              label="Post Id"
              helperText={fieldState.error?.message}
              error={!!fieldState.error}
              fullWidth
            />
          )}
        />

        <Controller
          name="content"
          control={form.control}
          render={({ field, fieldState }) => (
            <TextField
              {...field}
              label="Content"
              multiline
              rows={4}
              helperText={fieldState.error?.message}
              error={!!fieldState.error}
              fullWidth
            />
          )}
        />

        <Stack direction="row" spacing={2} justifyContent="flex-end">
          {onCancel && (
            <Button variant="outlined" onClick={onCancel} disabled={isPending}>
              Отмена
            </Button>
          )}
          <Button type="submit" variant="contained" disabled={isPending}>
            {isPending ? 'Сохранение...' : 'Сохранить'}
          </Button>
        </Stack>
      </Stack>
    </Box>
  );
}
