// AUTO-GENERATED by ANG. DO NOT EDIT.
import type { FormSchema } from '@/components/ui/auto-form';

export type FormSchemaLoader = () => Promise<FormSchema<any>>;

export type GeneratedFormName =
   "CreateComment"
 | "CreatePost"
 | "CreateTag"
 | "Register"
 | "SubmitPost"
 | "UpdateComment"
 | "UpdatePost"
 | "UpdateProfile"
 | "UpdateTag"
;

export type FormManifestEntry = {
  name: GeneratedFormName;
  loadSchema: FormSchemaLoader;
  useFormHook: string;
  useMutationHook: string;
  scope: 'public' | 'admin';
};

export const publicFormsManifest: Record<string, FormManifestEntry> = {
  "CreateComment": {
    name: "CreateComment",
    loadSchema: () => import('./CreateCommentForm.schema').then((m) => m.CreateCommentFormSchema),
    useFormHook: "useCreateCommentForm",
    useMutationHook: "useCreateComment",
    scope: "public",
  },
  "CreatePost": {
    name: "CreatePost",
    loadSchema: () => import('./CreatePostForm.schema').then((m) => m.CreatePostFormSchema),
    useFormHook: "useCreatePostForm",
    useMutationHook: "useCreatePost",
    scope: "public",
  },
  "CreateTag": {
    name: "CreateTag",
    loadSchema: () => import('./CreateTagForm.schema').then((m) => m.CreateTagFormSchema),
    useFormHook: "useCreateTagForm",
    useMutationHook: "useCreateTag",
    scope: "public",
  },
  "Register": {
    name: "Register",
    loadSchema: () => import('./RegisterForm.schema').then((m) => m.RegisterFormSchema),
    useFormHook: "useRegisterForm",
    useMutationHook: "useRegister",
    scope: "public",
  },
  "SubmitPost": {
    name: "SubmitPost",
    loadSchema: () => import('./SubmitPostForm.schema').then((m) => m.SubmitPostFormSchema),
    useFormHook: "useSubmitPostForm",
    useMutationHook: "useSubmitPost",
    scope: "public",
  },
  "UpdateComment": {
    name: "UpdateComment",
    loadSchema: () => import('./UpdateCommentForm.schema').then((m) => m.UpdateCommentFormSchema),
    useFormHook: "useUpdateCommentForm",
    useMutationHook: "useUpdateComment",
    scope: "public",
  },
  "UpdatePost": {
    name: "UpdatePost",
    loadSchema: () => import('./UpdatePostForm.schema').then((m) => m.UpdatePostFormSchema),
    useFormHook: "useUpdatePostForm",
    useMutationHook: "useUpdatePost",
    scope: "public",
  },
  "UpdateProfile": {
    name: "UpdateProfile",
    loadSchema: () => import('./UpdateProfileForm.schema').then((m) => m.UpdateProfileFormSchema),
    useFormHook: "useUpdateProfileForm",
    useMutationHook: "useUpdateProfile",
    scope: "public",
  },
  "UpdateTag": {
    name: "UpdateTag",
    loadSchema: () => import('./UpdateTagForm.schema').then((m) => m.UpdateTagFormSchema),
    useFormHook: "useUpdateTagForm",
    useMutationHook: "useUpdateTag",
    scope: "public",
  },
};

export const adminFormsManifest: Record<string, FormManifestEntry> = {
};

export const formsManifest: Record<string, FormManifestEntry> = {
  ...publicFormsManifest,
  ...adminFormsManifest,
};

export function resolveFormEntry(name: GeneratedFormName): FormManifestEntry {
  const entry = formsManifest[name];
  if (!entry) throw new Error(`ANG forms manifest: unknown form ${name}`);
  return entry;
}
