// Generated by ANG. Do not edit.
export { CreateCommentForm } from './CreateCommentForm';
export { CreatePostForm } from './CreatePostForm';
export { CreateTagForm } from './CreateTagForm';
export { RegisterForm } from './RegisterForm';
export { SubmitPostForm } from './SubmitPostForm';
export { UpdateCommentForm } from './UpdateCommentForm';
export { UpdatePostForm } from './UpdatePostForm';
export { UpdateProfileForm } from './UpdateProfileForm';
export { UpdateTagForm } from './UpdateTagForm';
