// AUTO-GENERATED by ANG. DO NOT EDIT.
import type { FormSchema } from '@/components/ui/auto-form';
import type { RegisterRequest } from '../../types';

export const RegisterFormSchema: FormSchema<RegisterRequest> = {
  schemaVersion: 1,
  layout: { type: 'grid', columns: 12 },
  fields: [
  {
    name: "email",
    label: "Email",
    type: "email",
    required: true,
    options: [],
    ui: {"type":"email","required":true,"fullWidth":true},
  },
  {
    name: "password",
    label: "Password",
    type: "password",
    required: true,
    options: [],
    ui: {"type":"password","required":true,"fullWidth":true},
  },
  {
    name: "name",
    label: "Name",
    type: "text",
    required: true,
    options: [],
    ui: {"type":"text","required":true,"fullWidth":true},
  },
  ],
};
