// AUTO-GENERATED by ANG. DO NOT EDIT.
import type { FormSchema } from '@/components/ui/auto-form';
import type { UpdatePostRequest } from '../../types';

export const UpdatePostFormSchema: FormSchema<UpdatePostRequest> = {
  schemaVersion: 1,
  layout: { type: 'grid', columns: 12 },
  fields: [
  {
    name: "id",
    label: "Id",
    type: "text",
    required: true,
    options: [],
    ui: {"type":"text","required":true,"fullWidth":true},
  },
  {
    name: "title",
    label: "Title",
    type: "text",
    required: false,
    options: [],
    ui: {"type":"text","fullWidth":true},
  },
  {
    name: "content",
    label: "Content",
    type: "textarea",
    required: false,
    options: [],
    ui: {"type":"textarea","fullWidth":true},
  },
  ],
};
