// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Component: UpdateProfileForm
// Type: Update Form (PATCH/PUT)
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

// ============================================================================
// SECTION: Imports
// PURPOSE: React Hook Form for form state, MUI for UI components
// LIBRARIES:
//   - react-hook-form: Form state management and validation
//   - @mui/material: UI components (TextField, Select, etc.)
//   - @mui/x-date-pickers: Date/time picker components
//   - dayjs: Date manipulation library
// ============================================================================
import { Controller } from 'react-hook-form';
import { Box, Button, Stack, TextField } from '@mui/material';
import { useUpdateProfileForm } from '../../forms';
import { useUpdateProfile } from '../../hooks';
import type { UpdateProfileRequest, UpdateProfileResponse } from '../../types';

// ============================================================================
// SECTION: Component Props
// PURPOSE: Define form component interface
// PROPS:
//   - onSuccess: Callback after successful mutation
//   - onError: Callback on mutation error
//   - onCancel: Callback for cancel button
//   - defaultValues: Pre-populate form fields for editing
// ============================================================================
export interface UpdateProfileFormProps {
  onSuccess?: (data: UpdateProfileResponse) => void;
  onError?: (error: Error) => void;
  onCancel?: () => void;
  defaultValues?: Partial<UpdateProfileRequest>;
}

// ============================================================================
// SECTION: Form Component
// PURPOSE: Render form with controlled inputs and submit handling
// PATTERN: Controller pattern for react-hook-form integration
// MUTATION: useUpdateProfile hook for API call
// ============================================================================
export function UpdateProfileForm({ onSuccess, onError, onCancel, defaultValues }: UpdateProfileFormProps) {
  const form = useUpdateProfileForm({ defaultValues });
  const { mutate, isPending } = useUpdateProfile({
    onSuccess: (data) => onSuccess?.(data),
    onError: (error) => onError?.(error as Error),
  });

  return (
    <Box
      component="form"
      onSubmit={form.handleSubmit((data) => mutate(data))}
      noValidate
    >
      <Stack spacing={3}>

        <Controller
          name="name"
          control={form.control}
          render={({ field, fieldState }) => (
            <TextField
              {...field}
              label="Name"
              helperText={fieldState.error?.message}
              error={!!fieldState.error}
              fullWidth
            />
          )}
        />

        <Controller
          name="avatarUrl"
          control={form.control}
          render={({ field, fieldState }) => (
            <TextField
              {...field}
              type="url"
              label="Avatar URL"
              placeholder="https://"
              helperText={fieldState.error?.message}
              error={!!fieldState.error}
              fullWidth
            />
          )}
        />

        <Stack direction="row" spacing={2} justifyContent="flex-end">
          {onCancel && (
            <Button variant="outlined" onClick={onCancel} disabled={isPending}>
              Отмена
            </Button>
          )}
          <Button type="submit" variant="contained" disabled={isPending}>
            {isPending ? 'Сохранение...' : 'Сохранить'}
          </Button>
        </Stack>
      </Stack>
    </Box>
  );
}
