// Generated by ANG. Do not edit.
// MSW v2 request handlers — use in tests via setupServer(handlers)
import { http, HttpResponse, ws } from 'msw';
import type * as Types from '../types';

// Override status codes for specific endpoints in tests:
// statusOverrides['GetUser'] = 404;
export const statusOverrides: Record<string, number> = {};

// Override response data for specific endpoints in tests:
// dataOverrides['GetUser'] = { id: 'test-id', email: 'test@test.com' };
export const dataOverrides: Record<string, unknown> = {};
/** Mock handler for POST /assistant/chat */
export const mockChatWithAssistant = http.post('*//assistant/chat', () => {
  const status = statusOverrides['ChatWithAssistant'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['ChatWithAssistant'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.ChatWithAssistantResponse> = {
    content: "sample text",
    finishReason: "sample text",
    toolCalls: 42,
    promptTokens: 42,
    completionTokens: 42,
    totalTokens: 42,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /auth/login */
export const mockLogin = http.post('*//auth/login', () => {
  const status = statusOverrides['Login'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['Login'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.LoginResponse> = {
    accessToken: "sample text",
    refreshToken: "sample text",
    user: null,
  };
  return HttpResponse.json(data);
});
/** Mock handler for GET /auth/profile */
export const mockGetProfile = http.get('*//auth/profile', () => {
  const status = statusOverrides['GetProfile'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['GetProfile'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.GetProfileResponse> = {
    ID: "gen-id-123",
    email: "user@example.com",
    name: "sample text",
    role: "sample text",
    avatarUrl: "sample text",
    createdAt: "sample text",
  };
  return HttpResponse.json(data);
});
/** Mock handler for PUT /auth/profile */
export const mockUpdateProfile = http.put('*//auth/profile', () => {
  const status = statusOverrides['UpdateProfile'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['UpdateProfile'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.UpdateProfileResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /auth/register */
export const mockRegister = http.post('*//auth/register', () => {
  const status = statusOverrides['Register'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['Register'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.RegisterResponse> = {
    ID: "gen-id-123",
    email: "user@example.com",
    name: "sample text",
  };
  return HttpResponse.json(data);
});
/** Mock handler for DELETE /comments/{id} */
export const mockDeleteComment = http.delete('*//comments/:id', () => {
  const status = statusOverrides['DeleteComment'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['DeleteComment'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.DeleteCommentResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for PUT /comments/{id} */
export const mockUpdateComment = http.put('*//comments/:id', () => {
  const status = statusOverrides['UpdateComment'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['UpdateComment'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.UpdateCommentResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for GET /my/posts */
export const mockListMyPosts = http.get('*//my/posts', () => {
  const status = statusOverrides['ListMyPosts'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['ListMyPosts'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.ListMyPostsResponse> = {
    data: [],
  };
  return HttpResponse.json(data);
});
/** Mock handler for GET /posts */
export const mockListPosts = http.get('*//posts', () => {
  const status = statusOverrides['ListPosts'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['ListPosts'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.ListPostsResponse> = {
    data: [],
    total: 42,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /posts */
export const mockCreatePost = http.post('*//posts', () => {
  const status = statusOverrides['CreatePost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['CreatePost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.CreatePostResponse> = {
    ID: "gen-id-123",
    slug: "sample text",
  };
  return HttpResponse.json(data);
});
/** Mock handler for DELETE /posts/{id} */
export const mockDeletePost = http.delete('*//posts/:id', () => {
  const status = statusOverrides['DeletePost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['DeletePost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.DeletePostResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for PUT /posts/{id} */
export const mockUpdatePost = http.put('*//posts/:id', () => {
  const status = statusOverrides['UpdatePost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['UpdatePost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.UpdatePostResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /posts/{id}/archive */
export const mockArchivePost = http.post('*//posts/:id/archive', () => {
  const status = statusOverrides['ArchivePost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['ArchivePost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.ArchivePostResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /posts/{id}/publish */
export const mockPublishPost = http.post('*//posts/:id/publish', () => {
  const status = statusOverrides['PublishPost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['PublishPost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.PublishPostResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /posts/{id}/submit */
export const mockSubmitPost = http.post('*//posts/:id/submit', () => {
  const status = statusOverrides['SubmitPost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['SubmitPost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.SubmitPostResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for GET /posts/{postID}/comments */
export const mockListComments = http.get('*//posts/:postID/comments', () => {
  const status = statusOverrides['ListComments'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['ListComments'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.ListCommentsResponse> = {
    data: [],
    total: 42,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /posts/{postID}/comments */
export const mockCreateComment = http.post('*//posts/:postID/comments', () => {
  const status = statusOverrides['CreateComment'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['CreateComment'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.CreateCommentResponse> = {
    ID: "gen-id-123",
  };
  return HttpResponse.json(data);
});
/** Mock handler for GET /posts/{slug} */
export const mockGetPost = http.get('*//posts/:slug', () => {
  const status = statusOverrides['GetPost'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['GetPost'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.GetPostResponse> = {
    ID: "gen-id-123",
    title: "sample text",
    content: "sample text",
    authorId: "gen-id-123",
    createdAt: "sample text",
    tags: [],
  };
  return HttpResponse.json(data);
});
/** Mock handler for GET /tags */
export const mockListTags = http.get('*//tags', () => {
  const status = statusOverrides['ListTags'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['ListTags'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.ListTagsResponse> = {
    data: [],
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /tags */
export const mockCreateTag = http.post('*//tags', () => {
  const status = statusOverrides['CreateTag'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['CreateTag'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.CreateTagResponse> = {
    ID: "gen-id-123",
    slug: "sample text",
  };
  return HttpResponse.json(data);
});
/** Mock handler for DELETE /tags/{id} */
export const mockDeleteTag = http.delete('*//tags/:id', () => {
  const status = statusOverrides['DeleteTag'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['DeleteTag'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.DeleteTagResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for PUT /tags/{id} */
export const mockUpdateTag = http.put('*//tags/:id', () => {
  const status = statusOverrides['UpdateTag'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['UpdateTag'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.UpdateTagResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /notifications/invitation */
export const mockSendInvitationEmail = http.post('*//notifications/invitation', () => {
  const status = statusOverrides['SendInvitationEmail'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['SendInvitationEmail'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.SendInvitationEmailResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});
/** Mock handler for POST /notifications/password-reset */
export const mockSendPasswordResetEmail = http.post('*//notifications/password-reset', () => {
  const status = statusOverrides['SendPasswordResetEmail'] ?? 200;
  if (status !== 200) {
    return HttpResponse.json(
      { code: 'MOCK_ERROR', title: 'Mocked error', detail: 'Status overridden in test', status },
      { status }
    );
  }
  const override = dataOverrides['SendPasswordResetEmail'];
  if (override !== undefined) {
    return HttpResponse.json(override);
  }
  const data: Partial<Types.SendPasswordResetEmailResponse> = {
    ok: true,
  };
  return HttpResponse.json(data);
});

export const handlers = [
  mockChatWithAssistant,
  mockLogin,
  mockGetProfile,
  mockUpdateProfile,
  mockRegister,
  mockDeleteComment,
  mockUpdateComment,
  mockListMyPosts,
  mockListPosts,
  mockCreatePost,
  mockDeletePost,
  mockUpdatePost,
  mockArchivePost,
  mockPublishPost,
  mockSubmitPost,
  mockListComments,
  mockCreateComment,
  mockGetPost,
  mockListTags,
  mockCreateTag,
  mockDeleteTag,
  mockUpdateTag,
  mockSendInvitationEmail,
  mockSendPasswordResetEmail,
];
