// Generated by ANG. Do not edit.
// MSW v2 test server setup.
// Usage in vitest/jest: import './mocks/server' in setupTests.ts
import { setupServer } from 'msw/node';
import { handlers } from './handlers';

export const server = setupServer(...handlers);

// Auto-setup lifecycle hooks (add to vitest.setup.ts or jest.setup.ts):
//   import { server } from './mocks/server';
//   beforeAll(() => server.listen({ onUnhandledRequest: 'warn' }));
//   afterEach(() => server.resetHandlers());
//   afterAll(() => server.close());
