// Code generated by ANG v0.1.126 from:
//   cue/api/auth.cue (sha: 48b5e49c)
// DO NOT EDIT.

package service

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"net/http"
	"time"

	"github.com/example/blog/internal/domain"
	"github.com/example/blog/internal/pkg/errors"
	"github.com/example/blog/internal/pkg/helpers"
	"github.com/example/blog/internal/port"
	"github.com/google/uuid"
)

// Generated from: cue/api/auth.cue:12
func (s *AuthImpl) Register(ctx context.Context, req port.RegisterRequest) (resp port.RegisterResponse, err error) {
	existing, err := s.UserRepo.FindByEmail(ctx, req.Email)
	if err != nil {
		return resp, err
	}
	if !(existing == nil) {
		return resp, errors.New(http.StatusBadRequest, "Validation Error", "Email already registered")
	}
	var newUser domain.User
	if err := helpers.Assign(&newUser.Email, req.Email); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newUser.Name, req.Name); err != nil {
		return resp, err
	}
	_sha256Sum_5 := sha256.Sum256([]byte(req.Password))
	hash := hex.EncodeToString(_sha256Sum_5[:])
	if err := helpers.Assign(&newUser.PasswordHash, hash); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newUser.Role, "reader"); err != nil {
		return resp, err
	}
	_newUserAutoID := uuid.NewString()
	if err := helpers.Assign(&newUser.ID, _newUserAutoID); err != nil {
		return resp, err
	}
	_newUserAutoCreatedAt := time.Now().UTC().Format(time.RFC3339)
	if err := helpers.Assign(&newUser.CreatedAt, _newUserAutoCreatedAt); err != nil {
		return resp, err
	}
	if err := s.UserRepo.Save(ctx, &newUser); err != nil {
		return resp, err
	}
	if s.publisher != nil {
		_ = s.publisher.PublishUserRegistered(ctx, domain.UserRegistered{Email: newUser.Email, UserID: newUser.ID})
	}
	if err := helpers.Assign(&resp.ID, newUser.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Email, newUser.Email); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Name, newUser.Name); err != nil {
		return resp, err
	}

	return resp, nil
}
