// Code generated by ANG v0.1.126 from:
//   cue/api/auth.cue (sha: 48b5e49c)
// DO NOT EDIT.

package service

import (
	"github.com/example/blog/internal/port"
)

type AuthImpl struct {
	UserRepo  port.UserRepository
	publisher port.Publisher
}

func NewAuthImpl(userRepo port.UserRepository, publisher port.Publisher) *AuthImpl {
	return &AuthImpl{UserRepo: userRepo, publisher: publisher}
}
