// Code generated by ANG v0.1.127 from:
//   cue/api/auth.cue (sha: e6ddda61)
// DO NOT EDIT.

package service

import (
	"github.com/example/blog/internal/port"
)

type AuthImpl struct {
	UserRepo   port.UserRepository
	publisher  port.Publisher
	dispatcher port.NotificationDispatcher
}

func NewAuthImpl(userRepo port.UserRepository, publisher port.Publisher, dispatcher port.NotificationDispatcher) *AuthImpl {
	return &AuthImpl{UserRepo: userRepo, publisher: publisher, dispatcher: dispatcher}
}
