// Code generated by ANG v0.1.126 from:
//   cue/api/tags.cue (sha: ee9ecea1)
// DO NOT EDIT.

package service

import (
	"context"
	"fmt"
	"net/http"
	"regexp"
	"strings"
	"time"

	"github.com/example/blog/internal/domain"
	"github.com/example/blog/internal/pkg/errors"
	"github.com/example/blog/internal/pkg/helpers"
	"github.com/example/blog/internal/port"
	"github.com/google/uuid"
)

// Generated from: cue/api/tags.cue:34
func (s *BlogImpl) CreateTag(ctx context.Context, req port.CreateTagRequest) (resp port.CreateTagResponse, err error) {
	slug := strings.ToLower(strings.TrimSpace(req.Name))
	_re_1, _reErr_1 := regexp.Compile("[^a-z0-9]+")
	if _reErr_1 != nil {
		return resp, fmt.Errorf("regex.Replace: %w", _reErr_1)
	}
	slug = _re_1.ReplaceAllString(slug, "-")
	_re_2, _reErr_2 := regexp.Compile("(^-|-$)")
	if _reErr_2 != nil {
		return resp, fmt.Errorf("regex.Replace: %w", _reErr_2)
	}
	slug = _re_2.ReplaceAllString(slug, "")
	if !(slug != "") {
		return resp, errors.New(http.StatusBadRequest, "Validation Error", "Unable to derive slug from name")
	}
	existing, err := s.TagRepo.FindBySlug(ctx, slug)
	if err != nil {
		return resp, err
	}
	if !(existing == nil) {
		return resp, errors.New(http.StatusBadRequest, "Validation Error", "Tag already exists")
	}
	var newTag domain.Tag
	if err := helpers.Assign(&newTag.Name, req.Name); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newTag.Slug, slug); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newTag.Description, req.Description); err != nil {
		return resp, err
	}
	_newTagAutoID := uuid.NewString()
	if err := helpers.Assign(&newTag.ID, _newTagAutoID); err != nil {
		return resp, err
	}
	_newTagAutoCreatedAt := time.Now().UTC().Format(time.RFC3339)
	if err := helpers.Assign(&newTag.CreatedAt, _newTagAutoCreatedAt); err != nil {
		return resp, err
	}
	if err := s.TagRepo.Save(ctx, &newTag); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.ID, newTag.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Slug, newTag.Slug); err != nil {
		return resp, err
	}

	return resp, nil
}
