// Code generated by ANG v0.1.126 from:
//   cue/api/comments.cue (sha: 81d10c9d)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"
	"time"

	"github.com/example/blog/internal/domain"
	"github.com/example/blog/internal/pkg/errors"
	"github.com/example/blog/internal/pkg/helpers"
	"github.com/example/blog/internal/port"
	"github.com/google/uuid"
)

// Generated from: cue/api/comments.cue:12
func (s *BlogImpl) CreateComment(ctx context.Context, req port.CreateCommentRequest) (resp port.CreateCommentResponse, err error) {
	post, err := s.PostRepo.FindByID(ctx, req.PostID)
	if err != nil {
		return resp, err
	}
	if post == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "Post not found")
	}
	var newComment domain.Comment
	if err := helpers.Assign(&newComment.PostID, req.PostID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newComment.AuthorID, req.UserID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&newComment.Content, req.Content); err != nil {
		return resp, err
	}
	_newCommentAutoID := uuid.NewString()
	if err := helpers.Assign(&newComment.ID, _newCommentAutoID); err != nil {
		return resp, err
	}
	_newCommentAutoCreatedAt := time.Now().UTC().Format(time.RFC3339)
	if err := helpers.Assign(&newComment.CreatedAt, _newCommentAutoCreatedAt); err != nil {
		return resp, err
	}
	if err := s.CommentRepo.Save(ctx, &newComment); err != nil {
		return resp, err
	}
	if s.publisher != nil {
		_ = s.publisher.PublishCommentCreated(ctx, domain.CommentCreated{AuthorID: newComment.AuthorID, CommentID: newComment.ID, PostID: newComment.PostID})
	}
	if err := helpers.Assign(&resp.ID, newComment.ID); err != nil {
		return resp, err
	}

	return resp, nil
}
