// Code generated by ANG v0.1.126 from:
//   cue/api/posts.cue (sha: a4cd4cf1)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"

	"github.com/example/blog/internal/domain"
	"github.com/example/blog/internal/pkg/errors"
	"github.com/example/blog/internal/pkg/helpers"
	"github.com/example/blog/internal/port"
)

// Generated from: cue/api/posts.cue:180
func (s *BlogImpl) UpdatePost(ctx context.Context, req port.UpdatePostRequest) (resp port.UpdatePostResponse, err error) {
	post, err := s.PostRepo.FindByID(ctx, req.ID)
	if err != nil {
		return resp, err
	}
	if post == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "Post not found")
	}
	if req.Title != "" {
		if err := helpers.Assign(&post.Title, req.Title); err != nil {
			return resp, err
		}
	}
	if req.Content != "" {
		if err := helpers.Assign(&post.Content, req.Content); err != nil {
			return resp, err
		}
	}
	if err := s.PostRepo.Save(ctx, post); err != nil {
		return resp, err
	}
	if s.publisher != nil {
		_ = s.publisher.PublishPostUpdated(ctx, domain.PostUpdated{PostID: post.ID})
	}
	if err := helpers.Assign(&resp.Ok, true); err != nil {
		return resp, err
	}

	return resp, nil
}
