// Code generated by ANG v0.1.127 from:
//   cue/api/posts.cue (sha: a4cd4cf1)
// DO NOT EDIT.

package service

import (
	"context"

	"github.com/example/blog/internal/pkg/helpers"
	"github.com/example/blog/internal/port"
)

// Generated from: cue/api/posts.cue:111
func (s *BlogImpl) ListPosts(ctx context.Context, req port.ListPostsRequest) (resp port.ListPostsResponse, err error) {
	if req.Tag != "" {
		posts, err := s.PostRepo.ListPublishedByTag(ctx, "published", req.Tag)
		if err != nil {
			return resp, err
		}
		totalCount, err := s.PostRepo.CountPublishedByTag(ctx, "published", req.Tag)
		if err != nil {
			return resp, err
		}
		if err := helpers.Assign(&resp.Data, posts); err != nil {
			return resp, err
		}
		if err := helpers.Assign(&resp.Total, totalCount); err != nil {
			return resp, err
		}
	} else {
		posts, err := s.PostRepo.ListPublished(ctx, "published")
		if err != nil {
			return resp, err
		}
		totalCount, err := s.PostRepo.CountPublished(ctx, "published")
		if err != nil {
			return resp, err
		}
		if err := helpers.Assign(&resp.Data, posts); err != nil {
			return resp, err
		}
		if err := helpers.Assign(&resp.Total, totalCount); err != nil {
			return resp, err
		}
	}

	return resp, nil
}
