// Code generated by ANG v0.1.127 from:
//   cue/api/posts.cue (sha: a4cd4cf1)
// DO NOT EDIT.

package service

import (
	"context"
	"net/http"

	"github.com/example/blog/internal/pkg/errors"
	"github.com/example/blog/internal/pkg/helpers"
	"github.com/example/blog/internal/port"
)

// Generated from: cue/api/posts.cue:76
func (s *BlogImpl) GetPost(ctx context.Context, req port.GetPostRequest) (resp port.GetPostResponse, err error) {
	post, err := s.PostRepo.FindBySlug(ctx, req.Slug)
	if err != nil {
		return resp, err
	}
	if post == nil {
		return resp, errors.New(http.StatusNotFound, "Not Found", "Post not found")
	}
	tags, err := s.TagRepo.ListByPost(ctx, post.ID)
	if err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.ID, post.ID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Title, post.Title); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Content, post.Content); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.AuthorID, post.AuthorID); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.CreatedAt, post.CreatedAt); err != nil {
		return resp, err
	}
	if err := helpers.Assign(&resp.Tags, tags); err != nil {
		return resp, err
	}

	return resp, nil
}
