// Code generated by ANG. DO NOT EDIT.
package mock

import (
	"context"

	"github.com/example/minimal/internal/port"
)

type MockNotificationFailureRecorder struct {
	RecordFailureFunc  func(ctx context.Context, failure port.NotificationFailure) error
	RecordFailureCalls []MockNotificationFailureRecorderRecordFailureCall
}

var _ port.NotificationFailureRecorder = (*MockNotificationFailureRecorder)(nil)

func NewNotificationFailureRecorder() *MockNotificationFailureRecorder {
	return &MockNotificationFailureRecorder{}
}

type MockNotificationFailureRecorderRecordFailureCall struct {
	Ctx     context.Context
	Failure port.NotificationFailure
}

func (m *MockNotificationFailureRecorder) RecordFailure(ctx context.Context, failure port.NotificationFailure) error {
	m.RecordFailureCalls = append(m.RecordFailureCalls, MockNotificationFailureRecorderRecordFailureCall{Ctx: ctx, Failure: failure})
	if m.RecordFailureFunc != nil {
		return m.RecordFailureFunc(ctx, failure)
	}
	var ret0 error
	return ret0
}
