// Code generated by ANG. DO NOT EDIT.
package mock

import (
	"context"

	"github.com/example/minimal/internal/domain"
	"github.com/example/minimal/internal/port"
)

type MockUserRepository struct {
	SaveFunc      func(ctx context.Context, entity *domain.User) error
	SaveCalls     []MockUserRepositorySaveCall
	FindByIDFunc  func(ctx context.Context, id string) (*domain.User, error)
	FindByIDCalls []MockUserRepositoryFindByIDCall
	DeleteFunc    func(ctx context.Context, id string) error
	DeleteCalls   []MockUserRepositoryDeleteCall
	InsertFunc    func(ctx context.Context, entity *domain.User) error
	InsertCalls   []MockUserRepositoryInsertCall
	UpdateFunc    func(ctx context.Context, entity *domain.User) error
	UpdateCalls   []MockUserRepositoryUpdateCall
	LockByIDFunc  func(ctx context.Context, id string) (*domain.User, error)
	LockByIDCalls []MockUserRepositoryLockByIDCall
	ListFunc      func(ctx context.Context) ([]domain.User, error)
	ListCalls     []MockUserRepositoryListCall
	ListAllFunc   func(ctx context.Context, offset int, limit int) ([]domain.User, error)
	ListAllCalls  []MockUserRepositoryListAllCall
}

var _ port.UserRepository = (*MockUserRepository)(nil)

func NewUserRepository() *MockUserRepository {
	return &MockUserRepository{}
}

type MockUserRepositorySaveCall struct {
	Ctx    context.Context
	Entity *domain.User
}

func (m *MockUserRepository) Save(ctx context.Context, entity *domain.User) error {
	m.SaveCalls = append(m.SaveCalls, MockUserRepositorySaveCall{Ctx: ctx, Entity: entity})
	if m.SaveFunc != nil {
		return m.SaveFunc(ctx, entity)
	}
	var ret0 error
	return ret0
}

type MockUserRepositoryFindByIDCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockUserRepository) FindByID(ctx context.Context, id string) (*domain.User, error) {
	m.FindByIDCalls = append(m.FindByIDCalls, MockUserRepositoryFindByIDCall{Ctx: ctx, ID: id})
	if m.FindByIDFunc != nil {
		return m.FindByIDFunc(ctx, id)
	}
	var ret0 *domain.User
	var ret1 error
	return ret0, ret1
}

type MockUserRepositoryDeleteCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockUserRepository) Delete(ctx context.Context, id string) error {
	m.DeleteCalls = append(m.DeleteCalls, MockUserRepositoryDeleteCall{Ctx: ctx, ID: id})
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, id)
	}
	var ret0 error
	return ret0
}

type MockUserRepositoryInsertCall struct {
	Ctx    context.Context
	Entity *domain.User
}

func (m *MockUserRepository) Insert(ctx context.Context, entity *domain.User) error {
	m.InsertCalls = append(m.InsertCalls, MockUserRepositoryInsertCall{Ctx: ctx, Entity: entity})
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, entity)
	}
	var ret0 error
	return ret0
}

type MockUserRepositoryUpdateCall struct {
	Ctx    context.Context
	Entity *domain.User
}

func (m *MockUserRepository) Update(ctx context.Context, entity *domain.User) error {
	m.UpdateCalls = append(m.UpdateCalls, MockUserRepositoryUpdateCall{Ctx: ctx, Entity: entity})
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, entity)
	}
	var ret0 error
	return ret0
}

type MockUserRepositoryLockByIDCall struct {
	Ctx context.Context
	ID  string
}

func (m *MockUserRepository) LockByID(ctx context.Context, id string) (*domain.User, error) {
	m.LockByIDCalls = append(m.LockByIDCalls, MockUserRepositoryLockByIDCall{Ctx: ctx, ID: id})
	if m.LockByIDFunc != nil {
		return m.LockByIDFunc(ctx, id)
	}
	var ret0 *domain.User
	var ret1 error
	return ret0, ret1
}

type MockUserRepositoryListCall struct {
	Ctx context.Context
}

func (m *MockUserRepository) List(ctx context.Context) ([]domain.User, error) {
	m.ListCalls = append(m.ListCalls, MockUserRepositoryListCall{Ctx: ctx})
	if m.ListFunc != nil {
		return m.ListFunc(ctx)
	}
	var ret0 []domain.User
	var ret1 error
	return ret0, ret1
}

type MockUserRepositoryListAllCall struct {
	Ctx    context.Context
	Offset int
	Limit  int
}

func (m *MockUserRepository) ListAll(ctx context.Context, offset int, limit int) ([]domain.User, error) {
	m.ListAllCalls = append(m.ListAllCalls, MockUserRepositoryListAllCall{Ctx: ctx, Offset: offset, Limit: limit})
	if m.ListAllFunc != nil {
		return m.ListAllFunc(ctx, offset, limit)
	}
	var ret0 []domain.User
	var ret1 error
	return ret0, ret1
}
