package emitter

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/strogmv/ang/angir/ir"
)

// EmitConventionsDoc writes docs/ang/conventions.md: the names and signatures
// this project's generated code uses that cannot be guessed from CUE. Every
// table in it is built from the same IR and naming rules the emitters use, so
// the document cannot disagree with the code.
func (e *Emitter) EmitConventionsDoc(schema *ir.Schema) error {
	if schema == nil {
		schema = &ir.Schema{}
	}
	var b strings.Builder
	b.WriteString("<!-- Code generated by ANG. DO NOT EDIT. -->\n\n")
	b.WriteString("# Generated code conventions\n\n")
	b.WriteString("Names and signatures the generator derives from CUE. They are fixed: the\n")
	b.WriteString("tables are in the production database, the types are in the API contract.\n\n")

	b.WriteString("## Rules\n\n")
	b.WriteString("- Table name = lower-case entity name + `s` (`Country` → `countrys`, `Company` → `companys`).\n")
	b.WriteString("- Array item type of an operation field: `data` → `<Op>ResponseData`; any other field → `<Op>Response<Field>Item`, in the input `<Op>Request<Field>Item`.\n")
	b.WriteString("- A repository finder with `action: \"delete\"` returns `(int64, error)` — the number of rows removed.\n")
	b.WriteString("- An input field named `body` receives the raw HTTP body (reported as `W_RAW_BODY_IMPLICIT`); declare `@rawBody()` when that is meant, otherwise name the field `text` or `message`.\n")
	b.WriteString("- Go in CUE is written as raw strings `#\"\"\"…\"\"\"#`: no escaping, interpolation is `\\#(…)`. Run `ang fmt` after editing.\n\n")

	b.WriteString("## Tables\n\n")
	tables := conventionTables(schema.Entities)
	if len(tables) == 0 {
		b.WriteString("None.\n\n")
	} else {
		b.WriteString("| Entity | Table |\n|---|---|\n")
		for _, row := range tables {
			fmt.Fprintf(&b, "| `%s` | `%s` |\n", row[0], row[1])
		}
		b.WriteString("\n")
	}

	b.WriteString("## Array item types\n\n")
	items := conventionItemTypes(schema.Services)
	if len(items) == 0 {
		b.WriteString("None.\n\n")
	} else {
		b.WriteString("| Operation field | Go type |\n|---|---|\n")
		for _, row := range items {
			fmt.Fprintf(&b, "| `%s` | `port.%s` |\n", row[0], row[1])
		}
		b.WriteString("\n")
	}

	b.WriteString("## Frontend SDK modules\n\n")
	b.WriteString("Optional parts of the generated SDK. A module listed in `frontend_sdk_skip` of the target (cue/project) is not generated; remove it from the list to get it back.\n\n")
	b.WriteString("| Module | Status | What it is |\n|---|---|---|\n")
	for _, m := range frontendSDKModules {
		status := "generated"
		if !e.sdkModuleEnabled(m.Name) {
			status = "skipped"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", m.Name, status, m.Description)
	}
	b.WriteString("\n")

	b.WriteString("## Generated files\n\n")
	b.WriteString("`ang-generated.txt` lists every file ANG generates in this project. Do not edit a listed file: the next build overwrites it. A listed file the project stops generating is removed by the next build; a file that was never listed is left alone.\n\n")

	b.WriteString("## Delete finders\n\n")
	deletes := conventionDeleteFinders(schema.Repos)
	if len(deletes) == 0 {
		b.WriteString("None.\n")
	} else {
		for _, finder := range deletes {
			fmt.Fprintf(&b, "- `%s` → `(int64, error)`\n", finder)
		}
	}

	dir := e.outDir("docs", "ang")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	path := e.outDir("docs", "ang", "conventions.md")
	if err := WriteFileIfChanged(path, []byte(b.String()), 0o644); err != nil {
		return err
	}
	logGenerated("Generated Conventions Doc: %s\n", path)
	return nil
}

// conventionTables lists the SQL tables EmitSQL creates: entities with an id
// field that are not Mongo documents.
func conventionTables(entities []ir.Entity) [][2]string {
	var rows [][2]string
	for _, entity := range IREntitiesToNormalizer(entities) {
		hasID, isMongo := false, false
		for _, f := range entity.Fields {
			if strings.EqualFold(f.Name, "id") {
				hasID = true
			}
			if strings.EqualFold(f.DB.Type, "ObjectId") {
				isMongo = true
			}
		}
		if hasID && !isMongo {
			rows = append(rows, [2]string{entity.Name, strings.ToLower(entity.Name) + "s"})
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i][0] < rows[j][0] })
	return rows
}

func conventionItemTypes(services []ir.Service) [][2]string {
	seen := map[string]string{}
	for _, svc := range IRServicesToNormalizer(services) {
		for _, m := range svc.Methods {
			for _, f := range m.Input.Fields {
				if f.ItemTypeName != "" && len(f.ItemFields) > 0 {
					seen[m.Name+" input."+f.Name] = f.ItemTypeName
				}
			}
			for _, f := range m.Output.Fields {
				if f.ItemTypeName != "" && len(f.ItemFields) > 0 {
					seen[m.Name+" output."+f.Name] = f.ItemTypeName
				}
			}
		}
	}
	rows := make([][2]string, 0, len(seen))
	for key, typ := range seen {
		rows = append(rows, [2]string{key, typ})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i][0] < rows[j][0] })
	return rows
}

func conventionDeleteFinders(repos []ir.Repository) []string {
	var out []string
	for _, repo := range IRReposToNormalizer(repos) {
		for _, finder := range repo.Finders {
			if finder.Action == "delete" {
				out = append(out, repo.Name+"."+finder.Name)
			}
		}
	}
	sort.Strings(out)
	return out
}
