package emitter

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/strogmv/ang-ir/normalizer"
)

// EmitEffectRegistry generates internal/bootstrap/effect_registry.gen.go with
// both declarative handler metadata and concrete runtime wiring.
func (e *Emitter) EmitEffectRegistry(ctx MainContext, infraValues map[string]any) error {
	target := filepath.Join(e.OutputDir, "internal", "bootstrap", "effect_registry.gen.go")
	src := e.renderEffectRegistrySource(ctx, infraValues)
	formatted, err := formatGoStrict([]byte(src), "internal/bootstrap/effect_registry.gen.go")
	if err != nil {
		return err
	}
	if err := WriteFileIfChanged(target, formatted, 0o644); err != nil {
		return err
	}
	fmt.Printf("Generated Effect Registry: %s\n", target)
	return nil
}

func (e *Emitter) renderEffectRegistrySource(ctx MainContext, infraValues map[string]any) string {
	handlers := normalizer.InfraEffectHandlers(infraValues)
	testHandlers := normalizer.InfraEffectTestHandlers(infraValues)
	middleware := normalizer.InfraEffectMiddleware(infraValues)

	services := append([]normalizer.Service(nil), ctx.Services...)
	entities := append([]normalizer.Entity(nil), ctx.Entities...)
	repoEntities := collectEffectRegistryRepoEntities(services, entities)
	hasMongoRepos := false
	for _, name := range repoEntities {
		if entityStorageByName(entities, name) == "mongo" {
			hasMongoRepos = true
			break
		}
	}

	needsPG := ctx.HasSQL || len(repoEntities) > 0
	needsS3 := ctx.HasS3 || anyServiceHasStorageActions(services)
	needsPolicy := anyServiceHasPolicyActions(services)
	needsState := anyServiceHasStateActions(services)
	needsSystemRepo := needsPG && (anyServiceHasIdempotencyOrOutbox(services) || needsState)
	needsRedis := ctx.HasCache || ctx.AuthRefreshStore == "redis" || ctx.AuthRefreshStore == "hybrid"

	var b strings.Builder
	b.WriteString("// Code generated by ANG. DO NOT EDIT.\n")
	b.WriteString("package bootstrap\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\teffectmw " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/middleware") + "\n")
	if needsPG {
		b.WriteString("\t\"github.com/jackc/pgx/v5/pgxpool\"\n")
	}
	if ctx.HasMongo {
		b.WriteString("\t\"go.mongodb.org/mongo-driver/mongo\"\n")
	}
	if needsRedis {
		b.WriteString("\t\"github.com/redis/go-redis/v9\"\n")
	}
	switch ctx.AuthRefreshStore {
	case "memory":
		b.WriteString("\tauthstore " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/auth/memory") + "\n")
	case "redis":
		b.WriteString("\tauthredis " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/auth/redis") + "\n")
	case "postgres":
		b.WriteString("\tauthpg " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/auth/postgres") + "\n")
	case "hybrid":
		b.WriteString("\tauthhybrid " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/auth/hybrid") + "\n")
		b.WriteString("\tauthpg " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/auth/postgres") + "\n")
		b.WriteString("\tauthredis " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/auth/redis") + "\n")
	}
	if ctx.NotificationMuting {
		b.WriteString("\t" + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter") + "\n")
	}
	if needsPG {
		b.WriteString("\t" + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/repository/postgres") + "\n")
	}
	if hasMongoRepos {
		b.WriteString("\tmongorepo " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/repository/mongo") + "\n")
	}
	if needsPG && needsState {
		b.WriteString("\tredisclient " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/cache/redis") + "\n")
		b.WriteString("\tredistore " + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/adapter/statestore/redis") + "\n")
	}
	if needsPolicy {
		b.WriteString("\t" + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/pkg/policy") + "\n")
	}
	b.WriteString("\t" + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/config") + "\n")
	b.WriteString("\t" + strconv.Quote(strings.TrimSpace(e.GoModule)+"/internal/port") + "\n")
	b.WriteString(")\n\n")

	b.WriteString("type EffectHandler struct {\n")
	b.WriteString("\tKind string\n")
	b.WriteString("\tDriver string\n")
	b.WriteString("\tProvider string\n")
	b.WriteString("\tOptions map[string]any\n")
	b.WriteString("}\n\n")
	b.WriteString("type EffectProfile struct {\n")
	b.WriteString("\tHandlers map[string]EffectHandler\n")
	b.WriteString("\tMiddleware map[string][]effectmw.EffectMiddleware\n")
	b.WriteString("}\n\n")
	b.WriteString("func (p EffectProfile) Handler(kind string) (EffectHandler, bool) {\n")
	b.WriteString("\tv, ok := p.Handlers[kind]\n\treturn v, ok\n}\n\n")
	b.WriteString("func (p EffectProfile) Chain(kind string) []effectmw.EffectMiddleware {\n")
	b.WriteString("\treturn p.Middleware[kind]\n}\n\n")

	b.WriteString("type EffectRegistry struct {\n")
	for _, name := range repoEntities {
		b.WriteString("\tRepo" + ExportName(name) + " port." + ExportName(name) + "Repository\n")
	}
	if needsSystemRepo {
		if anyServiceHasIdempotency(services) {
			b.WriteString("\tIdempotency port.IdempotencyStore\n")
		}
		if anyServiceHasOutbox(services) {
			b.WriteString("\tOutbox port.OutboxRepository\n")
		}
	}
	if ctx.AuthService != "" && ctx.AuthRefreshStore != "" {
		b.WriteString("\tRefreshStore port.RefreshTokenStore\n")
	}
	if anyServiceNeedsTx(services) {
		b.WriteString("\tTxManager port.TxManager\n")
	}
	b.WriteString("\tPublisher port.Publisher\n")
	b.WriteString("\tStorage port.FileStorage\n")
	b.WriteString("\tStateStore port.StateStore\n")
	if ctx.HasNotificationsService || ctx.HasNotificationDispatch {
		b.WriteString("\tNotificationDispatcher port.NotificationDispatcher\n")
	}
	if needsPolicy {
		b.WriteString("\tPolicyEngine port.PolicyEngine\n")
	}
	b.WriteString("\t// Runtime EffectProfile metadata\n")
	b.WriteString("\tRuntime EffectProfile\n")
	b.WriteString("\t// Test EffectProfile metadata\n")
	b.WriteString("\tTest EffectProfile\n")
	b.WriteString("}\n\n")

	b.WriteString("func NewEffectRegistry(\n")
	b.WriteString("\tctx context.Context,\n")
	b.WriteString("\tcfg *config.Config,\n")
	if needsPG {
		b.WriteString("\tpgPool *pgxpool.Pool,\n")
	}
	if ctx.HasMongo {
		b.WriteString("\tmongoClient *mongo.Client,\n")
	}
	if needsRedis {
		b.WriteString("\tredisClient *redis.Client,\n")
	}
	b.WriteString("\tpublisher port.Publisher,\n")
	if needsS3 {
		b.WriteString("\ts3Client port.FileStorage,\n")
	}
	if ctx.HasNotificationsService || ctx.HasNotificationDispatch {
		b.WriteString("\tnotificationDispatcher port.NotificationDispatcher,\n")
	}
	b.WriteString(") (*EffectRegistry, error) {\n")
	b.WriteString("\t_ = ctx\n")
	b.WriteString("\treg := &EffectRegistry{\n")
	b.WriteString("\t\tPublisher: publisher,\n")
	if needsS3 {
		b.WriteString("\t\tStorage: s3Client,\n")
	}
	if ctx.HasNotificationsService || ctx.HasNotificationDispatch {
		b.WriteString("\t\tNotificationDispatcher: notificationDispatcher,\n")
	}
	b.WriteString("\t\tRuntime: EffectProfile{Handlers: " + renderEffectHandlerMap(handlers) + ", Middleware: " + renderEffectMiddlewareMap(middleware) + "},\n")
	b.WriteString("\t\tTest: EffectProfile{Handlers: " + renderEffectHandlerMap(testHandlers) + ", Middleware: " + renderEffectMiddlewareMap(middleware) + "},\n")
	b.WriteString("\t}\n")
	b.WriteString("\treg.Publisher = effectmw.WrapPublisher(reg.Publisher, reg.Runtime.Chain(\"events\"))\n")
	if needsS3 {
		b.WriteString("\treg.Storage = effectmw.WrapFileStorage(reg.Storage, reg.Runtime.Chain(\"storage\"))\n")
	}

	for _, name := range repoEntities {
		if entityStorageByName(entities, name) == "mongo" {
			b.WriteString("\treg.Repo" + ExportName(name) + " = mongorepo.New" + ExportName(name) + "Repository(mongoClient, cfg.MongoDatabase)\n")
		} else {
			b.WriteString("\treg.Repo" + ExportName(name) + " = postgres.New" + ExportName(name) + "Repository(pgPool)\n")
		}
	}
	if ctx.NotificationMuting && hasEntityByName(entities, "Notification") && hasEntityByName(entities, "User") {
		b.WriteString("\tif reg.RepoNotification != nil && reg.RepoUser != nil {\n")
		b.WriteString("\t\treg.RepoNotification = adapter.NewMutingNotificationRepo(reg.RepoNotification, reg.RepoUser)\n")
		b.WriteString("\t}\n")
	}
	if needsSystemRepo {
		b.WriteString("\trepoSystem := postgres.NewSystemRepository(pgPool)\n")
		if anyServiceHasIdempotency(services) {
			b.WriteString("\treg.Idempotency = repoSystem\n")
		}
		if anyServiceHasOutbox(services) {
			b.WriteString("\treg.Outbox = repoSystem\n")
		}
		if needsState {
			b.WriteString("\treg.StateStore = repoSystem\n")
			b.WriteString("\tif cfg.RedisAddr != \"\" {\n")
			b.WriteString("\t\treg.StateStore = redistore.New(redisclient.NewClient(cfg.RedisAddr))\n")
			b.WriteString("\t}\n")
		}
	}
	if ctx.AuthService != "" && ctx.AuthRefreshStore != "" {
		switch ctx.AuthRefreshStore {
		case "memory":
			b.WriteString("\treg.RefreshStore = authstore.NewMemoryStore()\n")
		case "redis":
			b.WriteString("\treg.RefreshStore = authredis.NewStore(redisClient)\n")
		case "postgres":
			b.WriteString("\treg.RefreshStore = authpg.NewStore(pgPool)\n")
		case "hybrid":
			b.WriteString("\treg.RefreshStore = authhybrid.NewStore(authpg.NewStore(pgPool), authredis.NewStore(redisClient))\n")
		default:
			b.WriteString("\treg.RefreshStore = nil\n")
		}
	}
	if anyServiceNeedsTx(services) {
		b.WriteString("\treg.TxManager = postgres.NewTxManager(pgPool)\n")
	}
	if needsPolicy {
		b.WriteString("\treg.PolicyEngine = policy.NewEngine()\n")
	}
	b.WriteString("\treg.StateStore = effectmw.WrapStateStore(reg.StateStore, reg.Runtime.Chain(\"state\"))\n")
	b.WriteString("\treturn reg, nil\n")
	b.WriteString("}\n\n")

	b.WriteString("func NewTestEffectRegistry(publisher port.Publisher, storage port.FileStorage, stateStore port.StateStore) *EffectRegistry {\n")
	b.WriteString("\treg := &EffectRegistry{\n")
	b.WriteString("\t\tPublisher: publisher,\n")
	b.WriteString("\t\tStorage: storage,\n")
	b.WriteString("\t\tStateStore: stateStore,\n")
	b.WriteString("\t\tRuntime: EffectProfile{Handlers: " + renderEffectHandlerMap(handlers) + ", Middleware: " + renderEffectMiddlewareMap(middleware) + "},\n")
	b.WriteString("\t\tTest: EffectProfile{Handlers: " + renderEffectHandlerMap(testHandlers) + ", Middleware: " + renderEffectMiddlewareMap(middleware) + "},\n")
	b.WriteString("\t}\n")
	b.WriteString("\treg.Publisher = effectmw.WrapPublisher(reg.Publisher, reg.Test.Chain(\"events\"))\n")
	b.WriteString("\treg.Storage = effectmw.WrapFileStorage(reg.Storage, reg.Test.Chain(\"storage\"))\n")
	b.WriteString("\treg.StateStore = effectmw.WrapStateStore(reg.StateStore, reg.Test.Chain(\"state\"))\n")
	b.WriteString("\treturn reg\n")
	b.WriteString("}\n")
	return b.String()
}

func collectEffectRegistryRepoEntities(services []normalizer.Service, entities []normalizer.Entity) []string {
	seen := map[string]bool{}
	var out []string
	for _, svc := range services {
		for _, name := range serviceImplRepoEntities(svc, entities) {
			if seen[name] {
				continue
			}
			seen[name] = true
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

func entityStorageByName(entities []normalizer.Entity, name string) string {
	for _, ent := range entities {
		if ent.Name != name {
			continue
		}
		if ent.Metadata != nil {
			if storage, ok := ent.Metadata["storage"].(string); ok && strings.TrimSpace(storage) != "" {
				return strings.TrimSpace(storage)
			}
		}
		return "sql"
	}
	return "sql"
}

func hasEntityByName(entities []normalizer.Entity, name string) bool {
	for _, ent := range entities {
		if strings.EqualFold(ent.Name, name) {
			return true
		}
	}
	return false
}

func anyServiceNeedsTx(services []normalizer.Service) bool {
	for _, svc := range services {
		if serviceImplNeedsTx(svc) {
			return true
		}
	}
	return false
}

func anyServiceHasStorageActions(services []normalizer.Service) bool {
	for _, svc := range services {
		if svc.RequiresS3 || serviceImplHasStorageActions(svc) {
			return true
		}
	}
	return false
}

func anyServiceHasPolicyActions(services []normalizer.Service) bool {
	for _, svc := range services {
		if serviceImplHasPolicyActions(svc) {
			return true
		}
	}
	return false
}

func anyServiceHasStateActions(services []normalizer.Service) bool {
	for _, svc := range services {
		if serviceImplHasStateActions(svc) {
			return true
		}
	}
	return false
}

func anyServiceHasIdempotency(services []normalizer.Service) bool {
	for _, svc := range services {
		if serviceImplHasIdempotency(svc) {
			return true
		}
	}
	return false
}

func anyServiceHasOutbox(services []normalizer.Service) bool {
	for _, svc := range services {
		if serviceImplHasOutbox(svc) {
			return true
		}
	}
	return false
}

func anyServiceHasIdempotencyOrOutbox(services []normalizer.Service) bool {
	return anyServiceHasIdempotency(services) || anyServiceHasOutbox(services)
}

func renderEffectHandlerMap(def *normalizer.EffectHandlersDef) string {
	if def == nil || len(def.Bindings) == 0 {
		return "map[string]EffectHandler{}"
	}
	keys := make([]string, 0, len(def.Bindings))
	for k := range def.Bindings {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("map[string]EffectHandler{")
	for i, kind := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		item := def.Bindings[kind]
		b.WriteString(strconv.Quote(kind))
		b.WriteString(": {")
		b.WriteString("Kind: " + strconv.Quote(item.Kind))
		b.WriteString(", Driver: " + strconv.Quote(item.Driver))
		b.WriteString(", Provider: " + strconv.Quote(item.Provider))
		b.WriteString(", Options: " + renderAny(item.Options))
		b.WriteString("}")
	}
	b.WriteString("}")
	return b.String()
}

func renderEffectMiddlewareMap(def *normalizer.EffectMiddlewareCatalogDef) string {
	if def == nil || len(def.Chains) == 0 {
		return "map[string][]effectmw.EffectMiddleware{}"
	}
	keys := make([]string, 0, len(def.Chains))
	for k := range def.Chains {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("map[string][]effectmw.EffectMiddleware{")
	for i, kind := range keys {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(kind))
		b.WriteString(": {")
		for j, item := range def.Chains[kind] {
			if j > 0 {
				b.WriteString(", ")
			}
			b.WriteString("{")
			b.WriteString("Type: " + strconv.Quote(item.Type))
			b.WriteString(", Attempts: " + strconv.Itoa(item.Attempts))
			b.WriteString(", Backoff: " + strconv.Quote(item.Backoff))
			b.WriteString(", On: " + renderIntSlice(item.On))
			b.WriteString(", TTL: " + strconv.Quote(item.TTL))
			b.WriteString(", Key: " + strconv.Quote(item.Key))
			b.WriteString(", Duration: " + strconv.Quote(item.Duration))
			b.WriteString(", Level: " + strconv.Quote(item.Level))
			b.WriteString(", Options: " + renderAny(item.Options))
			b.WriteString("}")
		}
		b.WriteString("}")
	}
	b.WriteString("}")
	return b.String()
}

func renderIntSlice(items []int) string {
	if len(items) == 0 {
		return "nil"
	}
	var b strings.Builder
	b.WriteString("[]int{")
	for i, item := range items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Itoa(item))
	}
	b.WriteString("}")
	return b.String()
}

func renderAny(v any) string {
	switch x := v.(type) {
	case nil:
		return "nil"
	case string:
		return strconv.Quote(x)
	case bool:
		if x {
			return "true"
		}
		return "false"
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	case []int:
		return renderIntSlice(x)
	case []string:
		var b strings.Builder
		b.WriteString("[]string{")
		for i, item := range x {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(item))
		}
		b.WriteString("}")
		return b.String()
	case []any:
		var b strings.Builder
		b.WriteString("[]any{")
		for i, item := range x {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(renderAny(item))
		}
		b.WriteString("}")
		return b.String()
	case map[string]any:
		if len(x) == 0 {
			return "map[string]any{}"
		}
		keys := make([]string, 0, len(x))
		for k := range x {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var b strings.Builder
		b.WriteString("map[string]any{")
		for i, key := range keys {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(key))
			b.WriteString(": ")
			b.WriteString(renderAny(x[key]))
		}
		b.WriteString("}")
		return b.String()
	default:
		return strconv.Quote(fmt.Sprintf("%v", x))
	}
}
