package emitter

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/strogmv/ang/angir/normalizer"
)

func TestBuildTableData_SkipsAuthInjectedFields(t *testing.T) {
	t.Parallel()

	method := normalizer.Method{
		Name: "ListAllChatsForTheCurrentUser",
		Input: normalizer.Entity{
			Name: "ListAllChatsForTheCurrentUserRequest",
			Fields: []normalizer.Field{
				{Name: "CompanyID", Type: "string"},
				{Name: "UserID", Type: "string"},
				{Name: "Limit", Type: "int"},
				{Name: "Offset", Type: "int"},
			},
		},
	}
	endpoints := []normalizer.Endpoint{
		{
			ServiceName: "Chat",
			RPC:         "ListAllChatsForTheCurrentUser",
			AuthInject:  []string{"companyId", "userId"},
		},
	}

	got := buildTableData("Chat", method, nil, endpoints)

	if len(got.ExtraProps) != 0 {
		t.Fatalf("expected auth-injected fields to be omitted from table props, got %#v", got.ExtraProps)
	}
	if len(got.QueryParams) != 2 {
		t.Fatalf("expected only pagination params to remain, got %#v", got.QueryParams)
	}
	if got.QueryParams[0].Name != "limit" || got.QueryParams[1].Name != "offset" {
		t.Fatalf("expected only limit/offset query params, got %#v", got.QueryParams)
	}
}

func TestBuildTableData_ColumnPickerFromCUE(t *testing.T) {
	t.Parallel()

	method := normalizer.Method{
		Name: "ListB2BPartners",
		Attributes: []normalizer.Attribute{
			{Name: "table", Args: map[string]any{"hidden": "id,priceListId", "storageKey": "b2b.partners"}},
		},
		Output: normalizer.Entity{
			Name: "ListB2BPartnersResponse",
			Fields: []normalizer.Field{
				{Name: "data", Type: "[]ListB2BPartnersData", IsList: true, ItemFields: []normalizer.Field{
					{Name: "id", Type: "string"},
					{Name: "targetCompanyName", Type: "string"},
					{Name: "priceListID", Type: "string"},
					{Name: "roundingMode", Type: "string", UI: &normalizer.UIHints{Hidden: true}},
				}},
			},
		},
	}

	got := buildTableData("B2B", method, nil, nil)

	if !got.ColumnPicker {
		t.Fatalf("expected column picker enabled by default")
	}
	if got.StorageKey != "b2b.partners" {
		t.Fatalf("expected storageKey from @table, got %q", got.StorageKey)
	}
	hidden := map[string]bool{}
	for _, col := range got.Columns {
		hidden[col.Field] = col.Hidden
	}
	for field, want := range map[string]bool{"id": true, "targetCompanyName": false, "priceListId": true, "roundingMode": true} {
		if hidden[field] != want {
			t.Fatalf("column %q hidden=%v, want %v (columns: %#v)", field, hidden[field], want, got.Columns)
		}
	}

	optOut := normalizer.Method{
		Name:       "ListThings",
		Attributes: []normalizer.Attribute{{Name: "table", Args: map[string]any{"picker": "false"}}},
	}
	if buildTableData("Svc", optOut, nil, nil).ColumnPicker {
		t.Fatalf("expected @table(picker=false) to disable the column picker")
	}
	if buildTableData("Svc", normalizer.Method{Name: "ListThings"}, nil, nil).StorageKey != "Thing" {
		t.Fatalf("expected storage key to default to the table name")
	}
	if got.HasTotal {
		t.Fatalf("expected HasTotal=false without a total output field")
	}
	withTotal := normalizer.Method{Name: "ListThings", Output: normalizer.Entity{Fields: []normalizer.Field{{Name: "data", Type: "[]X", IsList: true}, {Name: "total", Type: "int"}}}}
	if !buildTableData("Svc", withTotal, nil, nil).HasTotal {
		t.Fatalf("expected HasTotal=true when the response has total")
	}
}

func TestHasFrontendListEndpointRequiresGETEndpoint(t *testing.T) {
	t.Parallel()

	endpoints := []normalizer.Endpoint{
		{ServiceName: "Tender", RPC: "ListTenders", Method: "GET"},
		{ServiceName: "Tender", RPC: "ListCategoriesAI", Method: ""},
	}

	if !hasFrontendListEndpoint("Tender", "ListTenders", endpoints) {
		t.Fatal("expected GET list endpoint to generate a frontend table")
	}
	if hasFrontendListEndpoint("Tender", "ListCategoriesAI", endpoints) {
		t.Fatal("did not expect non-HTTP list method to generate a frontend table")
	}
}

func TestRemoveStaleGeneratedComponents(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	files := map[string]string{
		"CurrentTable.tsx": "// AUTO-GENERATED by ANG (Architectural Normalized Generator)\n",
		"StaleTable.tsx":   "// Generated by ANG. Do not edit.\n",
		"CustomTable.tsx":  "export function CustomTable() { return null; }\n",
	}
	for name, contents := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(contents), 0644); err != nil {
			t.Fatalf("write %s: %v", name, err)
		}
	}

	if err := removeStaleGeneratedComponents(dir, map[string]struct{}{"CurrentTable.tsx": {}}); err != nil {
		t.Fatalf("remove stale components: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "StaleTable.tsx")); !os.IsNotExist(err) {
		t.Fatalf("expected stale generated component to be removed, stat error: %v", err)
	}
	for _, name := range []string{"CurrentTable.tsx", "CustomTable.tsx"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Fatalf("expected %s to remain: %v", name, err)
		}
	}
}
