package emitter

import (
	"os"
	"path/filepath"
)

// emitBaseUITablesLayer writes the table UI registry consumed by generated
// tables. The host application can swap the pagination component once at
// bootstrap (registerTablePagination) instead of editing generated files.
func (e *Emitter) emitBaseUITablesLayer() error {
	dir := filepath.Join(e.FrontendDir, "@ui", "tables")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	const indexTSX = `// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Table UI layer shared by every generated table:
//   - registerTablePagination / TablePagination  — page control (host-swappable)
//   - registerTableLabels / useTableLabels       — column & action labels (i18n)
//   - useTableColumnVisibility                   — CUE defaults + localStorage
//   - TableActionsHeader                         — actions header + column picker
//   - TableFooter                                — footer slot with pagination
//   - registerTableSlots / getTableSlots         — extra DataGrid slots (baseCheckbox, ...)
//   - formatTableDate / formatTableCurrency      — cell formatting shared by all tables
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================
import type { ComponentType } from 'react';
import { useState, useSyncExternalStore } from 'react';
import { Box, IconButton, Pagination, Tooltip } from '@mui/material';
import {
  ColumnsPanelTrigger,
  gridPageCountSelector,
  gridPageSelector,
  useGridApiContext,
  useGridSelector,
  type GridColumnVisibilityModel,
  type GridSlotsComponent,
} from '@mui/x-data-grid';
import { ViewColumn as ViewColumnIcon } from '@mui/icons-material';
import dayjs from 'dayjs';

// ---------------------------------------------------------------------------
// Cell formatting
// ---------------------------------------------------------------------------

/** Empty placeholder for cells with no value. */
export const TABLE_EMPTY_CELL = '—';

/**
 * Which locale a cell is written in.
 *
 * Dates were formatted with a hard-coded DD.MM.YYYY and money with the
 * browser's own locale, so a German reader on an English Chrome was shown
 * 1,234.56 where their accountant reads 1.234,56 — a thousands separator that
 * reads as a decimal point is not a cosmetic difference. Neither followed the
 * language the reader had actually chosen, because the SDK cannot see the
 * app's i18n. The app registers it; without one, the browser's locale is used
 * exactly as before.
 */
let localeSource: () => string = () => {
  if (typeof navigator !== 'undefined' && navigator.language) return navigator.language;
  return 'en';
};

export function registerTableLocale(source: () => string) {
  localeSource = source;
  notifyLabelsChanged();
}

function tableLocale(): string {
  try {
    return localeSource() || 'en';
  } catch {
    return 'en';
  }
}

/** Date cell: never renders "Invalid Date" for empty or unparsable values. */
export function formatTableDate(value: unknown, withTime = true): string {
  if (value === null || value === undefined || value === '') return TABLE_EMPTY_CELL;
  const parsed = dayjs(value as string | number | Date);
  if (!parsed.isValid()) return TABLE_EMPTY_CELL;
  try {
    return new Intl.DateTimeFormat(tableLocale(), {
      dateStyle: 'short',
      ...(withTime ? { timeStyle: 'short' } : {}),
    }).format(parsed.toDate());
  } catch {
    return parsed.format(withTime ? 'DD.MM.YYYY HH:mm' : 'DD.MM.YYYY');
  }
}

/**
 * Money cell. The currency comes from the row (currencyCode) because a table
 * can mix currencies; without one the value is rendered as a plain number
 * instead of guessing a symbol.
 */
export function formatTableCurrency(value: unknown, currencyCode?: unknown): string {
  if (value === null || value === undefined || value === '') return TABLE_EMPTY_CELL;
  const amount = typeof value === 'number' ? value : Number(value);
  if (!Number.isFinite(amount)) return TABLE_EMPTY_CELL;
  const code = typeof currencyCode === 'string' ? currencyCode.trim().toUpperCase() : '';
  const locale = tableLocale();
  // Two decimals even without a currency: a money column that prints 1.234,5
  // in one row and 1.234,50 in the next is not a column anyone adds up.
  const plain = { minimumFractionDigits: 2, maximumFractionDigits: 2 };
  if (code.length !== 3) return new Intl.NumberFormat(locale, plain).format(amount);
  try {
    return new Intl.NumberFormat(locale, { style: 'currency', currency: code }).format(amount);
  } catch {
    return new Intl.NumberFormat(locale, plain).format(amount) + ' ' + code;
  }
}

/**
 * Enum cell. A status column printed whatever the API sent — "pending",
 * "revoked", "markup" — in every language, so a table in Russian told the
 * reader their invitation was "pending". The value is a contract constant, so
 * it stays what it is in the data and only what is shown goes through here.
 * Without a registered formatter the raw value is used, exactly as before.
 */
export type TableValueFormatter = (field: string, value: string) => string;

const defaultValueFormatter: TableValueFormatter = (_field, value) => value;

let valueFormatter: TableValueFormatter = defaultValueFormatter;

/** Replace how generated tables render enum values (status, scope, mode...). */
export function registerTableValueFormatter(formatter: TableValueFormatter) {
  valueFormatter = formatter;
  notifyLabelsChanged();
}

export function formatTableValue(field: unknown, value: unknown): string {
  if (value === null || value === undefined || value === '') return TABLE_EMPTY_CELL;
  const raw = String(value);
  const name = typeof field === 'string' ? field : '';
  return valueFormatter(name, raw);
}

// ---------------------------------------------------------------------------
// Column / action labels
// ---------------------------------------------------------------------------

/** Resolves a header text. field is the JSON field name or an action key
 *  such as "actions" / "actions.view"; fallback is the generated label. */
export type TableLabelResolver = (table: string, field: string, fallback: string) => string;

const defaultLabelResolver: TableLabelResolver = (_table, _field, fallback) => fallback;

let labelResolver: TableLabelResolver = defaultLabelResolver;
let labelsVersion = 0;
const labelListeners = new Set<() => void>();
let unsubscribeLanguage: (() => void) | undefined;

function notifyLabelsChanged() {
  labelsVersion += 1;
  labelListeners.forEach((listener) => listener());
}

/**
 * Replace how generated tables resolve column headers. Pass subscribe to
 * re-render tables when the source changes (for example on language switch).
 */
export function registerTableLabels(
  resolver: TableLabelResolver,
  subscribe?: (onChange: () => void) => () => void,
) {
  labelResolver = resolver;
  unsubscribeLanguage?.();
  unsubscribeLanguage = subscribe?.(notifyLabelsChanged);
  notifyLabelsChanged();
}

function subscribeLabels(listener: () => void) {
  labelListeners.add(listener);
  return () => labelListeners.delete(listener);
}

/** Current label resolver; the component re-renders when labels change. */
export function useTableLabels(): TableLabelResolver {
  useSyncExternalStore(subscribeLabels, () => labelsVersion, () => labelsVersion);
  return labelResolver;
}

// ---------------------------------------------------------------------------
// DataGrid slots (host-provided base components: baseCheckbox, baseButton, ...)
// ---------------------------------------------------------------------------

export type TableSlots = Partial<GridSlotsComponent>;

let registeredSlots: TableSlots = {};

/** Merge DataGrid slots into every generated table (e.g. a branded baseCheckbox). */
export function registerTableSlots(slots: TableSlots) {
  registeredSlots = { ...registeredSlots, ...slots };
}

export function getTableSlots(): TableSlots {
  return registeredSlots;
}

// ---------------------------------------------------------------------------
// Pagination
// ---------------------------------------------------------------------------

export type TablePaginationProps = {
  /** 1-based current page */
  page: number;
  pageCount: number;
  onChange: (page: number) => void;
};

function DefaultTablePagination({ page, pageCount, onChange }: TablePaginationProps) {
  if (pageCount <= 1) return null;
  return (
    <Pagination
      page={page}
      count={pageCount}
      shape="rounded"
      showLastButton
      onChange={(_event, next) => onChange(next)}
    />
  );
}

let registeredPagination: ComponentType<TablePaginationProps> = DefaultTablePagination;

/** Replace the pagination used by every generated table. */
export function registerTablePagination(component: ComponentType<TablePaginationProps>) {
  registeredPagination = component;
}

export function TablePagination(props: TablePaginationProps) {
  const Component = registeredPagination;
  return <Component {...props} />;
}

/** DataGrid footer slot: pagination only, left-aligned. */
export function TableFooter() {
  const apiRef = useGridApiContext();
  const page = useGridSelector(apiRef, gridPageSelector);
  const pageCount = useGridSelector(apiRef, gridPageCountSelector);
  return (
    <Box sx={{ px: 1, py: 1.5 }}>
      <TablePagination
        page={page + 1}
        pageCount={pageCount}
        onChange={(next) => apiRef.current.setPage(next - 1)}
      />
    </Box>
  );
}

// ---------------------------------------------------------------------------
// Column visibility (CUE defaults + per-user persistence)
// ---------------------------------------------------------------------------

function storageKeyFor(tableKey: string) {
  return 'ang:table:' + tableKey + ':columns';
}

function readStoredVisibility(tableKey: string, defaults: GridColumnVisibilityModel): GridColumnVisibilityModel {
  if (typeof window === 'undefined') return defaults;
  try {
    const raw = window.localStorage.getItem(storageKeyFor(tableKey));
    const parsed: unknown = raw ? JSON.parse(raw) : null;
    if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
      return parsed as GridColumnVisibilityModel;
    }
  } catch {
    // Storage unavailable (private mode, quota, disabled): fall back to defaults.
  }
  return defaults;
}

function persistVisibility(tableKey: string, model: GridColumnVisibilityModel) {
  try {
    window.localStorage.setItem(storageKeyFor(tableKey), JSON.stringify(model));
  } catch {
    // Best effort only; the in-memory model still applies for this session.
  }
}

/**
 * Column visibility for a generated table: defaults come from CUE
 * (@ui(hidden) / @table(hidden=...)), the user's choice persists per table.
 * When the host passes a controlled model the internal state is bypassed.
 */
export function useTableColumnVisibility(
  tableKey: string,
  defaults: GridColumnVisibilityModel,
  controlled?: GridColumnVisibilityModel,
  onControlledChange?: (model: GridColumnVisibilityModel) => void,
) {
  const [stored, setStored] = useState<GridColumnVisibilityModel>(() => readStoredVisibility(tableKey, defaults));
  const model = controlled ?? stored;
  const onChange = (next: GridColumnVisibilityModel) => {
    if (controlled === undefined) {
      setStored(next);
      persistVisibility(tableKey, next);
    }
    onControlledChange?.(next);
  };
  return { model, onChange };
}

// ---------------------------------------------------------------------------
// Actions column header with the column picker
// ---------------------------------------------------------------------------

export type TableActionsHeaderProps = {
  label: string;
  /** Show the column-picker trigger (CUE: @table(picker=false) hides it). */
  picker?: boolean;
};

/** Header of the actions column: label plus the MUI columns-panel trigger,
 *  so the picker lives in the header row instead of a separate toolbar. */
export function TableActionsHeader({ label, picker = true }: TableActionsHeaderProps) {
  const apiRef = useGridApiContext();
  const pickerLabel = String(apiRef.current.getLocaleText('toolbarColumns'));
  return (
    <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 0.5, width: '100%' }}>
      <span>{label}</span>
      {picker && (
        <Tooltip title={pickerLabel}>
          <ColumnsPanelTrigger render={<IconButton size="small" aria-label={pickerLabel} />}>
            <ViewColumnIcon sx={{ fontSize: 20 }} />
          </ColumnsPanelTrigger>
        </Tooltip>
      )}
    </Box>
  );
}
`
	path := filepath.Join(dir, "index.tsx")
	if err := WriteFileIfChanged(path, []byte(indexTSX), 0o644); err != nil {
		return err
	}
	logGenerated("Generated Table UI Layer: %s\n", path)
	return nil
}
