package emitter

import (
	"fmt"
	"os"
	"path/filepath"
)

// emitBaseUITablesLayer writes the table UI registry consumed by generated
// tables. The host application can swap the pagination component once at
// bootstrap (registerTablePagination) instead of editing generated files.
func (e *Emitter) emitBaseUITablesLayer() error {
	dir := filepath.Join(e.FrontendDir, "@ui", "tables")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	const indexTSX = `// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Table UI registry. Generated tables render pagination through
// TablePagination and resolve column headers through useTableLabels; the
// host app may override both once at bootstrap:
//
//   import { registerTablePagination, registerTableLabels } from '@sdk/@ui/tables';
//   registerTablePagination(MyPagination);
//   registerTableLabels((table, field, fallback) => t(...), subscribeToLanguage);
//
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================
import type { ComponentType } from 'react';
import { useSyncExternalStore } from 'react';
import { Pagination } from '@mui/material';

// ---------------------------------------------------------------------------
// Column / action labels
// ---------------------------------------------------------------------------

/** Resolves a header text. 'field' is the JSON field name or an action key
 *  such as "actions", "actions.view"; 'fallback' is the generated label. */
export type TableLabelResolver = (table: string, field: string, fallback: string) => string;

const defaultLabelResolver: TableLabelResolver = (_table, _field, fallback) => fallback;

let labelResolver: TableLabelResolver = defaultLabelResolver;
let labelsVersion = 0;
const labelListeners = new Set<() => void>();
let unsubscribeLanguage: (() => void) | undefined;

function notifyLabelsChanged() {
  labelsVersion += 1;
  labelListeners.forEach((listener) => listener());
}

/**
 * Replace how generated tables resolve column headers. Pass 'subscribe' to
 * re-render tables when the source changes (for example on language switch).
 */
export function registerTableLabels(
  resolver: TableLabelResolver,
  subscribe?: (onChange: () => void) => () => void,
) {
  labelResolver = resolver;
  unsubscribeLanguage?.();
  unsubscribeLanguage = subscribe?.(notifyLabelsChanged);
  notifyLabelsChanged();
}

function subscribeLabels(listener: () => void) {
  labelListeners.add(listener);
  return () => labelListeners.delete(listener);
}

/** Current label resolver; the component re-renders when labels change. */
export function useTableLabels(): TableLabelResolver {
  useSyncExternalStore(subscribeLabels, () => labelsVersion, () => labelsVersion);
  return labelResolver;
}

// ---------------------------------------------------------------------------
// Pagination
// ---------------------------------------------------------------------------

export type TablePaginationProps = {
  /** 1-based current page */
  page: number;
  pageCount: number;
  onChange: (page: number) => void;
};

function DefaultTablePagination({ page, pageCount, onChange }: TablePaginationProps) {
  if (pageCount <= 1) return null;
  return (
    <Pagination
      page={page}
      count={pageCount}
      shape="rounded"
      showLastButton
      onChange={(_event, next) => onChange(next)}
    />
  );
}

let registeredPagination: ComponentType<TablePaginationProps> = DefaultTablePagination;

/** Replace the pagination used by every generated table. */
export function registerTablePagination(component: ComponentType<TablePaginationProps>) {
  registeredPagination = component;
}

export function TablePagination(props: TablePaginationProps) {
  const Component = registeredPagination;
  return <Component {...props} />;
}
`
	path := filepath.Join(dir, "index.tsx")
	if err := WriteFileIfChanged(path, []byte(indexTSX), 0o644); err != nil {
		return err
	}
	fmt.Printf("Generated Table UI Layer: %s\n", path)
	return nil
}
