package emitter

import (
	"bytes"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/strogmv/ang/compiler/ir"
)

func (e *Emitter) EmitGRPCProto(schema *ir.Schema) error {
	if schema == nil {
		schema = &ir.Schema{}
	}

	module := strings.TrimSpace(e.GoModule)
	if module == "" {
		module = "example.com/ang"
	}

	services := append([]ir.Service(nil), schema.Services...)
	sort.Slice(services, func(i, j int) bool {
		return strings.ToLower(services[i].Name) < strings.ToLower(services[j].Name)
	})

	type grpcMessage struct {
		Name   string
		Fields []ir.Field
	}
	messages := make(map[string]grpcMessage)
	messageOrder := make([]string, 0, len(services)*2)

	addMessage := func(name string, ent *ir.Entity) {
		name = strings.TrimSpace(name)
		if name == "" {
			return
		}
		if _, exists := messages[name]; exists {
			return
		}
		msg := grpcMessage{Name: name}
		if ent != nil {
			msg.Fields = append(msg.Fields, ent.Fields...)
		}
		messages[name] = msg
		messageOrder = append(messageOrder, name)
	}

	var b strings.Builder
	b.WriteString("syntax = \"proto3\";\n\n")
	b.WriteString("package ang.v1;\n\n")
	b.WriteString(fmt.Sprintf("option go_package = %q;\n\n", module+"/internal/transport/grpc/pb;pb"))

	for _, svc := range services {
		methods := append([]ir.Method(nil), svc.Methods...)
		sort.Slice(methods, func(i, j int) bool {
			return strings.ToLower(methods[i].Name) < strings.ToLower(methods[j].Name)
		})
		b.WriteString(fmt.Sprintf("service %sService {\n", ExportName(svc.Name)))
		for _, m := range methods {
			reqName := grpcMethodMessageName(svc.Name, m, true)
			respName := grpcMethodMessageName(svc.Name, m, false)
			addMessage(reqName, m.Input)
			addMessage(respName, m.Output)
			b.WriteString(fmt.Sprintf("  rpc %s (%s) returns (%s);\n", ExportName(m.Name), reqName, respName))
		}
		b.WriteString("}\n\n")
	}

	for _, name := range messageOrder {
		msg := messages[name]
		b.WriteString(fmt.Sprintf("message %s {\n", msg.Name))
		usedFieldNames := map[string]int{}
		fieldNo := 1
		for _, f := range msg.Fields {
			fieldName := grpcProtoFieldName(f.Name)
			if fieldName == "" {
				fieldName = fmt.Sprintf("field_%d", fieldNo)
			}
			if n := usedFieldNames[fieldName]; n > 0 {
				fieldName = fmt.Sprintf("%s_%d", fieldName, n+1)
			}
			usedFieldNames[fieldName]++
			b.WriteString(fmt.Sprintf("  %s %s = %d;\n", grpcProtoType(f.Type), fieldName, fieldNo))
			fieldNo++
		}
		b.WriteString("}\n\n")
	}

	path := filepath.Join(e.OutputDir, "api", "grpc", "service.proto")
	if err := WriteFileIfChanged(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write grpc proto: %w", err)
	}
	fmt.Printf("Generated gRPC Proto: %s\n", path)
	return nil
}

func (e *Emitter) EmitGRPCTransport(schema *ir.Schema) error {
	if schema == nil {
		schema = &ir.Schema{}
	}

	services := append([]ir.Service(nil), schema.Services...)
	sort.Slice(services, func(i, j int) bool {
		return strings.ToLower(services[i].Name) < strings.ToLower(services[j].Name)
	})

	serviceNames := make([]string, 0, len(services))
	for _, svc := range services {
		name := strings.TrimSpace(ExportName(svc.Name))
		if name == "" {
			continue
		}
		serviceNames = append(serviceNames, name)
	}

	var goBuf strings.Builder
	goBuf.WriteString("package grpc\n\n")
	goBuf.WriteString("import \"context\"\n\n")
	goBuf.WriteString("// Server is a lightweight gRPC transport scaffold generated by ANG.\n")
	goBuf.WriteString("// It intentionally avoids grpc-go hard dependency and is meant to be wired manually.\n")
	goBuf.WriteString("type Server struct {\n")
	goBuf.WriteString("\tservices []string\n")
	goBuf.WriteString("}\n\n")
	goBuf.WriteString("func NewServer() *Server {\n")
	goBuf.WriteString("\treturn &Server{services: []string{")
	for i, name := range serviceNames {
		if i > 0 {
			goBuf.WriteString(", ")
		}
		goBuf.WriteString(fmt.Sprintf("%q", name))
	}
	goBuf.WriteString("}}\n")
	goBuf.WriteString("}\n\n")
	goBuf.WriteString("func (s *Server) ServiceNames() []string {\n")
	goBuf.WriteString("\tout := make([]string, len(s.services))\n")
	goBuf.WriteString("\tcopy(out, s.services)\n")
	goBuf.WriteString("\treturn out\n")
	goBuf.WriteString("}\n\n")
	goBuf.WriteString("// MethodHandler is a generic method invocation bridge for future protobuf wiring.\n")
	goBuf.WriteString("type MethodHandler interface {\n")
	goBuf.WriteString("\tInvoke(ctx context.Context, service, method string, req any) (any, error)\n")
	goBuf.WriteString("}\n\n")
	goBuf.WriteString("func (s *Server) Register(_ MethodHandler) {\n")
	goBuf.WriteString("\t// TODO: run protoc, import generated pb package, register services on grpc.Server.\n")
	goBuf.WriteString("}\n")

	goPath := filepath.Join(e.OutputDir, "internal", "transport", "grpc", "server.go")
	if err := WriteFileIfChanged(goPath, []byte(goBuf.String()), 0o644); err != nil {
		return fmt.Errorf("write grpc server scaffold: %w", err)
	}

	var readme bytes.Buffer
	readme.WriteString("# gRPC Transport Scaffold\n\n")
	readme.WriteString("ANG generated a minimal gRPC scaffold.\n\n")
	readme.WriteString("- `api/grpc/service.proto` contains service and message contracts.\n")
	readme.WriteString("- `internal/transport/grpc/server.go` is a manual wiring placeholder.\n\n")
	readme.WriteString("Next steps:\n")
	readme.WriteString("1. Generate protobuf Go code (`protoc --go_out --go-grpc_out ...`).\n")
	readme.WriteString("2. Add `google.golang.org/grpc` dependency.\n")
	readme.WriteString("3. Wire generated handlers into runtime startup.\n")

	readmePath := filepath.Join(e.OutputDir, "internal", "transport", "grpc", "README.md")
	if err := WriteFileIfChanged(readmePath, readme.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write grpc readme: %w", err)
	}

	fmt.Printf("Generated gRPC Transport: %s\n", filepath.Dir(goPath))
	return nil
}

func grpcMethodMessageName(serviceName string, method ir.Method, isInput bool) string {
	if isInput && method.Input != nil && strings.TrimSpace(method.Input.Name) != "" {
		return ExportName(method.Input.Name)
	}
	if !isInput && method.Output != nil && strings.TrimSpace(method.Output.Name) != "" {
		return ExportName(method.Output.Name)
	}
	suffix := "Request"
	if !isInput {
		suffix = "Response"
	}
	return ExportName(serviceName) + ExportName(method.Name) + suffix
}

func grpcProtoFieldName(name string) string {
	s := strings.TrimSpace(ToSnakeCase(name))
	if s == "" {
		return ""
	}
	var out strings.Builder
	prevUnderscore := false
	for _, r := range s {
		ok := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_'
		if !ok {
			r = '_'
		}
		if r == '_' {
			if prevUnderscore {
				continue
			}
			prevUnderscore = true
		} else {
			prevUnderscore = false
		}
		out.WriteRune(r)
	}
	res := strings.Trim(out.String(), "_")
	if res == "" {
		return ""
	}
	if res[0] >= '0' && res[0] <= '9' {
		return "f_" + res
	}
	return res
}

func grpcProtoType(t ir.TypeRef) string {
	switch t.Kind {
	case ir.KindList:
		if t.ItemType == nil {
			return "repeated string"
		}
		item := grpcProtoType(*t.ItemType)
		if strings.HasPrefix(item, "map<") {
			item = "string"
		}
		return "repeated " + item
	case ir.KindMap:
		val := "string"
		if t.ItemType != nil {
			val = grpcProtoType(*t.ItemType)
			if strings.HasPrefix(val, "repeated ") || strings.HasPrefix(val, "map<") {
				val = "string"
			}
		}
		return "map<string, " + val + ">"
	case ir.KindInt:
		return "int32"
	case ir.KindInt64:
		return "int64"
	case ir.KindFloat:
		return "double"
	case ir.KindBool:
		return "bool"
	case ir.KindString, ir.KindTime, ir.KindUUID, ir.KindJSON, ir.KindAny, ir.KindFile, ir.KindEnum, ir.KindEntity:
		return "string"
	default:
		return "string"
	}
}
