package emitter

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type portInterfaceSpec struct {
	Name    string
	Methods []portMethodSpec
}

type portMethodSpec struct {
	Name    string
	Params  []portFieldSpec
	Results []portFieldSpec
}

type portFieldSpec struct {
	Name string
	Type string
}

// EmitPortMocks generates internal/adapter/mock/*.gen.go by parsing generated
// interfaces from internal/port.
func (e *Emitter) EmitPortMocks() error {
	specs, importPaths, err := readPortInterfaces(e.outDir("internal", "port"))
	if err != nil {
		return err
	}
	targetDir := e.outDir("internal", "adapter", "mock")
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	keep := make(map[string]struct{}, len(specs))
	for _, spec := range specs {
		src, err := renderPortMockSource(strings.TrimSpace(e.GoModule), spec, importPaths)
		if err != nil {
			return err
		}
		filename := ToSnakeCase(spec.Name) + ".gen.go"
		keep[filename] = struct{}{}
		path := filepath.Join(targetDir, filename)
		formatted, err := formatGoStrict([]byte(src), "internal/adapter/mock/"+filename)
		if err != nil {
			return err
		}
		if err := WriteFileIfChanged(path, formatted, 0o644); err != nil {
			return err
		}
	}
	return pruneGeneratedFiles(
		targetDir,
		keep,
		func(name string) bool { return strings.HasSuffix(name, ".gen.go") },
		func(path string) bool { return fileContainsAny(path, "Code generated by ANG", "package mock") },
	)
}

func readPortInterfaces(dir string) ([]portInterfaceSpec, map[string]string, error) {
	if _, err := os.Stat(dir); err != nil {
		if os.IsNotExist(err) {
			return nil, map[string]string{}, nil
		}
		return nil, nil, err
	}
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		name := fi.Name()
		if strings.HasSuffix(name, "_test.go") {
			return false
		}
		return strings.HasSuffix(name, ".go")
	}, parser.ParseComments)
	if err != nil {
		return nil, nil, err
	}
	pkg := pkgs["port"]
	if pkg == nil {
		return nil, map[string]string{}, nil
	}

	localTypes := map[string]struct{}{}
	importPaths := map[string]string{}
	fileOrder := make([]string, 0, len(pkg.Files))
	for name := range pkg.Files {
		fileOrder = append(fileOrder, name)
	}
	sort.Strings(fileOrder)

	for _, name := range fileOrder {
		file := pkg.Files[name]
		for _, imp := range file.Imports {
			path, _ := strconv.Unquote(imp.Path.Value)
			alias := ""
			if imp.Name != nil {
				alias = imp.Name.Name
			}
			if alias == "" {
				parts := strings.Split(path, "/")
				alias = parts[len(parts)-1]
			}
			importPaths[alias] = path
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				localTypes[typeSpec.Name.Name] = struct{}{}
			}
		}
	}

	var out []portInterfaceSpec
	for _, name := range fileOrder {
		file := pkg.Files[name]
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				iface, ok := typeSpec.Type.(*ast.InterfaceType)
				if !ok {
					continue
				}
				if len(iface.Methods.List) == 0 {
					continue
				}
				item := portInterfaceSpec{Name: typeSpec.Name.Name}
				for _, method := range iface.Methods.List {
					if len(method.Names) == 0 {
						continue
					}
					fn, ok := method.Type.(*ast.FuncType)
					if !ok {
						continue
					}
					item.Methods = append(item.Methods, portMethodSpec{
						Name:    method.Names[0].Name,
						Params:  collectPortFields(fn.Params, localTypes),
						Results: collectPortFields(fn.Results, localTypes),
					})
				}
				out = append(out, item)
			}
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out, importPaths, nil
}

func collectPortFields(list *ast.FieldList, localTypes map[string]struct{}) []portFieldSpec {
	if list == nil || len(list.List) == 0 {
		return nil
	}
	var out []portFieldSpec
	argIndex := 1
	for _, field := range list.List {
		typeExpr := qualifyPortExpr(field.Type, localTypes)
		if len(field.Names) == 0 {
			out = append(out, portFieldSpec{
				Name: fmt.Sprintf("arg%d", argIndex),
				Type: typeExpr,
			})
			argIndex++
			continue
		}
		for _, name := range field.Names {
			out = append(out, portFieldSpec{Name: name.Name, Type: typeExpr})
			argIndex++
		}
	}
	return out
}

func qualifyPortExpr(expr ast.Expr, localTypes map[string]struct{}) string {
	switch x := expr.(type) {
	case *ast.Ident:
		if isBuiltinGoType(x.Name) {
			return x.Name
		}
		if _, ok := localTypes[x.Name]; ok {
			return "port." + x.Name
		}
		return x.Name
	case *ast.StarExpr:
		return "*" + qualifyPortExpr(x.X, localTypes)
	case *ast.ArrayType:
		if x.Len == nil {
			return "[]" + qualifyPortExpr(x.Elt, localTypes)
		}
		return fmt.Sprintf("[%s]%s", qualifyPortExpr(x.Len, localTypes), qualifyPortExpr(x.Elt, localTypes))
	case *ast.SelectorExpr:
		return qualifyPortExpr(x.X, localTypes) + "." + x.Sel.Name
	case *ast.MapType:
		return "map[" + qualifyPortExpr(x.Key, localTypes) + "]" + qualifyPortExpr(x.Value, localTypes)
	case *ast.InterfaceType:
		if x.Methods == nil || len(x.Methods.List) == 0 {
			return "any"
		}
	case *ast.FuncType:
		var params []string
		for _, item := range collectPortFields(x.Params, localTypes) {
			params = append(params, item.Name+" "+item.Type)
		}
		var results []string
		for _, item := range collectPortFields(x.Results, localTypes) {
			results = append(results, item.Type)
		}
		if len(results) == 0 {
			return "func(" + strings.Join(params, ", ") + ")"
		}
		if len(results) == 1 {
			return "func(" + strings.Join(params, ", ") + ") " + results[0]
		}
		return "func(" + strings.Join(params, ", ") + ") (" + strings.Join(results, ", ") + ")"
	case *ast.ChanType:
		switch x.Dir {
		case ast.SEND:
			return "chan<- " + qualifyPortExpr(x.Value, localTypes)
		case ast.RECV:
			return "<-chan " + qualifyPortExpr(x.Value, localTypes)
		default:
			return "chan " + qualifyPortExpr(x.Value, localTypes)
		}
	case *ast.Ellipsis:
		return "..." + qualifyPortExpr(x.Elt, localTypes)
	}

	var buf bytes.Buffer
	_ = printer.Fprint(&buf, token.NewFileSet(), expr)
	return buf.String()
}

func renderPortMockSource(goModule string, spec portInterfaceSpec, importPaths map[string]string) (string, error) {
	importSet := map[string]string{
		"port": filepath.ToSlash(strings.TrimSpace(goModule) + "/internal/port"),
	}
	for _, m := range spec.Methods {
		for _, field := range append(append([]portFieldSpec{}, m.Params...), m.Results...) {
			for _, alias := range collectTypeAliases(field.Type) {
				if alias == "port" {
					continue
				}
				if path, ok := importPaths[alias]; ok {
					importSet[alias] = path
				}
			}
		}
	}

	aliases := make([]string, 0, len(importSet))
	for alias := range importSet {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)

	var b strings.Builder
	b.WriteString("// Code generated by ANG. DO NOT EDIT.\n")
	b.WriteString("package mock\n\n")
	if len(aliases) > 0 {
		b.WriteString("import (\n")
		for _, alias := range aliases {
			path := importSet[alias]
			if alias == filepath.Base(path) {
				b.WriteString("\t" + strconv.Quote(path) + "\n")
			} else {
				b.WriteString("\t" + alias + " " + strconv.Quote(path) + "\n")
			}
		}
		b.WriteString(")\n\n")
	}

	mockType := "Mock" + spec.Name
	b.WriteString("type " + mockType + " struct {\n")
	for _, method := range spec.Methods {
		b.WriteString("\t" + method.Name + "Func func(" + renderFieldSignature(method.Params) + ")" + renderResultSignature(method.Results) + "\n")
		b.WriteString("\t" + method.Name + "Calls []" + mockType + method.Name + "Call\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("var _ port." + spec.Name + " = (*" + mockType + ")(nil)\n\n")
	b.WriteString("func New" + spec.Name + "() *" + mockType + " {\n")
	b.WriteString("\treturn &" + mockType + "{}\n")
	b.WriteString("}\n\n")
	for _, method := range spec.Methods {
		callType := mockType + method.Name + "Call"
		b.WriteString("type " + callType + " struct {\n")
		if len(method.Params) == 0 {
			b.WriteString("\t_ struct{}\n")
		}
		for _, field := range method.Params {
			b.WriteString("\t" + ExportName(field.Name) + " " + field.Type + "\n")
		}
		b.WriteString("}\n\n")

		b.WriteString("func (m *" + mockType + ") " + method.Name + "(" + renderFieldSignature(method.Params) + ")" + renderResultSignature(method.Results) + " {\n")
		b.WriteString("\tm." + method.Name + "Calls = append(m." + method.Name + "Calls, " + callType + "{")
		for i, field := range method.Params {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(ExportName(field.Name) + ": " + field.Name)
		}
		b.WriteString("})\n")
		b.WriteString("\tif m." + method.Name + "Func != nil {\n")
		if len(method.Results) == 0 {
			b.WriteString("\t\tm." + method.Name + "Func(" + renderFieldNames(method.Params) + ")\n")
			b.WriteString("\t\treturn\n")
		} else {
			b.WriteString("\t\treturn m." + method.Name + "Func(" + renderFieldNames(method.Params) + ")\n")
		}
		b.WriteString("\t}\n")
		if len(method.Results) == 0 {
			b.WriteString("\treturn\n")
		} else {
			for i, field := range method.Results {
				b.WriteString("\tvar ret" + strconv.Itoa(i) + " " + field.Type + "\n")
			}
			b.WriteString("\treturn ")
			for i := range method.Results {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString("ret" + strconv.Itoa(i))
			}
			b.WriteString("\n")
		}
		b.WriteString("}\n\n")
	}
	return b.String(), nil
}

func renderFieldSignature(fields []portFieldSpec) string {
	if len(fields) == 0 {
		return ""
	}
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, field.Name+" "+field.Type)
	}
	return strings.Join(parts, ", ")
}

func renderFieldNames(fields []portFieldSpec) string {
	if len(fields) == 0 {
		return ""
	}
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, field.Name)
	}
	return strings.Join(parts, ", ")
}

func renderResultSignature(fields []portFieldSpec) string {
	if len(fields) == 0 {
		return ""
	}
	if len(fields) == 1 {
		return " " + fields[0].Type
	}
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, field.Type)
	}
	return " (" + strings.Join(parts, ", ") + ")"
}

func collectTypeAliases(t string) []string {
	seen := map[string]struct{}{}
	flush := func(token string) {
		if token == "" {
			return
		}
		if strings.Contains(token, ".") {
			parts := strings.SplitN(token, ".", 2)
			if parts[0] != "" {
				seen[parts[0]] = struct{}{}
			}
		}
	}
	var token strings.Builder
	for _, r := range t {
		if r == '.' || r == '_' || ('a' <= r && r <= 'z') || ('A' <= r && r <= 'Z') || ('0' <= r && r <= '9') {
			token.WriteRune(r)
			continue
		}
		flush(token.String())
		token.Reset()
	}
	flush(token.String())
	out := make([]string, 0, len(seen))
	for alias := range seen {
		out = append(out, alias)
	}
	sort.Strings(out)
	return out
}

func isBuiltinGoType(name string) bool {
	switch name {
	case "bool", "string", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune", "error", "any":
		return true
	default:
		return false
	}
}
