package emitter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/strogmv/ang-ir/ir"
)

func TestEmitServiceImpl_SplitsByMethod(t *testing.T) {
	root := t.TempDir()
	em := New(root, filepath.Join(root, "frontend"), "templates")
	em.GoModule = "example.com/test"
	em.Version = "0.1.test"

	schema := &ir.Schema{
		Services: []ir.Service{
			{
				Name: "Auth",
				Methods: []ir.Method{
					{
						Name:   "Login",
						Source: "cue/api/auth.cue:10",
						Input:  &ir.Entity{Name: "LoginRequest"},
						Output: &ir.Entity{Name: "LoginResponse"},
					},
					{
						Name:   "LogoutUser",
						Source: "cue/api/auth.cue:20",
						Input:  &ir.Entity{Name: "LogoutUserRequest"},
						Output: &ir.Entity{Name: "LogoutUserResponse"},
					},
				},
				Source: "cue/api/auth.cue:1",
			},
		},
	}

	if err := em.EmitServiceImplFromIR(schema, nil); err != nil {
		t.Fatalf("EmitServiceImplFromIR failed: %v", err)
	}

	targetDir := filepath.Join(root, "internal", "service")
	wantFiles := []string{
		"auth_impl.gen.go",
		"auth__login.gen.go",
		"auth__logout_user.gen.go",
	}
	for _, name := range wantFiles {
		path := filepath.Join(targetDir, name)
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("expected generated file %s: %v", path, err)
		}
	}
	if _, err := os.Stat(filepath.Join(targetDir, "auth.go")); !os.IsNotExist(err) {
		t.Fatalf("legacy monolith file should not exist")
	}

	data, err := os.ReadFile(filepath.Join(targetDir, "auth__login.gen.go"))
	if err != nil {
		t.Fatalf("read generated method file: %v", err)
	}
	if !strings.Contains(string(data), "Code generated by ANG v0.1.test") {
		t.Fatalf("expected provenance header in generated method file")
	}
}
