package emitter

import (
	"fmt"
	"strings"

	"github.com/strogmv/ang/compiler/normalizer"
)

func renderFlowStepMetaPlan(st *flowRenderState, step normalizer.FlowStep, indent int, sfx string, arg func(string) string, child func(string) []normalizer.FlowStep) (string, bool) {
	_ = child
	pad := strings.Repeat("\t", indent)

	switch step.Action {
	case "plan.BuildAutomata":
		input := arg("input")
		output := arg("output")
		if input == "" || output == "" {
			return "", true
		}
		assign := ":="
		if st.declared[output] {
			assign = "="
		}
		st.declared[output] = true
		st.pointers[output] = false
		st.types[output] = "map[string]any"
		resV := "_planAutomata" + sfx
		errV := "_planAutomataErr" + sfx
		code := renderPlanBuildAutomataCode(st, pad, input, output, assign, resV, errV)
		return code, true

	case "plan.BuildMicroPlan":
		usecases := arg("usecases")
		automata := arg("automata")
		output := arg("output")
		if usecases == "" || automata == "" || output == "" {
			return "", true
		}
		assign := ":="
		if st.declared[output] {
			assign = "="
		}
		st.declared[output] = true
		st.pointers[output] = false
		st.types[output] = "map[string]any"
		resV := "_planMicro" + sfx
		errV := "_planMicroErr" + sfx
		code := renderPlanBuildMicroPlanCode(st, pad, usecases, automata, output, assign, resV, errV)
		return code, true

	case "cue.EmitProject":
		usecases := arg("usecases")
		microPlan := arg("micro_plan")
		layout := arg("layout")
		if layout == "" {
			layout = `"split"`
		}
		output := arg("output")
		if usecases == "" || microPlan == "" || output == "" {
			return "", true
		}
		assign := ":="
		if st.declared[output] {
			assign = "="
		}
		st.declared[output] = true
		st.pointers[output] = false
		st.types[output] = "map[string]string"
		resV := "_cueProject" + sfx
		errV := "_cueProjectErr" + sfx
		code := renderCueEmitProjectCode(st, pad, usecases, microPlan, layout, output, assign, resV, errV)
		return code, true

	case "cue.ValidateProject":
		files := arg("files")
		output := arg("output")
		if files == "" || output == "" {
			return "", true
		}
		binary := arg("binary")
		if binary == "" {
			binary = `"ang"`
		}
		assign := ":="
		if st.declared[output] {
			assign = "="
		}
		st.declared[output] = true
		st.pointers[output] = false
		st.types[output] = "map[string]any"
		resV := "_cueValidate" + sfx
		errV := "_cueValidateErr" + sfx
		code := renderCueValidateProjectCode(st, pad, files, binary, output, assign, resV, errV)
		return code, true

	case "cue.WriteProjectFiles":
		root := arg("root")
		files := arg("files")
		output := arg("output")
		if root == "" || files == "" || output == "" {
			return "", true
		}
		mode := arg("mode")
		if mode == "" {
			mode = `"upsert"`
		}
		assign := ":="
		if st.declared[output] {
			assign = "="
		}
		st.declared[output] = true
		st.pointers[output] = false
		st.types[output] = "map[string]any"
		resV := "_cueWrite" + sfx
		errV := "_cueWriteErr" + sfx
		code := renderCueWriteProjectFilesCode(st, pad, root, files, mode, output, assign, resV, errV, step.Args["prefixes"])
		return code, true
	}

	return "", false
}

func renderCueWriteProjectFilesCode(st *flowRenderState, pad, root, files, mode, output, assign, resV, errV string, prefixesArg any) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s// cue.WriteProjectFiles\n", pad))
	b.WriteString(fmt.Sprintf("%s%s, %s := func() (map[string]any, error) {\n", pad, resV, errV))
	b.WriteString(fmt.Sprintf("%s\tvar _files map[string]string\n", pad))
	b.WriteString(fmt.Sprintf("%s\tswitch x := any(%s).(type) {\n", pad, files))
	b.WriteString(fmt.Sprintf("%s\tcase map[string]string:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_files = x\n", pad))
	b.WriteString(fmt.Sprintf("%s\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_raw, err := json.Marshal(x)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err != nil { return nil, fmt.Errorf(\"cue.WriteProjectFiles: encode files: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err := json.Unmarshal(_raw, &_files); err != nil { return nil, fmt.Errorf(\"cue.WriteProjectFiles: parse files: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_mode := strings.TrimSpace(strings.ToLower(%s))\n", pad, mode))
	b.WriteString(fmt.Sprintf("%s\tif _mode == \"\" { _mode = \"upsert\" }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif _mode != \"upsert\" && _mode != \"replace_prefix\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"cue.WriteProjectFiles: unsupported mode %%q\", _mode)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_root := filepath.Clean(%s)\n", pad, root))
	b.WriteString(fmt.Sprintf("%s\tif _root == \".\" || strings.TrimSpace(_root) == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"cue.WriteProjectFiles: unsafe root %%q\", %s)\n", pad, root))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := os.MkdirAll(_root, 0o755); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"cue.WriteProjectFiles: mkdir root: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_cleanPath := func(p string) (string, error) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tp = filepath.Clean(strings.TrimSpace(p))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif p == \".\" || p == \"\" || strings.HasPrefix(p, \"..\") || filepath.IsAbs(p) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\", fmt.Errorf(\"unsafe path %%q\", p)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn p, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_prefixes := make([]string, 0)\n", pad))
	switch v := prefixesArg.(type) {
	case []string:
		if len(v) > 0 {
			for _, p := range v {
				b.WriteString(fmt.Sprintf("%s\t_prefixes = append(_prefixes, %q)\n", pad, p))
			}
		}
	case []any:
		if len(v) > 0 {
			for _, raw := range v {
				if s, ok := raw.(string); ok {
					b.WriteString(fmt.Sprintf("%s\t_prefixes = append(_prefixes, %q)\n", pad, s))
				}
			}
		}
	}
	b.WriteString(fmt.Sprintf("%s\tif _mode == \"replace_prefix\" && len(_prefixes) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_seen := map[string]struct{}{}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _path := range _files {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_clean, err := _cleanPath(_path)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif err != nil { return nil, fmt.Errorf(\"cue.WriteProjectFiles: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_head := _clean\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif idx := strings.Index(_head, string(os.PathSeparator)); idx >= 0 { _head = _head[:idx] }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif _head == \"\" { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif _, ok := _seen[_head]; ok { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_seen[_head] = struct{}{}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_prefixes = append(_prefixes, _head)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_deleted := make([]string, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif _mode == \"replace_prefix\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, _prefix := range _prefixes {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_cleanPrefix, err := _cleanPath(_prefix)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif err != nil { return nil, fmt.Errorf(\"cue.WriteProjectFiles: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_target := filepath.Join(_root, _cleanPrefix)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif err := os.RemoveAll(_target); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn nil, fmt.Errorf(\"cue.WriteProjectFiles: clean prefix %%s: %%w\", _cleanPrefix, err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_deleted = append(_deleted, _cleanPrefix)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_written := make([]string, 0, len(_files))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_paths := make([]string, 0, len(_files))\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _path := range _files { _paths = append(_paths, _path) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tsort.Strings(_paths)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, _path := range _paths {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_clean, err := _cleanPath(_path)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err != nil { return nil, fmt.Errorf(\"cue.WriteProjectFiles: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_abs := filepath.Join(_root, _clean)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err := os.MkdirAll(filepath.Dir(_abs), 0o755); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.WriteProjectFiles: mkdir %%s: %%w\", filepath.Dir(_clean), err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err := os.WriteFile(_abs, []byte(_files[_path]), 0o644); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.WriteProjectFiles: write %%s: %%w\", _clean, err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_written = append(_written, _clean)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\treturn map[string]any{\"root\": _root, \"mode\": _mode, \"written\": _written, \"deleted\": _deleted}, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s}()\n", pad))
	b.WriteString(fmt.Sprintf("%sif %s != nil {\n", pad, errV))
	b.WriteString(errReturn(st, pad+"\t", fmt.Sprintf("fmt.Errorf(\"cue.WriteProjectFiles: %%w\", %s)", errV)))
	b.WriteString(fmt.Sprintf("%s}\n", pad))
	b.WriteString(fmt.Sprintf("%s%s %s %s\n", pad, output, assign, resV))
	return b.String()
}

func renderCueValidateProjectCode(st *flowRenderState, pad, files, binary, output, assign, resV, errV string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s// cue.ValidateProject\n", pad))
	b.WriteString(fmt.Sprintf("%s%s, %s := func() (map[string]any, error) {\n", pad, resV, errV))
	b.WriteString(fmt.Sprintf("%s\tvar _files map[string]string\n", pad))
	b.WriteString(fmt.Sprintf("%s\tswitch x := any(%s).(type) {\n", pad, files))
	b.WriteString(fmt.Sprintf("%s\tcase map[string]string:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_files = x\n", pad))
	b.WriteString(fmt.Sprintf("%s\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_raw, err := json.Marshal(x)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: encode files: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err := json.Unmarshal(_raw, &_files); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: parse files: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_tmpDir, err := os.MkdirTemp(\"\", \"ang-cue-validate-*\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: mktemp: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tdefer os.RemoveAll(_tmpDir)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _path, _content := range _files {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_clean := filepath.Clean(strings.TrimSpace(_path))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif _clean == \".\" || _clean == \"\" || strings.HasPrefix(_clean, \"..\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: unsafe path %%q\", _path)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_abs := filepath.Join(_tmpDir, _clean)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err := os.MkdirAll(filepath.Dir(_abs), 0o755); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: mkdir %%s: %%w\", filepath.Dir(_clean), err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif err := os.WriteFile(_abs, []byte(_content), 0o644); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: write %%s: %%w\", _clean, err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_cmd := exec.Command(%s, \"validate\", \"--json\", _tmpDir)\n", pad, binary))
	b.WriteString(fmt.Sprintf("%s\t_out, err := _cmd.Output()\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif exitErr, ok := err.(*exec.ExitError); ok && len(_out) == 0 && len(exitErr.Stderr) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_out = exitErr.Stderr\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar _env map[string]any\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif len(_out) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: empty validator output\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := json.Unmarshal(_out, &_env); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"cue.ValidateProject: parse validator output: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\treturn _env, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s}()\n", pad))
	b.WriteString(fmt.Sprintf("%sif %s != nil {\n", pad, errV))
	b.WriteString(errReturn(st, pad+"\t", fmt.Sprintf("fmt.Errorf(\"cue.ValidateProject: %%w\", %s)", errV)))
	b.WriteString(fmt.Sprintf("%s}\n", pad))
	b.WriteString(fmt.Sprintf("%s%s %s %s\n", pad, output, assign, resV))
	return b.String()
}

func renderCueEmitProjectCode(st *flowRenderState, pad, usecases, microPlan, layout, output, assign, resV, errV string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s// cue.EmitProject\n", pad))
	b.WriteString(fmt.Sprintf("%s%s, %s := func() (map[string]string, error) {\n", pad, resV, errV))
	b.WriteString(fmt.Sprintf("%s\t_planToBytes := func(v any) ([]byte, error) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch x := any(v).(type) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase string:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn []byte(x), nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase []byte:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn x, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn json.Marshal(x)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_pascal := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.TrimSpace(s)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif s == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tparts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif len(parts) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn strings.ToUpper(s[:1]) + s[1:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar out strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, part := range parts {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tpart = strings.TrimSpace(part)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif part == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tout.WriteString(strings.ToUpper(part[:1]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(part) > 1 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tout.WriteString(part[1:])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn out.String()\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_lowerCamel := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = _pascal(s)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif s == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn strings.ToLower(s[:1]) + s[1:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_kebab := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.TrimSpace(s)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif s == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar out []rune\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor i, r := range s {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif r == '_' || r == ' ' {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tout = append(out, '-')\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif i > 0 && r >= 'A' && r <= 'Z' {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tprev := rune(s[i-1])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif prev != '-' && !(prev >= 'A' && prev <= 'Z') {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tout = append(out, '-')\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif r >= 'A' && r <= 'Z' {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tr = r + ('a' - 'A')\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tout = append(out, r)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tres := strings.Trim(strings.ReplaceAll(string(out), \"--\", \"-\"), \"-\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn res\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_pluralPath := func(entity string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tk := _kebab(entity)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif k == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"items\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn k + \"s\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_contextName := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.TrimSpace(strings.ToLower(s))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif s == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, sep := range []string{\"_\", \"-\", \".\"} {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif idx := strings.Index(s, sep); idx > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn strings.TrimSpace(s[:idx])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn s\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_entityFieldCueType := func(t string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch strings.TrimSpace(t) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"uuid\", \"string\", \"int\", \"float64\", \"bool\", \"time\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn fmt.Sprintf(\"\\\"%%s\\\"\", strings.TrimSpace(t))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\\\"string\\\"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_operationFieldType := func(t string, isOutput bool) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tt = strings.TrimSpace(t)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif isOutput {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.HasPrefix(t, \"[]\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tname := strings.TrimSpace(strings.TrimPrefix(t, \"[]\"))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif name != \"\" && name[0] >= 'A' && name[0] <= 'Z' {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\treturn \"[...#\" + name + \"]\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif t != \"\" && t[0] >= 'A' && t[0] <= 'Z' {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"#\" + t\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch t {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"uuid\", \"time\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"string\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"string\", \"int\", \"float64\", \"bool\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn t\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"string\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_resolvedOutputFieldType := func(kind, entity, fieldName, fieldType string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfieldType = strings.TrimSpace(fieldType)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif kind == \"list\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.HasPrefix(fieldType, \"[]\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn _operationFieldType(fieldType, true)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.TrimSpace(entity) != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"[...#\" + strings.TrimSpace(entity) + \"]\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn _operationFieldType(fieldType, true)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_httpPath := func(kind, entity, opName string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tbase := \"/\" + _pluralPath(entity)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch kind {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"get_one\", \"update\", \"delete\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn base + \"/{id}\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"list\", \"create\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn base\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"transition\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tverb := _kebab(strings.TrimPrefix(opName, entity))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif verb == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tverb = \"change-status\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn base + \"/{id}/\" + verb\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn base\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_renderFlow := func(steps []map[string]any) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tlines := make([]string, 0, len(steps))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, step := range steps {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tprim, _ := step[\"p\"].(string)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tswitch prim {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"session\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, \"        {action: \\\"session.Get\\\", output: \\\"sessionID\\\"},\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"load\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"repo.Find\\\", source: \\\"%%s\\\", input: \\\"req.%%s\\\", output: \\\"%%s\\\", error: %%q},\", step[\"entity\"], _pascal(fmt.Sprint(step[\"input\"])), step[\"output\"], fmt.Sprint(step[\"error\"])))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"load_list\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif in, ok := step[\"input\"].(string); ok && strings.TrimSpace(in) != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"repo.List\\\", source: \\\"%%s\\\", method: \\\"%%s\\\", input: \\\"%%s\\\", output: \\\"%%s\\\"},\", step[\"entity\"], step[\"method\"], in, step[\"output\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t} else {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"repo.List\\\", source: \\\"%%s\\\", method: \\\"%%s\\\", output: \\\"%%s\\\"},\", step[\"entity\"], step[\"method\"], step[\"output\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"new\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"mapping.Map\\\", output: \\\"%%s\\\", entity: \\\"%%s\\\"},\", step[\"output\"], step[\"entity\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"set_id\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"uuid.New\\\", output: \\\"%%s\\\"},\", step[\"to\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"set_now\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"time.Now\\\", output: \\\"%%s\\\"},\", step[\"to\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"set\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"mapping.Assign\\\", to: \\\"%%s\\\", value: %%q},\", step[\"to\"], fmt.Sprint(step[\"value\"])))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"save\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"repo.Save\\\", source: \\\"%%s\\\", input: \\\"%%s\\\"},\", step[\"entity\"], step[\"input\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"delete\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"repo.Delete\\\", source: \\\"%%s\\\", input: \\\"%%s\\\"},\", step[\"entity\"], step[\"input\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"guard_status\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"logic.Check\\\", condition: \\\"%%s.Status == \\\\\\\"%%s\\\\\\\"\\\", throw: %%q},\", step[\"var\"], step[\"status\"], fmt.Sprint(step[\"throw\"])))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"transition\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"mapping.Assign\\\", to: \\\"%%s.Status\\\", value: \\\"\\\\\\\"%%s\\\\\\\"\\\"},\", step[\"var\"], step[\"to\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"reply\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"mapping.Assign\\\", to: \\\"resp.%%s\\\", value: \\\"%%s\\\"},\", _pascal(fmt.Sprint(step[\"field\"])), step[\"value\"]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcase \"emit\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tparts := make([]string, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif pm, ok := step[\"payload_map\"].(map[string]any); ok {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tkeys := make([]string, 0, len(pm))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tfor k := range pm { keys = append(keys, k) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tsort.Strings(keys)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tfor _, k := range keys {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\tparts = append(parts, fmt.Sprintf(\"%%s: \\\"%%s\\\"\", k, fmt.Sprint(pm[k])))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tlines = append(lines, fmt.Sprintf(\"        {action: \\\"event.Publish\\\", name: \\\"%%s\\\", payloadMap: {%%s}},\", step[\"name\"], strings.Join(parts, \", \")))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn strings.Join(lines, \"\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar _usecases struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tServiceName string `json:\"service_name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tEntities []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName      string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tFields    []struct{ Name, Type string } `json:\"fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tHasStatus bool `json:\"has_status\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tStatuses  []string `json:\"statuses\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"entities\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tUseCases []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tMethod string `json:\"method\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tPrimaryEntity string `json:\"primary_entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tInputFields []struct{ Name, Type string } `json:\"input_fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tOutputFields []struct{ Name, Type string } `json:\"output_fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"use_cases\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar _micro struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tOperations []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tKind string `json:\"kind\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tEntity string `json:\"entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tNeedsManualPlan bool `json:\"needs_manual_plan\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tSteps []map[string]any `json:\"steps\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"operations\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_usecasesRaw, err := _planToBytes(%s)\n", pad, usecases))
	b.WriteString(fmt.Sprintf("%s\tif err != nil { return nil, fmt.Errorf(\"cue.EmitProject: encode usecases: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := json.Unmarshal(_usecasesRaw, &_usecases); err != nil { return nil, fmt.Errorf(\"cue.EmitProject: parse usecases: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_microRaw, err := _planToBytes(%s)\n", pad, microPlan))
	b.WriteString(fmt.Sprintf("%s\tif err != nil { return nil, fmt.Errorf(\"cue.EmitProject: encode micro plan: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := json.Unmarshal(_microRaw, &_micro); err != nil { return nil, fmt.Errorf(\"cue.EmitProject: parse micro plan: %%w\", err) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_serviceName := _contextName(_usecases.ServiceName)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif _serviceName == \"\" { _serviceName = \"app\" }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfiles := map[string]string{}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar entitiesB strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\tentitiesB.WriteString(\"package domain\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, entity := range _usecases.Entities {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentitiesB.WriteString(\"#\" + entity.Name + \": {\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentitiesB.WriteString(fmt.Sprintf(\"    name:  \\\"%%s\\\"\\n\", entity.Name))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentitiesB.WriteString(fmt.Sprintf(\"    owner: \\\"%%s\\\"\\n\", _serviceName))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentitiesB.WriteString(\"    fields: {\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, field := range entity.Fields {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tline := fmt.Sprintf(\"        %%s: {type: %%s}\", field.Name, _entityFieldCueType(field.Type))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.EqualFold(field.Name, \"status\") && entity.HasStatus && len(entity.Statuses) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tline = fmt.Sprintf(\"        %%s: {type: %%s, validate: \\\"required,oneof=%%s\\\"}\", field.Name, _entityFieldCueType(field.Type), strings.Join(entity.Statuses, \" \"))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tentitiesB.WriteString(line + \"\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentitiesB.WriteString(\"    }\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentitiesB.WriteString(\"}\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfiles[\"cue/domain/entities.cue\"] = entitiesB.String()\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar httpB strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\thttpB.WriteString(\"package api\\n\\nHTTP: {\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, op := range _micro.Operations {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar method string\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, uc := range _usecases.UseCases {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif uc.Name == op.Name { method = strings.ToUpper(strings.TrimSpace(uc.Method)); break }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif method == \"\" { method = \"POST\" }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\thttpB.WriteString(fmt.Sprintf(\"    %%s: {method: \\\"%%s\\\", path: \\\"%%s\\\"}\\n\", op.Name, method, _httpPath(op.Kind, op.Entity, op.Name)))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\thttpB.WriteString(\"}\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfiles[\"cue/api/http.cue\"] = httpB.String()\n", pad))
	b.WriteString(fmt.Sprintf("%s\trepoFinders := map[string]map[string]string{}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, op := range _micro.Operations {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, step := range op.Steps {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif fmt.Sprint(step[\"p\"]) != \"load_list\" { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tentity := fmt.Sprint(step[\"entity\"])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tmethod := fmt.Sprint(step[\"method\"])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif entity == \"\" || method == \"\" { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif _, ok := repoFinders[entity]; !ok { repoFinders[entity] = map[string]string{} }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfield := strings.TrimPrefix(method, \"ListBy\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif field == \"\" { field = \"ID\" }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfieldName := _lowerCamel(field)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\trepoFinders[entity][method] = fieldName\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar repoB strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\trepoB.WriteString(\"package repo\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\tentities := make([]string, 0, len(repoFinders))\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor entity := range repoFinders { entities = append(entities, entity) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tsort.Strings(entities)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, entity := range entities {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\trepoB.WriteString(fmt.Sprintf(\"%%sRepository: {\\n\", entity))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\trepoB.WriteString(fmt.Sprintf(\"    entity: \\\"%%s\\\"\\n\", entity))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\trepoB.WriteString(\"    finders: {\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tmethods := make([]string, 0, len(repoFinders[entity]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor method := range repoFinders[entity] { methods = append(methods, method) }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tsort.Strings(methods)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, method := range methods {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfieldName := repoFinders[entity][method]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\trepoB.WriteString(fmt.Sprintf(\"        %%s: {where: {%%s: string}}\\n\", method, fieldName))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\trepoB.WriteString(\"    }\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\trepoB.WriteString(\"}\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfiles[\"cue/repo/repositories.cue\"] = repoB.String()\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar opsB strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\topsB.WriteString(\"package api\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, op := range _micro.Operations {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif op.NeedsManualPlan { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar uc *struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tMethod string `json:\"method\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tPrimaryEntity string `json:\"primary_entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tInputFields []struct{ Name, Type string } `json:\"input_fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tOutputFields []struct{ Name, Type string } `json:\"output_fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor i := range _usecases.UseCases {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif _usecases.UseCases[i].Name == op.Name { uc = &_usecases.UseCases[i]; break }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif uc == nil { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(fmt.Sprintf(\"%%s: {\\n\", op.Name))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(fmt.Sprintf(\"    description: \\\"Generated %%s operation\\\"\\n\", op.Name))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(fmt.Sprintf(\"    service:     \\\"%%s\\\"\\n\", _serviceName))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"    input: {\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, field := range uc.InputFields {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\topsB.WriteString(fmt.Sprintf(\"        %%s: %%s\\n\", field.Name, _operationFieldType(field.Type, false)))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"    }\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"    output: {\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, field := range uc.OutputFields {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\topsB.WriteString(fmt.Sprintf(\"        %%s: %%s\\n\", field.Name, _resolvedOutputFieldType(op.Kind, op.Entity, field.Name, field.Type)))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"    }\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"    flow: [\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tflowBody := _renderFlow(op.Steps)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif strings.TrimSpace(flowBody) != \"\" { opsB.WriteString(flowBody + \"\\n\") }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"    ]\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\topsB.WriteString(\"}\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfiles[\"cue/api/operations.cue\"] = opsB.String()\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_layout := strings.TrimSpace(strings.ToLower(%s))\n", pad, layout))
	b.WriteString(fmt.Sprintf("%s\tif _layout == \"\" { _layout = \"split\" }\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif _layout == \"single_file\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_stripPackage := func(src string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsrc = strings.Replace(src, \"\\r\\n\", \"\\n\", -1)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif idx := strings.Index(src, \"\\n\"); idx >= 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tfirst := strings.TrimSpace(src[:idx])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif strings.HasPrefix(first, \"package \") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tsrc = src[idx+1:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn strings.TrimSpace(src)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tsections := []string{\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_stripPackage(files[\"cue/domain/entities.cue\"]),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_stripPackage(files[\"cue/repo/repositories.cue\"]),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_stripPackage(files[\"cue/api/http.cue\"]),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_stripPackage(files[\"cue/api/operations.cue\"]),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar mainB strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tmainB.WriteString(\"package api\\n\\n\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, section := range sections {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsection = strings.TrimSpace(section)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif section == \"\" { continue }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif mainB.Len() > len(\"package api\\n\\n\") { mainB.WriteString(\"\\n\\n\") }\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tmainB.WriteString(section)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfiles = map[string]string{\"cue/main.cue\": mainB.String()}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\treturn files, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s}()\n", pad))
	b.WriteString(fmt.Sprintf("%sif %s != nil {\n", pad, errV))
	b.WriteString(errReturn(st, pad+"\t", fmt.Sprintf("fmt.Errorf(\"cue.EmitProject: %%w\", %s)", errV)))
	b.WriteString(fmt.Sprintf("%s}\n", pad))
	b.WriteString(fmt.Sprintf("%s%s %s %s\n", pad, output, assign, resV))
	return b.String()
}

func renderPlanBuildAutomataCode(st *flowRenderState, pad, input, output, assign, resV, errV string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s// plan.BuildAutomata\n", pad))
	b.WriteString(fmt.Sprintf("%s%s, %s := func() (map[string]any, error) {\n", pad, resV, errV))
	b.WriteString(fmt.Sprintf("%s\t_planToBytes := func(v any) ([]byte, error) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch x := any(v).(type) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase string:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn []byte(x), nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase []byte:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn x, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn json.Marshal(x)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_planClean := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.TrimSpace(strings.ToLower(s))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.Trim(s, \".,;:!?()[]{}\\\"'\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn s\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_planDefaultState := func(states []string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif len(states) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"pending\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, preferred := range []string{\"draft\", \"pending\"} {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfor _, st := range states {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif strings.EqualFold(strings.TrimSpace(st), preferred) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\treturn strings.TrimSpace(st)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn strings.TrimSpace(states[0])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_planExtractFromState := func(guards []string, states []string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, guard := range guards {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tgl := strings.TrimSpace(strings.ToLower(guard))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif gl == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif idx := strings.Index(gl, \" in \"); idx >= 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\ttail := gl[idx+4:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif end := strings.Index(tail, \" status\"); end > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tcandidate := _planClean(tail[:end])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tif candidate != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\treturn candidate\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.Contains(gl, \"status\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tparts := strings.Fields(gl)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tfor i := len(parts) - 1; i >= 0; i-- {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tcandidate := _planClean(parts[i])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tif candidate == \"\" || candidate == \"status\" || candidate == \"must\" || candidate == \"be\" || candidate == \"in\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\treturn candidate\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn _planDefaultState(states)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar _usecases struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tEntities []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName      string   `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tHasStatus bool     `json:\"has_status\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tStatuses  []string `json:\"statuses\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"entities\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tUseCases []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName              string   `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tPrimaryEntity     string   `json:\"primary_entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tIsStateTransition bool     `json:\"is_state_transition\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tTransitionTo      *string  `json:\"transition_to\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tGuards            []string `json:\"guards\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"use_cases\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_planRaw, err := _planToBytes(%s)\n", pad, input))
	b.WriteString(fmt.Sprintf("%s\tif err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"plan.BuildAutomata: encode input: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := json.Unmarshal(_planRaw, &_usecases); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"plan.BuildAutomata: parse input: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_automata := make([]map[string]any, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, entity := range _usecases.Entities {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif !entity.HasStatus {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_transitions := make([]map[string]any, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, uc := range _usecases.UseCases {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif uc.PrimaryEntity != entity.Name || !uc.IsStateTransition || uc.TransitionTo == nil || strings.TrimSpace(*uc.TransitionTo) == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfromState := _planExtractFromState(uc.Guards, entity.Statuses)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tentityVar := entity.Name\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif entityVar != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tentityVar = strings.ToLower(entityVar[:1]) + entityVar[1:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_transitions = append(_transitions, map[string]any{\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\"from\": fromState,\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\"to\": strings.TrimSpace(*uc.TransitionTo),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\"via_operation\": uc.Name,\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\"guard_expr\": fmt.Sprintf(\"%%s.Status == \\\"%%s\\\"\", entityVar, fromState),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_automata = append(_automata, map[string]any{\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\"entity\": entity.Name,\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\"states\": entity.Statuses,\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\"initial_state\": _planDefaultState(entity.Statuses),\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\"transitions\": _transitions,\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\treturn map[string]any{\"automata\": _automata}, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s}()\n", pad))
	b.WriteString(fmt.Sprintf("%sif %s != nil {\n", pad, errV))
	b.WriteString(errReturn(st, pad+"\t", fmt.Sprintf("fmt.Errorf(\"plan.BuildAutomata: %%w\", %s)", errV)))
	b.WriteString(fmt.Sprintf("%s}\n", pad))
	b.WriteString(fmt.Sprintf("%s%s %s %s\n", pad, output, assign, resV))
	return b.String()
}

func renderPlanBuildMicroPlanCode(st *flowRenderState, pad, usecases, automata, output, assign, resV, errV string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("%s// plan.BuildMicroPlan\n", pad))
	b.WriteString(fmt.Sprintf("%s%s, %s := func() (map[string]any, error) {\n", pad, resV, errV))
	b.WriteString(fmt.Sprintf("%s\t_planToBytes := func(v any) ([]byte, error) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch x := any(v).(type) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase string:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn []byte(x), nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase []byte:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn x, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn json.Marshal(x)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_pascal := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.TrimSpace(s)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif s == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tparts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' || r == ' ' })\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif len(parts) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn strings.ToUpper(s[:1]) + s[1:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar out strings.Builder\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, part := range parts {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tpart = strings.TrimSpace(part)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif part == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tout.WriteString(strings.ToUpper(part[:1]))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(part) > 1 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tout.WriteString(part[1:])\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn out.String()\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_lowerCamel := func(s string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = _pascal(s)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif s == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn strings.ToLower(s[:1]) + s[1:]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_startsWithAny := func(s string, prefixes ...string) bool {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\ts = strings.ToLower(strings.TrimSpace(s))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, prefix := range prefixes {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.HasPrefix(s, strings.ToLower(strings.TrimSpace(prefix))) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn true\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn false\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_kindOf := func(name, method string, outputFields []struct{ Name, Type string }, isTransition bool) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tname = strings.TrimSpace(name)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch strings.ToUpper(strings.TrimSpace(method)) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"GET\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif _startsWithAny(name, \"list\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"list\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(outputFields) > 0 && strings.HasPrefix(strings.TrimSpace(outputFields[0].Type), \"[]\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"list\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"get_one\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"POST\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif _startsWithAny(name, \"create\", \"submit\", \"add\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"create\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif isTransition {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"transition\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"create\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"PUT\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif isTransition || _startsWithAny(name, \"approve\", \"reject\", \"resolve\", \"close\", \"open\", \"cancel\", \"complete\", \"activate\", \"deactivate\") {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn \"transition\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"update\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"DELETE\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"delete\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tdefault:\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_appendEntityReplies := func(steps *[]map[string]any, outputFields []struct{ Name, Type string }, entityName, entityVar string) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, outField := range outputFields {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfieldType := strings.TrimSpace(outField.Type)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.EqualFold(fieldType, entityName) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t*steps = append(*steps, map[string]any{\"p\": \"reply\", \"field\": outField.Name, \"value\": entityVar})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t*steps = append(*steps, map[string]any{\"p\": \"reply\", \"field\": outField.Name, \"value\": entityVar + \".\" + _pascal(outField.Name)})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_findActorField := func(fields []struct{ Name, Type string }, actor string) string {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\twant := strings.ToLower(strings.TrimSpace(actor)) + \"id\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, field := range fields {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.ToLower(strings.TrimSpace(field.Name)) == want {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn field.Name\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_findEntity := func(entities []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tName      string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tFields    []struct{ Name, Type string } `json:\"fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tHasStatus bool `json:\"has_status\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tStatuses  []string `json:\"statuses\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}, name string) *struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tName      string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tFields    []struct{ Name, Type string } `json:\"fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tHasStatus bool `json:\"has_status\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tStatuses  []string `json:\"statuses\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t} {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor i := range entities {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif entities[i].Name == name {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\treturn &entities[i]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_findTransition := func(automata []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tEntity string `json:\"entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tInitialState string `json:\"initial_state\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tTransitions []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tFrom string `json:\"from\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tViaOperation string `json:\"via_operation\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"transitions\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}, entity, op string) (string, string) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tvar initial string\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tfor _, a := range automata {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif a.Entity != entity {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tinitial = a.InitialState\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfor _, tr := range a.Transitions {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif tr.ViaOperation == op {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\treturn tr.From, a.InitialState\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn \"\", initial\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_appendManual := func(items *[]map[string]any, name, reason string) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t*items = append(*items, map[string]any{\"name\": name, \"reason\": reason})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar _usecases struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tServiceName string `json:\"service_name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tEntities []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName      string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tFields    []struct{ Name, Type string } `json:\"fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tHasStatus bool `json:\"has_status\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tStatuses  []string `json:\"statuses\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"entities\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tUseCases []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tName string `json:\"name\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tActor string `json:\"actor\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tMethod string `json:\"method\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tPrimaryEntity string `json:\"primary_entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tSecondaryEntities []string `json:\"secondary_entities\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tInputFields []struct{ Name, Type string } `json:\"input_fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tOutputFields []struct{ Name, Type string } `json:\"output_fields\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tIsStateTransition bool `json:\"is_state_transition\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tTransitionTo *string `json:\"transition_to\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tGuards []string `json:\"guards\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tSideEffects []string `json:\"side_effects\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tComplexity string `json:\"complexity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"use_cases\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tvar _automata struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tAutomata []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tEntity string `json:\"entity\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tInitialState string `json:\"initial_state\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tTransitions []struct {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tFrom string `json:\"from\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tViaOperation string `json:\"via_operation\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t} `json:\"transitions\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t} `json:\"automata\"`\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_usecasesRaw, err := _planToBytes(%s)\n", pad, usecases))
	b.WriteString(fmt.Sprintf("%s\tif err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"plan.BuildMicroPlan: encode usecases: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := json.Unmarshal(_usecasesRaw, &_usecases); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"plan.BuildMicroPlan: parse usecases: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_automataRaw, err := _planToBytes(%s)\n", pad, automata))
	b.WriteString(fmt.Sprintf("%s\tif err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"plan.BuildMicroPlan: encode automata: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\tif err := json.Unmarshal(_automataRaw, &_automata); err != nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\treturn nil, fmt.Errorf(\"plan.BuildMicroPlan: parse automata: %%w\", err)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_operations := make([]map[string]any, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t_manual := make([]map[string]any, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\tfor _, uc := range _usecases.UseCases {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif strings.EqualFold(strings.TrimSpace(uc.Complexity), \"multi_entity\") || len(uc.SecondaryEntities) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendManual(&_manual, uc.Name, \"multi_entity\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tkind := _kindOf(uc.Name, uc.Method, uc.OutputFields, uc.IsStateTransition)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif kind == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendManual(&_manual, uc.Name, \"unsupported_operation_kind\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentity := _findEntity(_usecases.Entities, uc.PrimaryEntity)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif entity == nil {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendManual(&_manual, uc.Name, \"unknown_entity\")\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tentityVar := _lowerCamel(uc.PrimaryEntity)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tsteps := make([]map[string]any, 0)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tmanualReason := \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\trequiresSession := kind == \"create\" || kind == \"update\" || kind == \"delete\" || kind == \"transition\" || kind == \"list\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif requiresSession {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"session\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tswitch kind {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"get_one\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.InputFields) == 0 || len(uc.OutputFields) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"missing_io_fields\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"load\", \"entity\": uc.PrimaryEntity, \"input\": uc.InputFields[0].Name, \"output\": entityVar, \"error\": uc.PrimaryEntity + \" not found\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendEntityReplies(&steps, uc.OutputFields, uc.PrimaryEntity, entityVar)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"list\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.OutputFields) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"missing_output_fields\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfinder := \"ListAll\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfinderInput := \"\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif actorField := _findActorField(entity.Fields, uc.Actor); actorField != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tfinder = \"ListBy\" + _pascal(actorField)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tfinderInput = \"sessionID\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tstep := map[string]any{\"p\": \"load_list\", \"entity\": uc.PrimaryEntity, \"method\": finder, \"output\": entityVar + \"s\"}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif finderInput != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tstep[\"input\"] = finderInput\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, step, map[string]any{\"p\": \"reply\", \"field\": uc.OutputFields[0].Name, \"value\": entityVar + \"s\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"create\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.OutputFields) == 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"missing_output_fields\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.Guards) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"unsupported_guard\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"new\", \"entity\": uc.PrimaryEntity, \"output\": entityVar}, map[string]any{\"p\": \"set_id\", \"to\": entityVar + \".ID\"}, map[string]any{\"p\": \"set_now\", \"to\": entityVar + \".CreatedAt\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif actorField := _findActorField(entity.Fields, uc.Actor); actorField != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tsteps = append(steps, map[string]any{\"p\": \"set\", \"to\": entityVar + \".\" + _pascal(actorField), \"value\": \"sessionID\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfor _, inField := range uc.InputFields {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tsteps = append(steps, map[string]any{\"p\": \"set\", \"to\": entityVar + \".\" + _pascal(inField.Name), \"value\": \"req.\" + _pascal(inField.Name)})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif entity.HasStatus {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t_, initial := _findTransition(_automata.Automata, uc.PrimaryEntity, uc.Name)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif strings.TrimSpace(initial) == \"\" && len(entity.Statuses) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tinitial = entity.Statuses[0]\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tif strings.TrimSpace(initial) != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tsteps = append(steps, map[string]any{\"p\": \"set\", \"to\": entityVar + \".Status\", \"value\": fmt.Sprintf(\"\\\"%%s\\\"\", initial)})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"save\", \"entity\": uc.PrimaryEntity, \"input\": entityVar})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendEntityReplies(&steps, uc.OutputFields, uc.PrimaryEntity, entityVar)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"update\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.InputFields) == 0 || len(uc.OutputFields) == 0 || len(uc.Guards) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"unsupported_update_shape\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"load\", \"entity\": uc.PrimaryEntity, \"input\": uc.InputFields[0].Name, \"output\": entityVar, \"error\": uc.PrimaryEntity + \" not found\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfor _, inField := range uc.InputFields[1:] {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tsteps = append(steps, map[string]any{\"p\": \"set\", \"to\": entityVar + \".\" + _pascal(inField.Name), \"value\": \"req.\" + _pascal(inField.Name)})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"save\", \"entity\": uc.PrimaryEntity, \"input\": entityVar})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendEntityReplies(&steps, uc.OutputFields, uc.PrimaryEntity, entityVar)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"delete\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.InputFields) == 0 || len(uc.Guards) > 0 {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"unsupported_delete_shape\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps, map[string]any{\"p\": \"load\", \"entity\": uc.PrimaryEntity, \"input\": uc.InputFields[0].Name, \"output\": entityVar, \"error\": uc.PrimaryEntity + \" not found\"}, map[string]any{\"p\": \"delete\", \"entity\": uc.PrimaryEntity, \"input\": entityVar + \".ID\"})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tcase \"transition\":\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif len(uc.InputFields) == 0 || len(uc.OutputFields) == 0 || uc.TransitionTo == nil || strings.TrimSpace(*uc.TransitionTo) == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"invalid_transition_shape\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfromState, _ := _findTransition(_automata.Automata, uc.PrimaryEntity, uc.Name)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tif strings.TrimSpace(fromState) == \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmanualReason = \"missing_transition_guard\"\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tsteps = append(steps,\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmap[string]any{\"p\": \"load\", \"entity\": uc.PrimaryEntity, \"input\": uc.InputFields[0].Name, \"output\": entityVar, \"error\": uc.PrimaryEntity + \" not found\"},\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmap[string]any{\"p\": \"guard_status\", \"var\": entityVar, \"status\": fromState, \"throw\": \"Invalid status for this operation\"},\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmap[string]any{\"p\": \"transition\", \"var\": entityVar, \"to\": strings.TrimSpace(*uc.TransitionTo)},\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tmap[string]any{\"p\": \"save\", \"entity\": uc.PrimaryEntity, \"input\": entityVar},\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tfor _, effect := range uc.SideEffects {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\twords := strings.Fields(strings.TrimSpace(effect))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\tfor i, word := range words {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tlw := strings.ToLower(strings.TrimSpace(word))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\tif lw == \"emits\" || lw == \"event\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\tif i+1 < len(words) {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\t\teventName := _pascal(strings.Trim(words[i+1], \".,;:!?\"))\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\t\tif eventName != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\t\t\tsteps = append(steps, map[string]any{\"p\": \"emit\", \"name\": eventName, \"payload_map\": map[string]any{\"id\": entityVar + \".ID\"}})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t\tbreak\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendEntityReplies(&steps, uc.OutputFields, uc.PrimaryEntity, entityVar)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\tif manualReason != \"\" {\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\t_appendManual(&_manual, uc.Name, manualReason)\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t\tcontinue\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\t\t_operations = append(_operations, map[string]any{\"name\": uc.Name, \"kind\": kind, \"entity\": uc.PrimaryEntity, \"needs_manual_plan\": false, \"steps\": steps, \"repairs\": []map[string]any{}})\n", pad))
	b.WriteString(fmt.Sprintf("%s\t}\n", pad))
	b.WriteString(fmt.Sprintf("%s\treturn map[string]any{\"service_name\": _usecases.ServiceName, \"operations\": _operations, \"manual_required\": _manual}, nil\n", pad))
	b.WriteString(fmt.Sprintf("%s}()\n", pad))
	b.WriteString(fmt.Sprintf("%sif %s != nil {\n", pad, errV))
	b.WriteString(errReturn(st, pad+"\t", fmt.Sprintf("fmt.Errorf(\"plan.BuildMicroPlan: %%w\", %s)", errV)))
	b.WriteString(fmt.Sprintf("%s}\n", pad))
	b.WriteString(fmt.Sprintf("%s%s %s %s\n", pad, output, assign, resV))
	return b.String()
}
