"""Typed models generated by ANG."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel


class Comment(BaseModel):
    id: dict[str, Any]
    postID: dict[str, Any]
    authorID: dict[str, Any]
    parentID: dict[str, Any]
    content: dict[str, Any]
    createdAt: dict[str, Any]
    updatedAt: dict[str, Any]


class Post(BaseModel):
    id: dict[str, Any]
    authorID: dict[str, Any]
    title: dict[str, Any]
    slug: dict[str, Any]
    content: dict[str, Any]
    excerpt: dict[str, Any]
    status: dict[str, Any]
    publishedAt: dict[str, Any]
    viewCount: dict[str, Any]
    createdAt: dict[str, Any]
    updatedAt: dict[str, Any]


class PostTag(BaseModel):
    postID: dict[str, Any]
    tagID: dict[str, Any]


class Tag(BaseModel):
    id: dict[str, Any]
    name: dict[str, Any]
    slug: dict[str, Any]
    description: dict[str, Any]


class User(BaseModel):
    id: dict[str, Any]
    email: dict[str, Any]
    phoneNumber: dict[str, Any] | None = None
    passwordHash: dict[str, Any]
    name: dict[str, Any]
    role: dict[str, Any]
    avatarURL: dict[str, Any]
    createdAt: dict[str, Any]
    updatedAt: dict[str, Any]


class UserVault(BaseModel):
    id: str
    personalKey: str
    bio: str | None = None

