// Package http provides HTTP handlers for the service.
// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.127
// InputHash: 0042c83541f19460bd5eeaaca878da6acf4e7b35b891888724c9c4cdb759de2b
// CompilerHash: 294b50c17c5868adf98ff6e7e34d9b0ddcf67156d863f2f508ad57df44889164
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

package http

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"

	"github.com/example/minimal/internal/pkg/errors"
	"github.com/example/minimal/internal/port"
	"github.com/go-chi/chi/v5"
)

func RegisterUserRoutes(r chi.Router, svc port.User) {
	r.With(MaxBodySizeMiddleware(1048576)).Get("/users", handlerListUsers(svc))
}

// handlerListUsers
// Source: /home/strog/work/ang/cue/schema/types.cue:1252
func handlerListUsers(svc port.User) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req port.ListUsersRequest
		if v := r.URL.Query().Get("limit"); v != "" {
			if i, err := strconv.Atoi(v); err == nil {
				req.Limit = i
			} else {
				errors.WriteError(w, r, errors.NewValidationError("Invalid query", map[string]string{"limit": "must be integer"}))
				return
			}
		}
		if v := r.URL.Query().Get("offset"); v != "" {
			if i, err := strconv.Atoi(v); err == nil {
				req.Offset = i
			} else {
				errors.WriteError(w, r, errors.NewValidationError("Invalid query", map[string]string{"offset": "must be integer"}))
				return
			}
		}
		if err := validate.Struct(&req); err != nil {
			errors.WriteError(w, r, errors.NewValidationError(err.Error(), nil))
			return
		}
		if err := req.Validate(); err != nil {
			errors.WriteError(w, r, errors.NewValidationError(err.Error(), nil))
			return
		}
		resp, err := svc.ListUsers(r.Context(), req)
		if err != nil {
			errors.WriteError(w, r, err)
			return
		}

		w.Header().Set("Content-Type", "application/json")
		var out any
		out = resp
		data, err := json.Marshal(out)
		if err != nil {
			errors.WriteError(w, r, errors.New(http.StatusInternalServerError, "Internal Server Error", "Failed to encode response"))
			return
		}
		etag := fmt.Sprintf("W/\"%x\"", sha256.Sum256(data))
		w.Header().Set("ETag", etag)
		if match := r.Header.Get("If-None-Match"); match == etag {
			w.WriteHeader(http.StatusNotModified)
			return
		}
		_, _ = w.Write(data)

	}
}
