// AUTO-GENERATED by ANG
import { apiClient, validateResponse } from './api-client';
import { markInvalidateTargets } from './stores/invalidation';
import * as Types from './types';
export const login = (params: Types.LoginRequest = {} as Types.LoginRequest) => {
  return apiClient.post<Types.LoginResponse>(`/auth/login`, params).then((r) => {
    const data = validateResponse('LoginResponseSchema', r.data, 'Login');
    const invalidateTargets = endpointMeta.login.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const getProfile = (params: Types.GetProfileRequest = {} as Types.GetProfileRequest) => {
  const queryParams = { ...params } as any;
  return apiClient.get<Types.GetProfileResponse>(`/auth/profile`, { params: queryParams }).then((r) =>
    validateResponse('GetProfileResponseSchema', r.data, 'GetProfile')
  );
};
export const updateProfile = (params: Types.UpdateProfileRequest = {} as Types.UpdateProfileRequest) => {
  return apiClient.put<Types.UpdateProfileResponse>(`/auth/profile`, params).then((r) => {
    const data = validateResponse('UpdateProfileResponseSchema', r.data, 'UpdateProfile');
    const invalidateTargets = endpointMeta.updateProfile.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const register = (params: Types.RegisterRequest = {} as Types.RegisterRequest) => {
  return apiClient.post<Types.RegisterResponse>(`/auth/register`, params).then((r) => {
    const data = validateResponse('RegisterResponseSchema', r.data, 'Register');
    const invalidateTargets = endpointMeta.register.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const deleteComment = (params: Types.DeleteCommentRequest = {} as Types.DeleteCommentRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.delete<Types.DeleteCommentResponse>(`/comments/${id}`, { data: params }).then((r) => {
    const data = validateResponse('DeleteCommentResponseSchema', r.data, 'DeleteComment');
    const invalidateTargets = endpointMeta.deleteComment.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const updateComment = (params: Types.UpdateCommentRequest = {} as Types.UpdateCommentRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.put<Types.UpdateCommentResponse>(`/comments/${id}`, params).then((r) => {
    const data = validateResponse('UpdateCommentResponseSchema', r.data, 'UpdateComment');
    const invalidateTargets = endpointMeta.updateComment.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const listMyPosts = (params: Types.ListMyPostsRequest = {} as Types.ListMyPostsRequest) => {
  const queryParams = { ...params } as any;
  return apiClient.get<Types.ListMyPostsResponse>(`/my/posts`, { params: queryParams }).then((r) =>
    validateResponse('ListMyPostsResponseSchema', r.data, 'ListMyPosts')
  );
};
export const listPosts = (params: Types.ListPostsRequest = {} as Types.ListPostsRequest) => {
  const queryParams = { ...params } as any;
  return apiClient.get<Types.ListPostsResponse>(`/posts`, { params: queryParams }).then((r) =>
    validateResponse('ListPostsResponseSchema', r.data, 'ListPosts')
  );
};
export const createPost = (params: Types.CreatePostRequest = {} as Types.CreatePostRequest) => {
  return apiClient.post<Types.CreatePostResponse>(`/posts`, params).then((r) => {
    const data = validateResponse('CreatePostResponseSchema', r.data, 'CreatePost');
    const invalidateTargets = endpointMeta.createPost.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const deletePost = (params: Types.DeletePostRequest = {} as Types.DeletePostRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.delete<Types.DeletePostResponse>(`/posts/${id}`, { data: params }).then((r) => {
    const data = validateResponse('DeletePostResponseSchema', r.data, 'DeletePost');
    const invalidateTargets = endpointMeta.deletePost.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const updatePost = (params: Types.UpdatePostRequest = {} as Types.UpdatePostRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.put<Types.UpdatePostResponse>(`/posts/${id}`, params).then((r) => {
    const data = validateResponse('UpdatePostResponseSchema', r.data, 'UpdatePost');
    const invalidateTargets = endpointMeta.updatePost.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const archivePost = (params: Types.ArchivePostRequest = {} as Types.ArchivePostRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.post<Types.ArchivePostResponse>(`/posts/${id}/archive`, params).then((r) => {
    const data = validateResponse('ArchivePostResponseSchema', r.data, 'ArchivePost');
    const invalidateTargets = endpointMeta.archivePost.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const publishPost = (params: Types.PublishPostRequest = {} as Types.PublishPostRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.post<Types.PublishPostResponse>(`/posts/${id}/publish`, params).then((r) => {
    const data = validateResponse('PublishPostResponseSchema', r.data, 'PublishPost');
    const invalidateTargets = endpointMeta.publishPost.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const submitPost = (params: Types.SubmitPostRequest = {} as Types.SubmitPostRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.post<Types.SubmitPostResponse>(`/posts/${id}/submit`, params).then((r) => {
    const data = validateResponse('SubmitPostResponseSchema', r.data, 'SubmitPost');
    const invalidateTargets = endpointMeta.submitPost.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const listComments = (params: Types.ListCommentsRequest = {} as Types.ListCommentsRequest) => {
  // @ts-ignore
  const postID = (params as any)?.postID ?? (params as any)?.postId;
  const queryParams = { ...params } as any;
  delete queryParams.postID;
  delete queryParams.postId;
  return apiClient.get<Types.ListCommentsResponse>(`/posts/${postID}/comments`, { params: queryParams }).then((r) =>
    validateResponse('ListCommentsResponseSchema', r.data, 'ListComments')
  );
};
export const createComment = (params: Types.CreateCommentRequest = {} as Types.CreateCommentRequest) => {
  // @ts-ignore
  const postID = (params as any)?.postID ?? (params as any)?.postId;
  return apiClient.post<Types.CreateCommentResponse>(`/posts/${postID}/comments`, params).then((r) => {
    const data = validateResponse('CreateCommentResponseSchema', r.data, 'CreateComment');
    const invalidateTargets = endpointMeta.createComment.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const getPost = (params: Types.GetPostRequest = {} as Types.GetPostRequest) => {
  // @ts-ignore
  const slug = (params as any)?.slug;
  const queryParams = { ...params } as any;
  delete queryParams.slug;
  return apiClient.get<Types.GetPostResponse>(`/posts/${slug}`, { params: queryParams }).then((r) =>
    validateResponse('GetPostResponseSchema', r.data, 'GetPost')
  );
};
export const listTags = (params: Types.ListTagsRequest = {} as Types.ListTagsRequest) => {
  const queryParams = { ...params } as any;
  return apiClient.get<Types.ListTagsResponse>(`/tags`, { params: queryParams }).then((r) =>
    validateResponse('ListTagsResponseSchema', r.data, 'ListTags')
  );
};
export const createTag = (params: Types.CreateTagRequest = {} as Types.CreateTagRequest) => {
  return apiClient.post<Types.CreateTagResponse>(`/tags`, params).then((r) => {
    const data = validateResponse('CreateTagResponseSchema', r.data, 'CreateTag');
    const invalidateTargets = endpointMeta.createTag.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const deleteTag = (params: Types.DeleteTagRequest = {} as Types.DeleteTagRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.delete<Types.DeleteTagResponse>(`/tags/${id}`, { data: params }).then((r) => {
    const data = validateResponse('DeleteTagResponseSchema', r.data, 'DeleteTag');
    const invalidateTargets = endpointMeta.deleteTag.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};
export const updateTag = (params: Types.UpdateTagRequest = {} as Types.UpdateTagRequest) => {
  // @ts-ignore
  const id = (params as any)?.id ?? (params as any)?.ID;
  return apiClient.put<Types.UpdateTagResponse>(`/tags/${id}`, params).then((r) => {
    const data = validateResponse('UpdateTagResponseSchema', r.data, 'UpdateTag');
    const invalidateTargets = endpointMeta.updateTag.invalidateTargets || [];
    if (invalidateTargets.length > 0) {
      markInvalidateTargets(invalidateTargets, params);
    }
    return data;
  });
};

export const endpointMeta: Record<string, {
  method: string;
  path: string;
  idempotent?: boolean;
  timeout?: string;
  authRoles?: string[];
  cacheTTL?: string;
  rateLimit?: {
    rps: number;
    burst: number;
  };
  requiredHeaders?: string[];
  retryStrategy?: {
    maxAttempts: number;
    baseDelayMs: number;
    retryOnStatuses: number[];
    retryNetworkErrors: boolean;
  };
  invalidateTargets?: {
    store: string;
    scopeParam?: string;
    mode?: 'list' | 'detail' | 'aggregate';
  }[];
}> = {
  login: {
    method: 'POST',
    path: '/auth/login',
    invalidateTargets: [{ store: 'auth', mode: 'list' }
    ],
  },
  getProfile: {
    method: 'GET',
    path: '/auth/profile',
    requiredHeaders: ['Authorization'],
    retryStrategy: {
      maxAttempts: 2,
      baseDelayMs: 200,
      retryOnStatuses: [429, 502, 503, 504],
      retryNetworkErrors: true,
    },
  },
  updateProfile: {
    method: 'PUT',
    path: '/auth/profile',
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'auth', mode: 'list' }
    ],
  },
  register: {
    method: 'POST',
    path: '/auth/register',
    invalidateTargets: [{ store: 'auth', mode: 'list' }
    ],
  },
  deleteComment: {
    method: 'DELETE',
    path: '/comments/{id}',
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', mode: 'list' },{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  updateComment: {
    method: 'PUT',
    path: '/comments/{id}',
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', mode: 'list' },{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  listMyPosts: {
    method: 'GET',
    path: '/my/posts',
    authRoles: ['author', 'admin'],
    requiredHeaders: ['Authorization'],
    retryStrategy: {
      maxAttempts: 2,
      baseDelayMs: 200,
      retryOnStatuses: [429, 502, 503, 504],
      retryNetworkErrors: true,
    },
  },
  listPosts: {
    method: 'GET',
    path: '/posts',
    retryStrategy: {
      maxAttempts: 2,
      baseDelayMs: 200,
      retryOnStatuses: [429, 502, 503, 504],
      retryNetworkErrors: true,
    },
  },
  createPost: {
    method: 'POST',
    path: '/posts',
    authRoles: ['author', 'admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  deletePost: {
    method: 'DELETE',
    path: '/posts/{id}',
    authRoles: ['author', 'admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  updatePost: {
    method: 'PUT',
    path: '/posts/{id}',
    authRoles: ['author', 'admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  archivePost: {
    method: 'POST',
    path: '/posts/{id}/archive',
    authRoles: ['author', 'admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  publishPost: {
    method: 'POST',
    path: '/posts/{id}/publish',
    authRoles: ['admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  submitPost: {
    method: 'POST',
    path: '/posts/{id}/submit',
    authRoles: ['author', 'admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  listComments: {
    method: 'GET',
    path: '/posts/{postID}/comments',
    retryStrategy: {
      maxAttempts: 2,
      baseDelayMs: 200,
      retryOnStatuses: [429, 502, 503, 504],
      retryNetworkErrors: true,
    },
  },
  createComment: {
    method: 'POST',
    path: '/posts/{postID}/comments',
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', mode: 'list' },{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  getPost: {
    method: 'GET',
    path: '/posts/{slug}',
    retryStrategy: {
      maxAttempts: 2,
      baseDelayMs: 200,
      retryOnStatuses: [429, 502, 503, 504],
      retryNetworkErrors: true,
    },
  },
  listTags: {
    method: 'GET',
    path: '/tags',
    retryStrategy: {
      maxAttempts: 2,
      baseDelayMs: 200,
      retryOnStatuses: [429, 502, 503, 504],
      retryNetworkErrors: true,
    },
  },
  createTag: {
    method: 'POST',
    path: '/tags',
    authRoles: ['admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  deleteTag: {
    method: 'DELETE',
    path: '/tags/{id}',
    authRoles: ['admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
  updateTag: {
    method: 'PUT',
    path: '/tags/{id}',
    authRoles: ['admin'],
    requiredHeaders: ['Authorization'],
    invalidateTargets: [{ store: 'comment', scopeParam: 'postID', mode: 'detail' },{ store: 'my', mode: 'list' },{ store: 'post', mode: 'list' },{ store: 'tag', mode: 'list' }
    ],
  },
};
