// Generated by ANG. Do not edit.
// Locale-aware formatters — read user.locale and user.timezone from auth store automatically.
import { useAuthStore } from './auth-store';

type LocalizedUserLike = {
  locale?: string | null;
  timezone?: string | null;
};

const getLocale = (): string => {
  const user = useAuthStore.getState().user;
  return (user as LocalizedUserLike | null | undefined)?.locale || (typeof navigator !== 'undefined' ? navigator.language : 'en') || 'en';
};

const getTimezone = (): string => {
  const user = useAuthStore.getState().user;
  return (user as LocalizedUserLike | null | undefined)?.timezone
    || (typeof Intl !== 'undefined' ? Intl.DateTimeFormat().resolvedOptions().timeZone : 'UTC');
};

/** Format a date value using user locale and timezone. */
export const formatDate = (
  date: Date | string | null | undefined,
  options?: Intl.DateTimeFormatOptions
): string => {
  if (!date) return '';
  const d = typeof date === 'string' ? new Date(date) : date;
  if (isNaN(d.getTime())) return '';
  return new Intl.DateTimeFormat(getLocale(), { timeZone: getTimezone(), ...options }).format(d);
};

/** Format date + time using user locale and timezone. */
export const formatDateTime = (
  date: Date | string | null | undefined,
  options?: Intl.DateTimeFormatOptions
): string =>
  formatDate(date, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
    ...options,
  });

/** Format a monetary amount using user locale. */
export const formatMoney = (
  amount: number | null | undefined,
  currency = 'USD',
  options?: Intl.NumberFormatOptions
): string => {
  if (amount == null) return '';
  return new Intl.NumberFormat(getLocale(), { style: 'currency', currency, ...options }).format(amount);
};

/** Format a number using user locale. */
export const formatNumber = (
  n: number | null | undefined,
  options?: Intl.NumberFormatOptions
): string => {
  if (n == null) return '';
  return new Intl.NumberFormat(getLocale(), options).format(n);
};

/** Format a date relative to now ("2 minutes ago", "in 3 days"). */
export const formatRelative = (date: Date | string | null | undefined): string => {
  if (!date) return '';
  const d = typeof date === 'string' ? new Date(date) : date;
  if (isNaN(d.getTime())) return '';
  const diff = (d.getTime() - Date.now()) / 1000;
  const rtf = new Intl.RelativeTimeFormat(getLocale(), { numeric: 'auto' });
  const abs = Math.abs(diff);
  if (abs < 60)       return rtf.format(Math.round(diff), 'second');
  if (abs < 3600)     return rtf.format(Math.round(diff / 60), 'minute');
  if (abs < 86400)    return rtf.format(Math.round(diff / 3600), 'hour');
  if (abs < 2592000)  return rtf.format(Math.round(diff / 86400), 'day');
  if (abs < 31536000) return rtf.format(Math.round(diff / 2592000), 'month');
  return rtf.format(Math.round(diff / 31536000), 'year');
};

// Entity-specific date formatters derived from domain field names:
/** Format Comment.createdAt as a localized date-time. */
export const formatCommentCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format Comment.updatedAt as a localized date-time. */
export const formatCommentUpdatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format Post.publishedAt as a localized date-time. */
export const formatPostPublishedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format Post.createdAt as a localized date-time. */
export const formatPostCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format Post.updatedAt as a localized date-time. */
export const formatPostUpdatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format Tag.createdAt as a localized date-time. */
export const formatTagCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format User.createdAt as a localized date-time. */
export const formatUserCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format User.updatedAt as a localized date-time. */
export const formatUserUpdatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format GetProfileResponse.createdAt as a localized date-time. */
export const formatGetProfileResponseCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format GetPostResponse.createdAt as a localized date-time. */
export const formatGetPostResponseCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format ListCommentsResponseData.createdAt as a localized date-time. */
export const formatListCommentsResponseDataCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format ListMyPostsResponseData.createdAt as a localized date-time. */
export const formatListMyPostsResponseDataCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
/** Format ListPostsResponseData.createdAt as a localized date-time. */
export const formatListPostsResponseDataCreatedAt = (
  value: string | null | undefined,
  opts?: Intl.DateTimeFormatOptions
): string => formatDateTime(value, opts);
