// Generated by ANG. Do not edit.
// GDPR client helpers — erasure requests, data export, consent management.
import { useMutation, useQueryClient } from '@tanstack/react-query';
import * as api from './endpoints';

type GdprOwnerReq = { ownerId: string };
type GdprEndpointFn = (req: GdprOwnerReq) => Promise<unknown>;

/** Resolve optional GDPR RPCs without keyof errors when they are not yet on the OpenAPI surface. */
function gdprCall(name: string, req: GdprOwnerReq): Promise<unknown> {
  const fn = (api as unknown as Record<string, GdprEndpointFn | undefined>)[name];
  if (typeof fn !== 'function') {
    return Promise.reject(
      new Error(`GDPR SDK: "${name}" is missing from generated endpoints; add the RPC to the API spec.`),
    );
  }
  return fn(req);
}

// ── Consent tracking ─────────────────────────────────────────────────────────

export type ConsentScope =
  | 'analytics'
  | 'marketing'
  | 'personalization'
  | 'essential';

export type ConsentState = Record<ConsentScope, boolean>;

const CONSENT_KEY = 'ang_gdpr_consent';

/** Read persisted consent from localStorage. */
export const getConsent = (): Partial<ConsentState> => {
  if (typeof window === 'undefined') return {};
  try {
    return JSON.parse(localStorage.getItem(CONSENT_KEY) ?? '{}');
  } catch {
    return {};
  }
};

/** Persist consent decision to localStorage (and optionally sync to backend). */
export const setConsent = (state: Partial<ConsentState>): void => {
  if (typeof window === 'undefined') return;
  const merged = { ...getConsent(), ...state };
  localStorage.setItem(CONSENT_KEY, JSON.stringify(merged));
};

export const hasConsent = (scope: ConsentScope): boolean =>
  getConsent()[scope] ?? false;

// ── Per-entity GDPR operations ────────────────────────────────────────────────

/** Helper: trigger download of exported personal data as a JSON file. */
export const downloadPersonalData = (blob: unknown, filename = 'my-data.json'): void => {
  const url = URL.createObjectURL(
    new Blob([JSON.stringify(blob, null, 2)], { type: 'application/json' }),
  );
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
};
