// @ts-nocheck
// Generated by ANG. Do not edit.
import React, { PropsWithChildren } from 'react';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const queryClient = new QueryClient();

export const AppProviders = ({ children }: PropsWithChildren) => (
  <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
);

export const withAppProviders =
  <P extends object>(Component: React.ComponentType<P>) =>
  (props: P) => (
    <AppProviders>
      <Component {...props} />
    </AppProviders>
  );
