// Generated by ANG. Do not edit.
import React, { PropsWithChildren, lazy, Suspense } from 'react';

import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { queryProfiles } from './query-options';

const defaultQueryProfile = queryProfiles.standard || {};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: defaultQueryProfile.staleTime ?? 30 * 1000,
      gcTime: defaultQueryProfile.gcTime ?? 5 * 60 * 1000,
      retry: defaultQueryProfile.retry ?? 1,
      refetchOnMount: defaultQueryProfile.refetchOnMount ?? false,
      refetchOnWindowFocus: defaultQueryProfile.refetchOnWindowFocus ?? false,
      refetchOnReconnect: defaultQueryProfile.refetchOnReconnect ?? true,
    },
    mutations: {
      retry: 0,
    },
  },
});

const ReactQueryDevtools =
  process.env.NODE_ENV === 'development'
    ? lazy(() =>
        import('@tanstack/react-query-devtools').then((m) => ({
          default: m.ReactQueryDevtools,
        }))
      )
    : null;

export const AppProviders = ({ children }: PropsWithChildren) => (
  <QueryClientProvider client={queryClient}>
    {children}
    {ReactQueryDevtools && (
      <Suspense fallback={null}>
        <ReactQueryDevtools initialIsOpen={false} buttonPosition="bottom-right" />
      </Suspense>
    )}
  </QueryClientProvider>
);

export const withAppProviders =
  <P extends object>(Component: React.ComponentType<P>) =>
  (props: P) => (
    <AppProviders>
      <Component {...props} />
    </AppProviders>
  );
