// AUTO-GENERATED by ANG
import { queryOptions } from '@tanstack/react-query';
import { queryKeys } from './query-keys';
import * as api from './endpoints';
import type * as Types from './types';
export const authOptions = {
};
export const myOptions = {
};
export const postsOptions = {
  list: (filters?: Types.ListPostsRequest) =>
    queryOptions({
      queryKey: queryKeys.posts.list(filters),
      queryFn: () => api.listPosts(filters),
    }),
  detail: (slug: string) =>
    queryOptions({
      queryKey: queryKeys.posts.detail(slug),
      queryFn: () => api.getPost({ slug } as Types.GetPostRequest),
      enabled: !!slug,
    }),
};
export const tagsOptions = {
  list: (filters?: Types.ListTagsRequest) =>
    queryOptions({
      queryKey: queryKeys.tags.list(filters),
      queryFn: () => api.listTags(filters),
    }),
};
