// Generated by ANG. Do not edit.
import { QueryClient } from '@tanstack/react-query';
import * as Queries from './queries';

export interface RouteMeta {
  title: string;
  breadcrumb: string;
}

export const createRouteDefinitions = (queryClient: QueryClient) => [
];

export const Routes = {
};
