// Generated by ANG. Do not edit.
import { useQueryClient } from '@tanstack/react-query';
import { WebSocketClient, WSMessage } from '../websocket';
import { queryKeys } from '../query-keys';
// @ts-ignore
import { useEffect, useRef, useLayoutEffect } from 'react';

const payloadResourceMap: Record<string, keyof typeof queryKeys> = {
  tenderId: 'tenders',
  applicationId: 'tenders',
  bidId: 'tenders',
  companyId: 'companies',
  chatId: 'chat',
  notificationId: 'notifications',
  attachmentId: 'attachments',
  reportId: 'tenders',
};

const inferResourcesFromPayload = (payload: any): Array<keyof typeof queryKeys> => {
  if (!payload || typeof payload !== 'object') return [];
  const resources = new Set<keyof typeof queryKeys>();
  for (const [field, resource] of Object.entries(payloadResourceMap)) {
    if (Object.prototype.hasOwnProperty.call(payload, field) && payload[field] !== undefined) {
      resources.add(resource);
    }
  }
  return Array.from(resources);
};

// Singleton WS Client
export const wsClient = new WebSocketClient(((import.meta as any).env?.VITE_API_URL || 'http://localhost:8080').replace(/^http/, 'ws') + '/ws');

/**
 * Hook to subscribe to specific WebSocket events.
 * @param topic The event type to filter by
 * @param onMessage Callback function when message arrives
 */
export const useWebsocketSubscription = <K extends WSMessage['type']>(
  topic: K,
  onMessage: (payload: Extract<WSMessage, { type: K }>['payload']) => void
) => {
  // Ref-pattern: always call the latest callback without re-subscribing on every render.
  // Adding onMessage to deps would re-subscribe on every inline-function re-creation.
  const onMessageRef = useRef(onMessage);
  useLayoutEffect(() => { onMessageRef.current = onMessage; });

  useEffect(() => {
    const unsubscribe = wsClient.subscribe((data: WSMessage) => {
      if (data.type === topic) {
        // @ts-ignore
        onMessageRef.current(data.payload);
      }
    });
    return () => unsubscribe();
  }, [topic]); // only re-subscribe when the topic changes
};

/**
 * Global hook to automatically invalidate queries based on WS events.
 * Call this once in your App root.
 */
export const useAutoInvalidation = () => {
  const queryClient = useQueryClient();

  useEffect(() => {
    const unsubscribe = wsClient.subscribe((data: WSMessage) => {
      const resources = inferResourcesFromPayload(data.payload);
      if (resources.length > 0) {
        resources.forEach((resource) => {
          queryClient.invalidateQueries({ queryKey: queryKeys[resource].all });
        });
        return;
      }

      const entity = data.type.replace(/Placed|Updated|Created|Deleted|Finished|Started/g, '').toLowerCase();
      if (entity && entity in queryKeys) {
        queryClient.invalidateQueries({ queryKey: queryKeys[entity as keyof typeof queryKeys].all });
      }
    });
    return () => unsubscribe();
  }, [queryClient]);
};
