// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.82
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

import (
	"github.com/strogmv/ang/internal/domain"
)

// PostTagDTO represents the data transfer object.
type PostTagDTO struct {
	PostID string `json:"postId"`
	TagID  string `json:"tagId"`
}

// ToDomain converts DTO to domain entity.
func (d *PostTagDTO) ToDomain() *domain.PostTag {
	if d == nil {
		return nil
	}
	return &domain.PostTag{
		PostID: d.PostID,
		TagID:  d.TagID,
	}
}

// FromDomain converts domain entity to DTO.
func (d *PostTagDTO) FromDomain(e *domain.PostTag) {
	if e == nil {
		return
	}
	d.PostID = e.PostID
	d.TagID = e.TagID
}

// ToDTO helper for quick conversion.
func ToPostTagDTO(e *domain.PostTag) *PostTagDTO {
	if e == nil {
		return nil
	}
	d := &PostTagDTO{}
	d.FromDomain(e)
	return d
}

func (d *PostTagDTO) Validate() error {
	return nil
}
