// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.81
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

import (
	"github.com/strogmv/ang/internal/domain"
	"time"
)

// PostDTO represents the data transfer object.
type PostDTO struct {
	ID          string `json:"ID"`
	AuthorID    string `json:"authorId"`
	Title       string `json:"title"`
	Slug        string `json:"slug"`
	Content     string `json:"content"`
	Excerpt     string `json:"excerpt"`
	Status      string `json:"status"`
	PublishedAt string `json:"publishedAt"`
	ViewCount   int    `json:"viewCount"`
	CreatedAt   string `json:"createdAt"`
	UpdatedAt   string `json:"updatedAt"`
}

// ToDomain converts DTO to domain entity.
func (d *PostDTO) ToDomain() *domain.Post {
	if d == nil {
		return nil
	}
	return &domain.Post{
		ID:          d.ID,
		AuthorID:    d.AuthorID,
		Title:       d.Title,
		Slug:        d.Slug,
		Content:     d.Content,
		Excerpt:     d.Excerpt,
		Status:      d.Status,
		PublishedAt: d.PublishedAt,
		ViewCount:   d.ViewCount,
		CreatedAt:   d.CreatedAt,
		UpdatedAt:   d.UpdatedAt,
	}
}

// FromDomain converts domain entity to DTO.
func (d *PostDTO) FromDomain(e *domain.Post) {
	if e == nil {
		return
	}
	d.ID = e.ID
	d.AuthorID = e.AuthorID
	d.Title = e.Title
	d.Slug = e.Slug
	d.Content = e.Content
	d.Excerpt = e.Excerpt
	d.Status = e.Status
	d.PublishedAt = e.PublishedAt
	d.ViewCount = e.ViewCount
	d.CreatedAt = e.CreatedAt
	d.UpdatedAt = e.UpdatedAt
}

// ToDTO helper for quick conversion.
func ToPostDTO(e *domain.Post) *PostDTO {
	if e == nil {
		return nil
	}
	d := &PostDTO{}
	d.FromDomain(e)
	return d
}

func (d *PostDTO) Validate() error {
	return nil
}
