// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.65
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

// PostTagDTO represents the data transfer object.
type PostTagDTO struct {
	PostID string `json:"postId"`
	TagID  string `json:"tagId"`
}

func (d *PostTagDTO) Validate() error {
	return nil
}
