// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.43
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

import ()

// TagDTO represents the data transfer object.
type TagDTO struct {
	ID          any `json:"id"`
	Name        any `json:"name"`
	Slug        any `json:"slug"`
	Description any `json:"description"`
}

func (d *TagDTO) Validate() error {
	return nil
}
