// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.65
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

// TagDTO represents the data transfer object.
type TagDTO struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (d *TagDTO) Validate() error {
	return nil
}
