// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.81
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

import (
	"github.com/strogmv/ang/internal/domain"
)

// UserDTO represents the data transfer object.
type UserDTO struct {
	Email        any `json:"email"`
	PasswordHash any `json:"passwordHash"`
	Name         any `json:"name"`
	AvatarURL    any `json:"avatarUrl"`
}

// ToDomain converts DTO to domain entity.
func (d *UserDTO) ToDomain() *domain.User {
	if d == nil {
		return nil
	}
	return &domain.User{
		Email:        d.Email,
		PasswordHash: d.PasswordHash,
		Name:         d.Name,
		AvatarURL:    d.AvatarURL,
	}
}

// FromDomain converts domain entity to DTO.
func (d *UserDTO) FromDomain(e *domain.User) {
	if e == nil {
		return
	}
	d.Email = e.Email
	d.PasswordHash = e.PasswordHash
	d.Name = e.Name
	d.AvatarURL = e.AvatarURL
}

// ToDTO helper for quick conversion.
func ToUserDTO(e *domain.User) *UserDTO {
	if e == nil {
		return nil
	}
	d := &UserDTO{}
	d.FromDomain(e)
	return d
}

func (d *UserDTO) Validate() error {
	return nil
}
