// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.55
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

import ()

// UserDTO represents the data transfer object.
type UserDTO struct {
	ID           any `json:"id"`
	Email        any `json:"email"`
	PhoneNumber  any `json:"phoneNumber"`
	PasswordHash any `json:"passwordHash"`
	Name         any `json:"name"`
	Role         any `json:"role"`
	AvatarURL    any `json:"avatarUrl"`
	CreatedAt    any `json:"createdAt"`
	UpdatedAt    any `json:"updatedAt"`
}

func (d *UserDTO) Validate() error {
	return nil
}
