// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.65
// DO NOT EDIT - changes will be overwritten on next generation
// ============================================================================

package dto

// UserDTO represents the data transfer object.
type UserDTO struct {
	Email        any `json:"email"`
	PasswordHash any `json:"passwordHash"`
	Name         any `json:"name"`
	AvatarURL    any `json:"avatarUrl"`
}

func (d *UserDTO) Validate() error {
	return nil
}
