"""Notifications service stub generated by ANG."""

from __future__ import annotations

from typing import Any


class NotificationsService:
    async def send_invitation_email(self, *args: Any, **kwargs: Any) -> Any:
        # ANG:BEGIN_CUSTOM Notifications.send_invitation_email
        raise NotImplementedError("Implement Notifications.send_invitation_email")
        # ANG:END_CUSTOM Notifications.send_invitation_email
    async def send_password_reset_email(self, *args: Any, **kwargs: Any) -> Any:
        # ANG:BEGIN_CUSTOM Notifications.send_password_reset_email
        raise NotImplementedError("Implement Notifications.send_password_reset_email")
        # ANG:END_CUSTOM Notifications.send_password_reset_email


_service = NotificationsService()


def get_notifications_service() -> NotificationsService:
    return _service
