// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.0
// InputHash: 0e42fb765c8c4c998929a35e33a0793d5ab856e841197e70e8443d4462dc8d2e
// CompilerHash: da4c69e77ddf4e94b49ea759dde0b35e42355a2b062317f6274172a1164123b5
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

package port

//go:generate go run go.uber.org/mock/mockgen@latest -source=$GOFILE -destination=mocks/mock_$GOFILE -package=mocks

import (
	"context"
	"log/slog"
)

// Blog defines the service interface.
type Blog interface {
	// Source: cue/api/comments.cue:12
	CreateComment(ctx context.Context, req CreateCommentRequest) (CreateCommentResponse, error)
	// Source: cue/api/posts.cue:12
	CreatePost(ctx context.Context, req CreatePostRequest) (CreatePostResponse, error)
	// Source: cue/api/posts.cue:65
	GetPost(ctx context.Context, req GetPostRequest) (GetPostResponse, error)
	// Source: cue/api/comments.cue:41
	ListComments(ctx context.Context, req ListCommentsRequest) (ListCommentsResponse, error)
	// Source: cue/api/posts.cue:100
	ListPosts(ctx context.Context, req ListPostsRequest) (ListPostsResponse, error)
	// Source: cue/api/posts.cue:136
	ListMyPosts(ctx context.Context, req ListMyPostsRequest) (ListMyPostsResponse, error)
	// Source: cue/api/tags.cue:12
	ListTags(ctx context.Context, req ListTagsRequest) (ListTagsResponse, error)
	// Source: cue/api/tags.cue:34
	CreateTag(ctx context.Context, req CreateTagRequest) (CreateTagResponse, error)
	// Source: cue/api/comments.cue:71
	UpdateComment(ctx context.Context, req UpdateCommentRequest) (UpdateCommentResponse, error)
	// Source: cue/api/comments.cue:98
	DeleteComment(ctx context.Context, req DeleteCommentRequest) (DeleteCommentResponse, error)
	// Source: cue/api/posts.cue:167
	UpdatePost(ctx context.Context, req UpdatePostRequest) (UpdatePostResponse, error)
	// Source: cue/api/posts.cue:197
	SubmitPost(ctx context.Context, req SubmitPostRequest) (SubmitPostResponse, error)
	// Source: cue/api/posts.cue:218
	PublishPost(ctx context.Context, req PublishPostRequest) (PublishPostResponse, error)
	// Source: cue/api/posts.cue:239
	ArchivePost(ctx context.Context, req ArchivePostRequest) (ArchivePostResponse, error)
	// Source: cue/api/posts.cue:260
	DeletePost(ctx context.Context, req DeletePostRequest) (DeletePostResponse, error)
	// Source: cue/api/tags.cue:70
	UpdateTag(ctx context.Context, req UpdateTagRequest) (UpdateTagResponse, error)
	// Source: cue/api/tags.cue:102
	DeleteTag(ctx context.Context, req DeleteTagRequest) (DeleteTagResponse, error)
}

// Request/Response DTOs
// CreateCommentRequest
// Source: cue/schema/types.cue:13
type CreateCommentRequest struct {
	// Source: cue/api/comments.cue:17
	PostID string `json:"postId" validate:""required,uuid""`
	// Source: cue/api/comments.cue:18
	Content string `json:"content" validate:""required,min=1,max=1000""`
	// Source: cue/api/comments.cue:19
	UserID string `json:"userId"`
}

// LogValue implements slog.LogValuer interface.
func (e CreateCommentRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("postId", e.PostID),
		slog.Any("content", e.Content),
		slog.Any("userId", e.UserID),
	)
}

// CreateCommentResponse
// Source: cue/schema/types.cue:14
type CreateCommentResponse struct {
	// Source: cue/api/comments.cue:23
	ID string `json:"id"`
}

// LogValue implements slog.LogValuer interface.
func (e CreateCommentResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
	)
}

// CreatePostRequest
// Source: cue/schema/types.cue:13
type CreatePostRequest struct {
	// Source: cue/api/posts.cue:17
	Title string `json:"title" validate:""required,min=5,max=200""`
	// Source: cue/api/posts.cue:18
	Content string `json:"content" validate:""required""`
	// Source: cue/api/posts.cue:19
	UserID string `json:"userId"`
	// Source: cue/api/posts.cue:20
	Tags []string `json:"tags"`
}

// LogValue implements slog.LogValuer interface.
func (e CreatePostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("title", e.Title),
		slog.Any("content", e.Content),
		slog.Any("userId", e.UserID),
		slog.Any("tags", e.Tags),
	)
}

// CreatePostResponse
// Source: cue/schema/types.cue:14
type CreatePostResponse struct {
	// Source: cue/api/posts.cue:24
	ID string `json:"id"`
	// Source: cue/api/posts.cue:25
	Slug string `json:"slug"`
}

// LogValue implements slog.LogValuer interface.
func (e CreatePostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("slug", e.Slug),
	)
}

// GetPostRequest
// Source: cue/schema/types.cue:13
type GetPostRequest struct {
	// Source: cue/api/posts.cue:70
	Slug   string `json:"slug" validate:""required""`
	Limit  int    `json:"limit"`
	Offset int    `json:"offset"`
}

// LogValue implements slog.LogValuer interface.
func (e GetPostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("slug", e.Slug),
		slog.Any("limit", e.Limit),
		slog.Any("offset", e.Offset),
	)
}

// GetPostResponse
// Source: cue/schema/types.cue:14
type GetPostResponse struct {
	// Source: cue/api/posts.cue:74
	ID string `json:"id"`
	// Source: cue/api/posts.cue:75
	Title string `json:"title"`
	// Source: cue/api/posts.cue:76
	Content string `json:"content"`
	// Source: cue/api/posts.cue:77
	AuthorID string `json:"authorId"`
	// Source: cue/api/posts.cue:78
	CreatedAt string `json:"createdAt"`
	// Source: cue/api/posts.cue:79
	Tags []GetPostResponseTagsItem `json:"tags"`
}

// LogValue implements slog.LogValuer interface.
func (e GetPostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("title", e.Title),
		slog.Any("content", e.Content),
		slog.Any("authorId", e.AuthorID),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("tags", e.Tags),
	)
}

// ListCommentsRequest
// Source: cue/schema/types.cue:13
type ListCommentsRequest struct {
	// Source: cue/api/comments.cue:46
	PostID string `json:"postId" validate:""required,uuid""`
	// Source: cue/api/comments.cue:47
	Limit int `json:"limit"`
	// Source: cue/api/comments.cue:48
	Offset int `json:"offset"`
}

// LogValue implements slog.LogValuer interface.
func (e ListCommentsRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("postId", e.PostID),
		slog.Any("limit", e.Limit),
		slog.Any("offset", e.Offset),
	)
}

// ListCommentsResponse
// Source: cue/schema/types.cue:14
type ListCommentsResponse struct {
	// Source: cue/api/comments.cue:52
	Data []ListCommentsResponseData `json:"data"`
	// Source: cue/api/comments.cue:58
	Total int `json:"total"`
}

// LogValue implements slog.LogValuer interface.
func (e ListCommentsResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("data", e.Data),
		slog.Any("total", e.Total),
	)
}

// ListPostsRequest
// Source: cue/schema/types.cue:13
type ListPostsRequest struct {
	// Source: cue/api/posts.cue:105
	Tag string `json:"tag"`
	// Source: cue/api/posts.cue:106
	Limit int `json:"limit"`
	// Source: cue/api/posts.cue:107
	Offset int `json:"offset"`
}

// LogValue implements slog.LogValuer interface.
func (e ListPostsRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("tag", e.Tag),
		slog.Any("limit", e.Limit),
		slog.Any("offset", e.Offset),
	)
}

// ListPostsResponse
// Source: cue/schema/types.cue:14
type ListPostsResponse struct {
	// Source: cue/api/posts.cue:111
	Data []ListPostsResponseData `json:"data"`
	// Source: cue/api/posts.cue:118
	Total int `json:"total"`
}

// LogValue implements slog.LogValuer interface.
func (e ListPostsResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("data", e.Data),
		slog.Any("total", e.Total),
	)
}

// ListMyPostsRequest
// Source: cue/schema/types.cue:13
type ListMyPostsRequest struct {
	// Source: cue/api/posts.cue:141
	UserID string `json:"userId"`
	// Source: cue/api/posts.cue:142
	Status string `json:"status"`
	// Source: cue/api/posts.cue:143
	Limit int `json:"limit"`
	// Source: cue/api/posts.cue:144
	Offset int `json:"offset"`
}

// LogValue implements slog.LogValuer interface.
func (e ListMyPostsRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("userId", e.UserID),
		slog.Any("status", e.Status),
		slog.Any("limit", e.Limit),
		slog.Any("offset", e.Offset),
	)
}

// ListMyPostsResponse
// Source: cue/schema/types.cue:14
type ListMyPostsResponse struct {
	// Source: cue/api/posts.cue:148
	Data []ListMyPostsResponseData `json:"data"`
}

// LogValue implements slog.LogValuer interface.
func (e ListMyPostsResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("data", e.Data),
	)
}

// ListTagsRequest
// Source: cue/schema/types.cue:13
type ListTagsRequest struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

// LogValue implements slog.LogValuer interface.
func (e ListTagsRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("limit", e.Limit),
		slog.Any("offset", e.Offset),
	)
}

// ListTagsResponse
// Source: cue/schema/types.cue:14
type ListTagsResponse struct {
	// Source: cue/api/tags.cue:19
	Data []ListTagsResponseData `json:"data"`
}

// LogValue implements slog.LogValuer interface.
func (e ListTagsResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("data", e.Data),
	)
}

// CreateTagRequest
// Source: cue/schema/types.cue:13
type CreateTagRequest struct {
	// Source: cue/api/tags.cue:39
	Name string `json:"name" validate:""required,min=2,max=50""`
	// Source: cue/api/tags.cue:40
	Description string `json:"description"`
}

// LogValue implements slog.LogValuer interface.
func (e CreateTagRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("name", e.Name),
		slog.Any("description", e.Description),
	)
}

// CreateTagResponse
// Source: cue/schema/types.cue:14
type CreateTagResponse struct {
	// Source: cue/api/tags.cue:44
	ID string `json:"id"`
	// Source: cue/api/tags.cue:45
	Slug string `json:"slug"`
}

// LogValue implements slog.LogValuer interface.
func (e CreateTagResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("slug", e.Slug),
	)
}

// UpdateCommentRequest
// Source: cue/schema/types.cue:13
type UpdateCommentRequest struct {
	// Source: cue/api/comments.cue:76
	ID string `json:"id" validate:""required,uuid""`
	// Source: cue/api/comments.cue:77
	Content string `json:"content" validate:""required,min=1,max=1000""`
	// Source: cue/api/comments.cue:78
	UserID string `json:"userId"`
}

// LogValue implements slog.LogValuer interface.
func (e UpdateCommentRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("content", e.Content),
		slog.Any("userId", e.UserID),
	)
}

// UpdateCommentResponse
// Source: cue/schema/types.cue:14
type UpdateCommentResponse struct {
	// Source: cue/api/comments.cue:82
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e UpdateCommentResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// DeleteCommentRequest
// Source: cue/schema/types.cue:13
type DeleteCommentRequest struct {
	// Source: cue/api/comments.cue:103
	ID string `json:"id" validate:""required,uuid""`
	// Source: cue/api/comments.cue:104
	UserID string `json:"userId"`
}

// LogValue implements slog.LogValuer interface.
func (e DeleteCommentRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("userId", e.UserID),
	)
}

// DeleteCommentResponse
// Source: cue/schema/types.cue:14
type DeleteCommentResponse struct {
	// Source: cue/api/comments.cue:108
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e DeleteCommentResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// UpdatePostRequest
// Source: cue/schema/types.cue:13
type UpdatePostRequest struct {
	// Source: cue/api/posts.cue:172
	ID string `json:"id" validate:""required,uuid""`
	// Source: cue/api/posts.cue:173
	Title string `json:"title" validate:"omitempty,"min=5,max=200""`
	// Source: cue/api/posts.cue:174
	Content string `json:"content"`
}

// LogValue implements slog.LogValuer interface.
func (e UpdatePostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("title", e.Title),
		slog.Any("content", e.Content),
	)
}

// UpdatePostResponse
// Source: cue/schema/types.cue:14
type UpdatePostResponse struct {
	// Source: cue/api/posts.cue:178
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e UpdatePostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// SubmitPostRequest
// Source: cue/schema/types.cue:13
type SubmitPostRequest struct {
	// Source: cue/api/posts.cue:202
	ID string `json:"id" validate:""required,uuid""`
}

// LogValue implements slog.LogValuer interface.
func (e SubmitPostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
	)
}

// SubmitPostResponse
// Source: cue/schema/types.cue:14
type SubmitPostResponse struct {
	// Source: cue/api/posts.cue:206
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e SubmitPostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// PublishPostRequest
// Source: cue/schema/types.cue:13
type PublishPostRequest struct {
	// Source: cue/api/posts.cue:223
	ID string `json:"id" validate:""required,uuid""`
}

// LogValue implements slog.LogValuer interface.
func (e PublishPostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
	)
}

// PublishPostResponse
// Source: cue/schema/types.cue:14
type PublishPostResponse struct {
	// Source: cue/api/posts.cue:227
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e PublishPostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// ArchivePostRequest
// Source: cue/schema/types.cue:13
type ArchivePostRequest struct {
	// Source: cue/api/posts.cue:244
	ID string `json:"id" validate:""required,uuid""`
}

// LogValue implements slog.LogValuer interface.
func (e ArchivePostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
	)
}

// ArchivePostResponse
// Source: cue/schema/types.cue:14
type ArchivePostResponse struct {
	// Source: cue/api/posts.cue:248
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e ArchivePostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// DeletePostRequest
// Source: cue/schema/types.cue:13
type DeletePostRequest struct {
	// Source: cue/api/posts.cue:265
	ID string `json:"id" validate:""required,uuid""`
}

// LogValue implements slog.LogValuer interface.
func (e DeletePostRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
	)
}

// DeletePostResponse
// Source: cue/schema/types.cue:14
type DeletePostResponse struct {
	// Source: cue/api/posts.cue:269
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e DeletePostResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// UpdateTagRequest
// Source: cue/schema/types.cue:13
type UpdateTagRequest struct {
	// Source: cue/api/tags.cue:75
	ID string `json:"id"`
	// Source: cue/api/tags.cue:76
	Name string `json:"name" validate:"omitempty,"min=2,max=50""`
	// Source: cue/api/tags.cue:77
	Description string `json:"description"`
}

// LogValue implements slog.LogValuer interface.
func (e UpdateTagRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("name", e.Name),
		slog.Any("description", e.Description),
	)
}

// UpdateTagResponse
// Source: cue/schema/types.cue:14
type UpdateTagResponse struct {
	// Source: cue/api/tags.cue:81
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e UpdateTagResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

// DeleteTagRequest
// Source: cue/schema/types.cue:13
type DeleteTagRequest struct {
	// Source: cue/api/tags.cue:107
	ID string `json:"id"`
}

// LogValue implements slog.LogValuer interface.
func (e DeleteTagRequest) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
	)
}

// DeleteTagResponse
// Source: cue/schema/types.cue:14
type DeleteTagResponse struct {
	// Source: cue/api/tags.cue:111
	Ok bool `json:"ok"`
}

// LogValue implements slog.LogValuer interface.
func (e DeleteTagResponse) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ok", e.Ok),
	)
}

type GetPostResponseTagsItem struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// LogValue implements slog.LogValuer interface.
func (e GetPostResponseTagsItem) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("name", e.Name),
		slog.Any("slug", e.Slug),
	)
}

type ListCommentsResponseData struct {
	ID        string `json:"id"`
	Content   string `json:"content"`
	UserID    string `json:"userId"`
	CreatedAt string `json:"createdAt"`
}

// LogValue implements slog.LogValuer interface.
func (e ListCommentsResponseData) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("content", e.Content),
		slog.Any("userId", e.UserID),
		slog.Any("createdAt", e.CreatedAt),
	)
}

type ListMyPostsResponseData struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Status    string `json:"status"`
	CreatedAt string `json:"createdAt"`
}

// LogValue implements slog.LogValuer interface.
func (e ListMyPostsResponseData) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("title", e.Title),
		slog.Any("status", e.Status),
		slog.Any("createdAt", e.CreatedAt),
	)
}

type ListPostsResponseData struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	AuthorID  string `json:"authorId"`
	CreatedAt string `json:"createdAt"`
}

// LogValue implements slog.LogValuer interface.
func (e ListPostsResponseData) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("title", e.Title),
		slog.Any("slug", e.Slug),
		slog.Any("authorId", e.AuthorID),
		slog.Any("createdAt", e.CreatedAt),
	)
}

type ListTagsResponseData struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

// LogValue implements slog.LogValuer interface.
func (e ListTagsResponseData) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("name", e.Name),
		slog.Any("slug", e.Slug),
		slog.Any("description", e.Description),
	)
}
