// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.81
// InputHash: e62c0030d86d5c8cffa7554e48678fea54dad5a6983506b07abe693991d92506
// CompilerHash: 130133befb383498d0f5e514fc5b5b1fd90348659da200fac0386fde106abf5f
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// Comment represents the domain entity.
// Source: cue/domain/entities.cue:130
type Comment struct {
	// Source: cue/domain/entities.cue:136
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:140
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:145
	AuthorID string `json:"authorId"`
	// Source: cue/domain/entities.cue:150
	ParentID string `json:"parentId"`
	// Source: cue/domain/entities.cue:156
	Content string `json:"content"`
	// Source: cue/domain/entities.cue:161
	CreatedAt time.Time `json:"createdAt"`
	// Source: cue/domain/entities.cue:165
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e *Comment) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Comment) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("postId", e.PostID),
		slog.Any("authorId", e.AuthorID),
		slog.Any("parentId", e.ParentID),
		slog.Any("content", e.Content),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewComment creates a new instance of Comment with default values.
func NewComment() *Comment {
	return &Comment{}
}
