// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.116
// InputHash: 088300c62e9d53b1ad38a3db1564a2a3d6caad413e59a4a2f93593ce31c5de28
// CompilerHash: 268d5e5e04d3594e2f3fff66a6c7beb2c2392ec97d8286321e83c3ec257983fe
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// Comment represents the domain entity.
// Source: cue/domain/entities.cue:163
type Comment struct {
	// Source: cue/domain/entities.cue:169
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:173
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:178
	AuthorID string `json:"authorId"`
	// Source: cue/domain/entities.cue:183
	ParentID string `json:"parentId"`
	// Source: cue/domain/entities.cue:189
	Content string `json:"content"`
	// Source: cue/domain/entities.cue:194
	CreatedAt time.Time `json:"createdAt"`
	// Source: cue/domain/entities.cue:198
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e *Comment) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Comment) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("postId", e.PostID),
		slog.Any("authorId", e.AuthorID),
		slog.Any("parentId", e.ParentID),
		slog.Any("content", e.Content),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewComment creates a new instance of Comment with default values.
func NewComment() *Comment {
	return &Comment{}
}
