// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.94
// InputHash: 4fa1317f67183096ec3725c403afcea8cb7683b885101240f821ee8f6cfef998
// CompilerHash: 69ae3e663ffdf36c126d325756d4cdc925427a9b8e8e770481a1d50dfec04044
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// Comment represents the domain entity.
// Source: cue/domain/entities.cue:163
type Comment struct {
	// Source: cue/domain/entities.cue:169
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:173
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:178
	AuthorID string `json:"authorId"`
	// Source: cue/domain/entities.cue:183
	ParentID string `json:"parentId"`
	// Source: cue/domain/entities.cue:189
	Content string `json:"content"`
	// Source: cue/domain/entities.cue:194
	CreatedAt time.Time `json:"createdAt"`
	// Source: cue/domain/entities.cue:198
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e *Comment) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Comment) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("postId", e.PostID),
		slog.Any("authorId", e.AuthorID),
		slog.Any("parentId", e.ParentID),
		slog.Any("content", e.Content),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewComment creates a new instance of Comment with default values.
func NewComment() *Comment {
	return &Comment{}
}
