// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.65
// InputHash: e62c0030d86d5c8cffa7554e48678fea54dad5a6983506b07abe693991d92506
// CompilerHash: c15beb3a865e4334bb63f22948765f50bd374735242722f1d1383a8269976f8a
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// PostTag represents the domain entity.
// Source: cue/domain/entities.cue:202
type PostTag struct {
	// Source: cue/domain/entities.cue:208
	PostID string `json:"postId"`
	// Source: cue/domain/entities.cue:212
	TagID string `json:"tagId"`
}

func (e *PostTag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *PostTag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("postId", e.PostID),
		slog.Any("tagId", e.TagID),
	)
}

// NewPostTag creates a new instance of PostTag with default values.
func NewPostTag() *PostTag {
	return &PostTag{}
}
