// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.43
// InputHash: 4d22593cd3717a05651c0fd9db8039904fb5f3fb88dad299216dd00bfcb3bbad
// CompilerHash: e5cd89423d770d4d34dfbc0dd5935877609cb707582c9912adb39a5cd27f7a6c
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// PostTag represents the domain entity.
// Source: cue/domain/entities.cue:206
type PostTag struct {
	// Source: cue/domain/entities.cue:211
	PostID any `json:"postId"`
	// Source: cue/domain/entities.cue:215
	TagID any `json:"tagId"`
}

func (e *PostTag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *PostTag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("postId", e.PostID),
		slog.Any("tagId", e.TagID),
	)
}

// NewPostTag creates a new instance of PostTag with default values.
func NewPostTag() *PostTag {
	return &PostTag{}
}
