// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.0
// InputHash: 12a2d15917a8359b50776637eaa499092103d9da09ac5563b4ace58288118ad9
// CompilerHash: 34e34d2704326e3ba340e2fe5d68517a122526347d96a856190d2b3b8a7ea91b
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// PostTag represents the domain entity.
// Source: cue/domain/entities.cue:206
type PostTag struct {
	// Source: cue/domain/entities.cue:207
	Name string `json:"name"`
	// Source: cue/domain/entities.cue:208
	Description string `json:"description"`
	// Source: cue/domain/entities.cue:210
	Fields any `json:"fields"`
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *PostTag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("name", e.Name),
		slog.Any("description", e.Description),
		slog.Any("fields", e.Fields),
	)
}

// NewPostTag creates a new instance of PostTag with default values.
func NewPostTag() *PostTag {
	return &PostTag{
		Name:        "PostTag",
		Description: "Post-Tag relationship",
	}
}
