// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.51
// InputHash: 027eaf3d0fffed4e5d3dbe6c68942a856acd710227485d4e2e76bb27357fa14a
// CompilerHash: 08a642c084b87d9392c0c2534fdbe0ff4b08989904e030ab4a5d545a605fc59c
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// Tag represents the domain entity.
// Source: cue/domain/entities.cue:181
type Tag struct {
	// Source: cue/domain/entities.cue:187
	ID any `json:"id"`
	// Source: cue/domain/entities.cue:191
	Name any `json:"name"`
	// Source: cue/domain/entities.cue:196
	Slug any `json:"slug"`
	// Source: cue/domain/entities.cue:201
	Description any `json:"description"`
}

func (e *Tag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Tag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("name", e.Name),
		slog.Any("slug", e.Slug),
		slog.Any("description", e.Description),
	)
}

// NewTag creates a new instance of Tag with default values.
func NewTag() *Tag {
	return &Tag{}
}
