// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.127
// InputHash: 41403d8f2296dfbebff46b0c1b6bf0e0f89c2e7911abc2bee84c8fabd12dae42
// CompilerHash: 294b50c17c5868adf98ff6e7e34d9b0ddcf67156d863f2f508ad57df44889164
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// Tag represents the domain entity.
// Source: cue/domain/entities.cue:206
type Tag struct {
	// Source: cue/domain/entities.cue:212
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:216
	Name string `json:"name"`
	// Source: cue/domain/entities.cue:221
	Slug string `json:"slug"`
	// Source: cue/domain/entities.cue:226
	Description string `json:"description"`
	// Source: cue/domain/entities.cue:231
	CreatedAt time.Time `json:"createdAt"`
}

func (e *Tag) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *Tag) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("name", e.Name),
		slog.Any("slug", e.Slug),
		slog.Any("description", e.Description),
		slog.Any("createdAt", e.CreatedAt),
	)
}

// NewTag creates a new instance of Tag with default values.
func NewTag() *Tag {
	return &Tag{}
}
