// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.126
// InputHash: e35af9b70b6e67ef91124c58eb216193bf82f2081b617d1fc3c217cfb9f018d4
// CompilerHash: d750a4f1ea119b1ed98e6675984d9051ef5da82743ec0588c733cbb3ab71c0d4
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// UserVault represents the domain entity.
// Source: cue/domain/vault.cue:5
type UserVault struct {
	// Source: cue/domain/vault.cue:6
	ID string `json:"ID"`
	// Source: cue/domain/vault.cue:7
	PersonalKey string `json:"personalKey"`
	// Source: cue/domain/vault.cue:8
	Bio string `json:"bio"`
}

func (e *UserVault) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *UserVault) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("personalKey", e.PersonalKey),
		slog.Any("bio", e.Bio),
	)
}

// NewUserVault creates a new instance of UserVault with default values.
func NewUserVault() *UserVault {
	return &UserVault{}
}
