// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.2.2
// InputHash: 2296caed74fdde9812254e75795150a89ee654796273fcb9ef6ddb9c5d768fd5
// CompilerHash: c6ff969c4f849a3d43096b736ea8243bff5fb2015fae31865c80a26ea3379894
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// UserVault represents the domain entity.
// Source: cue/domain/vault.cue:5
type UserVault struct {
	// Source: cue/domain/vault.cue:6
	ID string `json:"id"`
	// Source: cue/domain/vault.cue:7
	PersonalKey string `json:"personalKey"`
	// Source: cue/domain/vault.cue:8
	Bio string `json:"bio"`
}

func (e *UserVault) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *UserVault) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("personalKey", e.PersonalKey),
		slog.Any("bio", e.Bio),
	)
}

// NewUserVault creates a new instance of UserVault with default values.
func NewUserVault() *UserVault {
	return &UserVault{}
}
