// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.0
// InputHash: 0e42fb765c8c4c998929a35e33a0793d5ab856e841197e70e8443d4462dc8d2e
// CompilerHash: da4c69e77ddf4e94b49ea759dde0b35e42355a2b062317f6274172a1164123b5
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// User represents the domain entity.
// Source: cue/domain/entities.cue:12
type User struct {
	// Source: cue/domain/entities.cue:13
	Name string `json:"name"`
	// Source: cue/domain/entities.cue:14
	Description string `json:"description"`
	// Source: cue/domain/entities.cue:16
	Fields any `json:"fields"`
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *User) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("name", e.Name),
		slog.Any("description", e.Description),
		slog.Any("fields", e.Fields),
	)
}

// NewUser creates a new instance of User with default values.
func NewUser() *User {
	return &User{
		Name:        "User",
		Description: "Blog user account",
	}
}
