// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.118
// InputHash: 81e2bf1461d6069d65f3599ef6dea1fb5c4539ded74aab44135ad8bfa631e0be
// CompilerHash: 80a6e04b3ae0ee93fce9e9c276774f7e7bafaa3c5eeea6a5f86f57d9685e5c5c
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// UserVault represents the domain entity.
// Source: cue/domain/vault.cue:5
type UserVault struct {
	// Source: cue/domain/vault.cue:6
	ID string `json:"ID"`
	// Source: cue/domain/vault.cue:7
	PersonalKey string `json:"personalKey"`
	// Source: cue/domain/vault.cue:8
	Bio string `json:"bio"`
}

func (e *UserVault) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *UserVault) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("personalKey", e.PersonalKey),
		slog.Any("bio", e.Bio),
	)
}

// NewUserVault creates a new instance of UserVault with default values.
func NewUserVault() *UserVault {
	return &UserVault{}
}
