// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.51
// InputHash: 027eaf3d0fffed4e5d3dbe6c68942a856acd710227485d4e2e76bb27357fa14a
// CompilerHash: 08a642c084b87d9392c0c2534fdbe0ff4b08989904e030ab4a5d545a605fc59c
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
)

// User represents the domain entity.
// Source: cue/domain/entities.cue:12
type User struct {
	// Source: cue/domain/entities.cue:18
	ID any `json:"id"`
	// Source: cue/domain/entities.cue:22
	Email any `json:"email"`
	// Source: cue/domain/entities.cue:27
	PhoneNumber any `json:"phoneNumber"`
	// Source: cue/domain/entities.cue:31
	PasswordHash any `json:"passwordHash"`
	// Source: cue/domain/entities.cue:35
	Name any `json:"name"`
	// Source: cue/domain/entities.cue:40
	Role any `json:"role"`
	// Source: cue/domain/entities.cue:45
	AvatarURL any `json:"avatarUrl"`
	// Source: cue/domain/entities.cue:50
	CreatedAt any `json:"createdAt"`
	// Source: cue/domain/entities.cue:54
	UpdatedAt any `json:"updatedAt"`
}

func (e *User) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *User) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("id", e.ID),
		slog.Any("email", e.Email),
		slog.Any("phoneNumber", e.PhoneNumber),
		slog.String("passwordHash", "***"),
		slog.Any("name", e.Name),
		slog.Any("role", e.Role),
		slog.Any("avatarUrl", e.AvatarURL),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewUser creates a new instance of User with default values.
func NewUser() *User {
	return &User{}
}
