// ============================================================================
// AUTO-GENERATED by ANG (Architectural Normalized Generator)
// Version: 0.1.118
// InputHash: 81e2bf1461d6069d65f3599ef6dea1fb5c4539ded74aab44135ad8bfa631e0be
// CompilerHash: 80a6e04b3ae0ee93fce9e9c276774f7e7bafaa3c5eeea6a5f86f57d9685e5c5c
// DO NOT EDIT - changes will be overwritten on next generation
// GENERATED: true
// ============================================================================

// Package domain contains domain entities and business logic.
package domain

import (
	"log/slog"
	"time"
)

// User represents the domain entity.
// Source: cue/domain/entities.cue:12
type User struct {
	// Source: cue/domain/entities.cue:18
	ID string `json:"ID"`
	// Source: cue/domain/entities.cue:22
	Email string `json:"email"`
	// Source: cue/domain/entities.cue:35
	PasswordHash string `json:"passwordHash"`
	// Source: cue/domain/entities.cue:48
	Name string `json:"name"`
	// Source: cue/domain/entities.cue:59
	Role string `json:"role"`
	// Source: cue/domain/entities.cue:64
	AvatarURL string `json:"avatarUrl"`
	// Source: cue/domain/entities.cue:75
	CreatedAt time.Time `json:"createdAt"`
	// Source: cue/domain/entities.cue:79
	UpdatedAt time.Time `json:"updatedAt"`
}

func (e *User) Validate() error {
	return nil
}

// LogValue implements slog.LogValuer interface.
// It automatically masks fields marked as @secret or @pii.
func (e *User) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("ID", e.ID),
		slog.Any("email", e.Email),
		slog.String("passwordHash", "***"),
		slog.Any("name", e.Name),
		slog.Any("role", e.Role),
		slog.Any("avatarUrl", e.AvatarURL),
		slog.Any("createdAt", e.CreatedAt),
		slog.Any("updatedAt", e.UpdatedAt),
	)
}

// NewUser creates a new instance of User with default values.
func NewUser() *User {
	return &User{}
}
