// AUTO-GENERATED by ANG
import { apiClient, validateResponse, type ApiRequestOptions } from '../api-client';
import * as Types from '../types';

type ParamRecord = Record<string, unknown>;

const toParamRecord = (params: unknown): ParamRecord =>
  params && typeof params === 'object' ? (params as ParamRecord) : {};

const getPathParamValue = (params: ParamRecord, primary: string, aliases: string[] = []) => {
  const candidates = [primary, ...aliases];
  for (const key of candidates) {
    const value = params[key];
    if (value === undefined || value === null) {
      continue;
    }
    const text = String(value).trim();
    if (text !== '') {
      return text;
    }
  }
  throw new Error(`Missing required path param: ${primary}`);
};

const omitKeys = (params: ParamRecord, keys: string[]): ParamRecord => {
  const next: ParamRecord = { ...params };
  for (const key of keys) {
    delete next[key];
  }
  return next;
};
export const deleteComment = (
  params: Types.DeleteCommentRequest = {} as Types.DeleteCommentRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.delete<Types.DeleteCommentResponse>(`/comments/${id}`, { data: params, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('DeleteCommentResponseSchema', data, 'DeleteComment');
    }
    return data;
  });
};
export const updateComment = (
  params: Types.UpdateCommentRequest = {} as Types.UpdateCommentRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.put<Types.UpdateCommentResponse>(`/comments/${id}`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('UpdateCommentResponseSchema', data, 'UpdateComment');
    }
    return data;
  });
};
export const listMyPosts = (
  params: Types.ListMyPostsRequest = {} as Types.ListMyPostsRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const queryParams = omitKeys(toParamRecord(params), []);
  return apiClient.get<Types.ListMyPostsResponse>(`/my/posts`, { params: queryParams, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('ListMyPostsResponseSchema', data, 'ListMyPosts');
    }
    return data;
  });
};
export const listPosts = (
  params: Types.ListPostsRequest = {} as Types.ListPostsRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const queryParams = omitKeys(toParamRecord(params), []);
  return apiClient.get<Types.ListPostsResponse>(`/posts`, { params: queryParams, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('ListPostsResponseSchema', data, 'ListPosts');
    }
    return data;
  });
};
export const createPost = (
  params: Types.CreatePostRequest = {} as Types.CreatePostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  return apiClient.post<Types.CreatePostResponse>(`/posts`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('CreatePostResponseSchema', data, 'CreatePost');
    }
    return data;
  });
};
export const deletePost = (
  params: Types.DeletePostRequest = {} as Types.DeletePostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.delete<Types.DeletePostResponse>(`/posts/${id}`, { data: params, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('DeletePostResponseSchema', data, 'DeletePost');
    }
    return data;
  });
};
export const updatePost = (
  params: Types.UpdatePostRequest = {} as Types.UpdatePostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.put<Types.UpdatePostResponse>(`/posts/${id}`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('UpdatePostResponseSchema', data, 'UpdatePost');
    }
    return data;
  });
};
export const archivePost = (
  params: Types.ArchivePostRequest = {} as Types.ArchivePostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.post<Types.ArchivePostResponse>(`/posts/${id}/archive`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('ArchivePostResponseSchema', data, 'ArchivePost');
    }
    return data;
  });
};
export const publishPost = (
  params: Types.PublishPostRequest = {} as Types.PublishPostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.post<Types.PublishPostResponse>(`/posts/${id}/publish`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('PublishPostResponseSchema', data, 'PublishPost');
    }
    return data;
  });
};
export const submitPost = (
  params: Types.SubmitPostRequest = {} as Types.SubmitPostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.post<Types.SubmitPostResponse>(`/posts/${id}/submit`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('SubmitPostResponseSchema', data, 'SubmitPost');
    }
    return data;
  });
};
export const listComments = (
  params: Types.ListCommentsRequest = {} as Types.ListCommentsRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const postID = getPathParamValue(paramsRecord, 'postID', ['postId']);
  const queryParams = omitKeys(toParamRecord(params), ['postID', 'postId']);
  return apiClient.get<Types.ListCommentsResponse>(`/posts/${postID}/comments`, { params: queryParams, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('ListCommentsResponseSchema', data, 'ListComments');
    }
    return data;
  });
};
export const createComment = (
  params: Types.CreateCommentRequest = {} as Types.CreateCommentRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const postID = getPathParamValue(paramsRecord, 'postID', ['postId']);
  return apiClient.post<Types.CreateCommentResponse>(`/posts/${postID}/comments`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('CreateCommentResponseSchema', data, 'CreateComment');
    }
    return data;
  });
};
export const getPost = (
  params: Types.GetPostRequest = {} as Types.GetPostRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const slug = getPathParamValue(paramsRecord, 'slug', []);
  const queryParams = omitKeys(toParamRecord(params), ['slug']);
  return apiClient.get<Types.GetPostResponse>(`/posts/${slug}`, { params: queryParams, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('GetPostResponseSchema', data, 'GetPost');
    }
    return data;
  });
};
export const listTags = (
  params: Types.ListTagsRequest = {} as Types.ListTagsRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const queryParams = omitKeys(toParamRecord(params), []);
  return apiClient.get<Types.ListTagsResponse>(`/tags`, { params: queryParams, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('ListTagsResponseSchema', data, 'ListTags');
    }
    return data;
  });
};
export const createTag = (
  params: Types.CreateTagRequest = {} as Types.CreateTagRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  return apiClient.post<Types.CreateTagResponse>(`/tags`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('CreateTagResponseSchema', data, 'CreateTag');
    }
    return data;
  });
};
export const deleteTag = (
  params: Types.DeleteTagRequest = {} as Types.DeleteTagRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.delete<Types.DeleteTagResponse>(`/tags/${id}`, { data: params, signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('DeleteTagResponseSchema', data, 'DeleteTag');
    }
    return data;
  });
};
export const updateTag = (
  params: Types.UpdateTagRequest = {} as Types.UpdateTagRequest,
  requestOptions: ApiRequestOptions = {}
) => {
  const paramsRecord = toParamRecord(params);
  const id = getPathParamValue(paramsRecord, 'id', ['ID']);
  return apiClient.put<Types.UpdateTagResponse>(`/tags/${id}`, params, { signal: requestOptions.signal }).then((r) => {
    const data = r.data;
    if (import.meta.env.DEV) {
      validateResponse('UpdateTagResponseSchema', data, 'UpdateTag');
    }
    return data;
  });
};
