openapi: 3.0.3
info:
  title: ANG API
  version: 0.1.0
  x-ang-version: 0.1.126
  x-ang-input-hash: 814ec3f9b96d4fb4583c9d3884daec6b98af5648440dd2b3457e19840dd94621
  x-ang-compiler-hash: 29a8f520277aa6f4d2ff45be2952a732164a1e0860bf797c7d714de4f1da85f9
paths:
  /users:
    get:
      summary: ListUsers
      operationId: ListUsers
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            maximum: 100
            default: 20
        - in: query
          name: offset
          schema:
            type: integer
      responses:
        '200':
          description: OK
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListUsersResponse'
        '401':
          description: Unauthorized
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'

components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
        code:
          type: integer
        errors:
          type: object
    ListUsersRequest:
      type: object
      properties:
        limit:
          type: integer
          format: int64
        offset:
          type: integer
          format: int64
    ListUsersResponse:
      type: object
      properties:
        data:
          type: array
          items:
            type: string
      required:
        - data
    ListUsersResponseData:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        name:
          type: string
      required:
        - id
        - email
        - name
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
