"""Report service stub generated by ANG."""

from __future__ import annotations

from typing import Any

from fastapi import Response
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
import io
import matplotlib.pyplot as plt


class ReportService:
    async def generate_report_pdf(self, *args: Any, **kwargs: Any) -> Any:
        payload = args[0] if args else kwargs.get("payload", {})
        if hasattr(payload, "model_dump"):
            payload = payload.model_dump()

        title = payload.get("title") or "PDF Chart Report"
        raw_points = payload.get("points") or []
        if not raw_points:
            raw_points = [
                {"x": 1, "y": 3},
                {"x": 2, "y": 4.2},
                {"x": 3, "y": 2.8},
                {"x": 4, "y": 5.1},
            ]

        xs = [float(p.get("x", 0)) for p in raw_points]
        ys = [float(p.get("y", 0)) for p in raw_points]

        fig, ax = plt.subplots(figsize=(7, 3.2))
        ax.plot(xs, ys, marker="o", linewidth=2)
        ax.set_title(title)
        ax.set_xlabel("X")
        ax.set_ylabel("Y")
        ax.grid(alpha=0.3)

        img_buffer = io.BytesIO()
        fig.savefig(img_buffer, format="png", dpi=160, bbox_inches="tight")
        plt.close(fig)
        img_buffer.seek(0)

        pdf_buffer = io.BytesIO()
        pdf = canvas.Canvas(pdf_buffer, pagesize=A4)
        width, height = A4

        pdf.setTitle(title)
        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(40, height - 48, title)
        pdf.setFont("Helvetica", 10)
        pdf.drawString(40, height - 64, "Generated by ANG Python example service")

        pdf.drawImage(ImageReader(img_buffer), 40, height - 380, width=520, height=280, preserveAspectRatio=True, mask="auto")
        pdf.setFont("Helvetica", 9)
        pdf.drawString(40, 36, "POST /reports/pdf")

        pdf.showPage()
        pdf.save()
        pdf_buffer.seek(0)

        return Response(
            content=pdf_buffer.getvalue(),
            media_type="application/pdf",
            headers={"Content-Disposition": "inline; filename=report.pdf"},
        )


_service = ReportService()


def get_report_service() -> ReportService:
    return _service
